'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const ROOT=path.resolve(__dirname,'..'), C=require(ROOT+'/source/maths_script_1.js'),D=require(ROOT+'/source/curriculum.json'), L=C.library(D);
const results=[];function check(category,name,expected,fn,issue=''){const id=category+'-'+String(results.filter(x=>x.category===category).length+1).padStart(3,'0');let status='PASS',actual;try{actual=fn();}catch(e){status='FAIL';actual=e.message;}results.push({id,category,name,expected,status,actual:actual??'符合預期',issue:status==='FAIL'?issue:''});}
const eq=(a,b)=>assert.deepEqual(a,b);const ok=(a,msg)=>assert.ok(a,msg);const clone=C.clone;
function correct(q){let expression='';if(q.type==='word')expression=q.skill==='2N5.3'?`${q.params.paid}-${q.params.price}`:`${q.params.paid}-${q.params.price}*${q.params.qty}`;return {value:q.answer,expression,unit:q.unit,remainder:q.remainder??''};}
const q0=C.generate(L,'1N2.2-T2',42), fixed=Date.UTC(2026,8,28,3), DAY=86400000;
function stateAttempt(){let s=C.blank();C.record(s,L,q0,correct(q0),{id:'attempt1',at:fixed,time_ms:3000});return s;}
function stateCurrent(){let s=C.blank();s.current={id:'session1',skill:q0.skill,track:'normal',mode:'practice',game:null,stage:4,index:0,queues:{4:[{template:q0.templateId,seed:q0.seed}]},example:{template:q0.templateId,seed:q0.seed},startedAt:fixed,questionAt:fixed,hint:0,feedback:null,results:[],replacements:[],completed:false};return s;}
function stateReward(){let s=C.blank();C.enqueueReward(s,{key:'normal:1N2.2',startedAt:fixed,completedAt:fixed+4000,valid:true});return s;}
// 504 deterministic fixtures are independently checked with Python Fraction, not this engine.
const fixtures=[];for(const t of D.templates)for(const seed of [0,1,2,42,65535,4294967295])fixtures.push({template:t,question:C.generate(L,t.id,seed)});
fs.writeFileSync(ROOT+'/results/generated_fixtures.json',JSON.stringify(fixtures,null,2));
// 84 marker scenarios: correct, wrong, malformed, fullwidth, and equivalent fraction slash when relevant.
for(const t of D.templates){check('GRADE',t.id+'：完整答案、錯答及輸入正規化','正答全分；錯答不全分；空白不記分；全形／等值分數可判分',()=>{const q=C.generate(L,t.id,42),a=correct(q);let r=C.mark(q,a);ok(r.correct,JSON.stringify({input:a,result:r}));const wrong={...a,value:C.Q.parse(q.answer).add(17).toString()};ok(!C.mark(q,wrong).correct,'錯誤答案被判全對');ok(!C.mark(q,{...a,value:''}).valid,'空白被當成有效答案');const fw={...a,value:a.value.replace(/[0-9/]/g,c=>String.fromCharCode(c.charCodeAt(0)+0xfee0))};ok(C.mark(q,fw).correct,'全形正答不獲全分');if(q.answer.includes('/')){const unicode={...a,value:q.answer.replace('/','⁄')};r=C.mark(q,unicode);ok(r.correct,'等值分數 '+unicode.value+' 被拒絕：'+JSON.stringify(r));}return {template:t.id,seed:q.seed,answer:q.answer,variants:q.answer.includes('/')?5:4};},'F-FRACTION-SLASH');}
// 80 parser cases. Expected values are literals, not generated by the implementation.
const qValid=[['0','0'],['-0','0'],['+7','7'],['0009','9'],[' 12 ','12'],['１／２','1/2'],['1⁄2','1/2'],['½','1/2'],['−3','-3'],['.5','1/2'],['-.5','-1/2'],['2.','2'],['0.125','1/8'],['-1.25','-5/4'],['2/4','1/2'],['7/1','7'],['1 1/2','3/2'],['-1 1/2','-3/2'],['-0 1/2','-1/2'],['99999999999999999999','99999999999999999999']];
const qInvalid=['',' ','NaN','Infinity','-Infinity','1e3','0x10','1,000','1/0','2/0','1/-2','1 2/2','1 5/2','1..2','--1','1+1','abc','2/3/4','1%','9'.repeat(61)];
for(const [x,want]of qValid)check('PARSER','有理數輸入 '+JSON.stringify(x),'精確結果 '+want,()=>{eq(C.Q.parse(x).toString(),want);return want;});
for(const x of qInvalid)check('PARSER','拒絕無效數字 '+JSON.stringify(x),'丟出格式錯誤而非產生錯誤數值',()=>{assert.throws(()=>C.Q.parse(x));return '已拒絕';});
const eValid=[['1+2*3','7'],['(1+2)*3','9'],['8/4/2','1'],['8/(4/2)','4'],['-3*2','-6'],['1--2','3'],['+5','5'],['0.1+0.2','3/10'],['1/3+1/6','1/2'],['floor(7/3)','2'],['floor(-7/3)','-3'],['7%3','1'],['-7%3','-1'],['２ × ３','6'],['12÷4','3'],['2x3','6'],['(2+1)x4','12'],['a*2+1','15'],['-(3+2)','-5'],['1+2+3+4','10']];
const eInvalid=['','1+','(1+2','1+2)','window.alert(1)','globalThis','__proto__','constructor','1;2','2**3','1,2','floor()','foo(1)','0/0','1/0','1%0','(1/2)%2',''.padStart(25,'(')+'1'+''.padStart(25,')'),'9'.repeat(241),'a.b'];
for(const [x,want]of eValid)check('PARSER','算式 '+JSON.stringify(x),'精確結果 '+want,()=>{eq(C.evaluate(x,{a:7}).toString(),want);return want;});
for(const x of eInvalid)check('PARSER','拒絕非支援算式 '+JSON.stringify(x).slice(0,100),'拒絕錯誤或非數學指令',()=>{assert.throws(()=>C.evaluate(x));return '已拒絕';});
// 96 backup/schema cases; fixture mutations are explicit and auditable.
const mutations=[];function mut(name,build,fn,issue='F-SCHEMA'){mutations.push({name,build,fn,issue});}
mut('版本為 0',C.blank,s=>s.schema=0);mut('版本為字串',C.blank,s=>s.schema='1');mut('缺少版本',C.blank,s=>delete s.schema);
for(const [k,vals] of [['revision',[-1,.5,1000000001,'1',null]],['serial',[-1,.5,1000000001,'1',null]]])for(const v of vals)mut(k+' 非法值 '+JSON.stringify(v),C.blank,s=>s[k]=v);
mut('attempts 不是列表',C.blank,s=>s.attempts={});mut('attempts 超過 5000 筆',stateAttempt,s=>s.attempts=Array.from({length:5001},(_,i)=>({...s.attempts[0],id:'a'+i})));mut('作答 ID 重複',stateAttempt,s=>s.attempts.push(clone(s.attempts[0])));
for(const [k,vals] of [['id',['','__proto__']],['skill',['missing']],['track',['olympiad']],['hint',[-1,6,.5]],['time_ms',[-1,3600001,'20']],['at',[0,-1,null,1e20]],['correct',['true']],['template',['missing',null]],['seed',[-1,4294967296,1.5,null]],['credit',[-1,2,null]],['difficulty',[0,4]],['independent',['true']],['mode',['not-a-mode']]])for(const v of vals)mut('作答 '+k+' = '+JSON.stringify(v),stateAttempt,s=>s.attempts[0][k]=v,'F-ATTEMPT-VALIDATION');
mut('普通數學掌握度為陣列',C.blank,s=>s.mastery.normal=[],'F-ARRAY-STATE');mut('奧數掌握度為陣列',C.blank,s=>s.mastery.olympiad=[],'F-ARRAY-STATE');
mut('掌握度跨路線',stateAttempt,s=>{s.mastery.olympiad[q0.skill]=s.mastery.normal[q0.skill];delete s.mastery.normal[q0.skill]});
for(const v of [-1,101,'50'])mut('掌握度分數 '+v,stateAttempt,s=>s.mastery.normal[q0.skill].score=v);
mut('掌握度證據超過 5 筆',stateAttempt,s=>s.mastery.normal[q0.skill].recent=Array(6).fill(s.mastery.normal[q0.skill].recent[0]));
mut('掌握度重溫日期不存在',stateAttempt,s=>s.mastery.normal[q0.skill].next='2026-02-30');
mut('掌握度獨立作答為字串',stateAttempt,s=>s.mastery.normal[q0.skill].recent[0].independent='yes');
mut('學習語言錯誤',C.blank,s=>s.settings.language='xx');mut('語音設定錯誤',C.blank,s=>s.settings.voice='xx');
for(const v of [4,91,5.5])mut('每天時限 '+v,C.blank,s=>s.settings.limit=v);
for(const k of ['sound','slow','olympiad','showScore'])mut('設定 '+k+' 不是布林',C.blank,s=>s.settings[k]='true');
mut('學校單元字串過長',C.blank,s=>s.settings.schoolUnit='x'.repeat(31));
mut('使用時間為陣列',C.blank,s=>s.usage=[],'F-ARRAY-STATE');mut('使用時間負數',C.blank,s=>s.usage['2026-09-28']=-1);mut('使用時間超過一天',C.blank,s=>s.usage['2026-09-28']=86400001);mut('使用日期不存在',C.blank,s=>s.usage['2026-02-30']=1000,'F-USAGE-DATE');
mut('錯題本為陣列',C.blank,s=>s.mistakes=[]);mut('課堂紀錄為陣列',C.blank,s=>s.lessons=[]);mut('錢包日期為陣列',C.blank,s=>s.wallet.days=[]);
mut('錢包負餘額',C.blank,s=>s.wallet.balance=-1);mut('錢包超上限',C.blank,s=>s.wallet.balance=1000001);
mut('不存在策略卡',C.blank,s=>s.cards=['not-a-card']);mut('策略卡數量超上限',C.blank,s=>s.cards=Array(31).fill(D.cards[0].id));
mut('獎勵紀錄超 200 筆',stateReward,s=>s.outbox=Array.from({length:201},(_,i)=>({...s.outbox[0],id:'reward'+i})));
mut('獎勵完成早於開始',stateReward,s=>s.outbox[0].completedAt=fixed-1);mut('獎勵非有效事件',stateReward,s=>s.outbox[0].valid=false);mut('結算狀態為字串',stateReward,s=>s.outbox[0].settled='yes');mut('獎勵分數超上限',stateReward,s=>s.outbox[0].award=6);mut('獎勵日期不存在',stateReward,s=>s.outbox[0].day='2026-02-30');
mut('課堂模式錯誤',stateCurrent,s=>s.current.mode='x');mut('課堂技能跨路線',stateCurrent,s=>s.current.track='olympiad');mut('課堂題目種子負值',stateCurrent,s=>s.current.queues[4][0].seed=-1);mut('課堂題號越界',stateCurrent,s=>s.current.index=1);mut('練習階段缺少題目佇列',stateCurrent,s=>s.current.queues={},'F-CURRENT-QUEUE');mut('課堂遊戲名稱錯誤',stateCurrent,s=>s.current.game='unknown');
mut('原型污染欄位',C.blank,s=>Object.defineProperty(s,'__proto__',{value:{polluted:true},enumerable:true}));mut('巢狀 constructor 欄位',C.blank,s=>s.extra={constructor:{}});mut('備份巢狀超深',C.blank,s=>{let x=s;for(let i=0;i<26;i++)x=x.extra={};});mut('備份大於 2.5MB',C.blank,s=>s.extra='x'.repeat(2500001));
mut('作答模板與技能不相符',stateAttempt,s=>s.attempts[0].template='O-CAL-pattern-T1','F-ATTEMPT-VALIDATION');
mut('掌握度證據難度 0',stateAttempt,s=>s.mastery.normal[q0.skill].recent[0].difficulty=0);
mut('錯題重溫日期不存在',C.blank,s=>s.mistakes['normal:'+q0.skill]={skill:q0.skill,track:'normal',due:['2026-02-30'],successes:0,lastSeed:42,cleared:false});
mut('題目報錯引用不存在模板',C.blank,s=>s.reports=[{template:'missing',seed:42,at:fixed}]);
mut('最近出題引用不存在技能',C.blank,s=>s.lastGenerated={missing:'x'});
mut('課堂結果分數超上限',stateCurrent,s=>s.current.results=[{skill:q0.skill,correct:true,hint:0,credit:2}]);
// Counts fail loudly rather than silently padding the target.
console.log('STATE planned',mutations.length);
for(const m of mutations)check('STATE',m.name,'拒絕不符合資料模型的備份，保留原檔',()=>{let s=m.build();m.fn(s);let accepted=false;try{C.validateState(s,L);accepted=true;}catch(e){return {rejected:true,reason:e.message};}ok(!accepted,'不合法資料被 validateState 接受');},m.issue);
// 56 learning / reward / scheduling cases (28 per-skill track-isolation cases plus 28 behaviours).
for(const sk of D.skills)check('LEARNING',sk.id+' 作答只更新本路線','該技能有紀錄，另一條路線沒有變動',()=>{let s=C.blank(),q=C.generate(L,sk.id+'-T2',42);C.record(s,L,q,correct(q),{id:'x',at:fixed});ok(s.mastery[sk.track][sk.id]);eq(Object.keys(s.mastery[sk.track==='normal'?'olympiad':'normal']).length,0);return {track:sk.track,score:s.mastery[sk.track][sk.id].score};});
check('LEARNING','同一作答 ID 不重複計分','只保留一筆',()=>{let s=stateAttempt();let r=C.record(s,L,q0,correct(q0),{id:'attempt1',at:fixed});ok(r.duplicate);eq(s.attempts.length,1);});
check('LEARNING','空白答案不污染作答紀錄','0 筆',()=>{let s=C.blank();C.record(s,L,q0,'',{id:'blank',at:fixed});eq(s.attempts.length,0);});
for(const mode of ['guided','challenge-demo'])check('LEARNING',mode+' 不直接增加掌握度','作答有紀錄但掌握度空白',()=>{let s=C.blank();C.record(s,L,q0,correct(q0),{id:'x',at:fixed,mode});eq(Object.keys(s.mastery.normal).length,0);eq(s.attempts.length,1);});
for(const hint of [4,5])check('LEARNING','提示 '+hint+' 不能達成獨立掌握','即使多次答對仍未掌握',()=>{let s=C.blank();for(let i=0;i<25;i++)C.record(s,L,q0,correct(q0),{id:'x'+i,at:fixed+i,hint});ok(!C.isMastered(C.mastery(s,L.skills.get(q0.skill))));});
check('LEARNING','足夠獨立中階正答達成掌握','掌握及翌日重溫',()=>{let s=C.blank();for(let i=0;i<25;i++){let q=C.generate(L,q0.templateId,i);C.record(s,L,q,correct(q),{id:'x'+i,at:fixed+i});}let m=C.mastery(s,L.skills.get(q0.skill));ok(C.isMastered(m));eq(m.next,'2026-09-29');});
check('LEARNING','錯題安排翌日重溫','翌日、三日、七日',()=>{let s=C.blank();C.record(s,L,q0,{value:'999'},{id:'w',at:fixed});eq(s.mistakes['normal:'+q0.skill].due,['2026-09-29','2026-10-01','2026-10-05']);});
check('LEARNING','同一題種子不能清除錯題','successes 保持 0',()=>{let s=C.blank();C.record(s,L,q0,{value:'999'},{id:'w',at:fixed});C.record(s,L,q0,correct(q0),{id:'r',at:fixed+1});eq(s.mistakes['normal:'+q0.skill].successes,0);});
check('LEARNING','兩題不同種子答對清除錯題','cleared=true',()=>{let s=C.blank();C.record(s,L,q0,{value:'999'},{id:'w',at:fixed});for(const seed of [1,2]){let q=C.generate(L,q0.templateId,seed);C.record(s,L,q,correct(q),{id:'r'+seed,at:fixed+seed});}ok(s.mistakes['normal:'+q0.skill].cleared);});
check('LEARNING','下一題與上一題不同數字','題幹與答案簽章不同',()=>{let s=C.blank(),a=C.nextQuestion(s,L,'1N2.2',2),b=C.nextQuestion(s,L,'1N2.2',2);ok(a.stem_zh+'|'+a.answer!==b.stem_zh+'|'+b.answer);});
check('LEARNING','每日練習數量與路線','10 個普通技能',()=>{let ids=C.planDaily(C.blank(),L,{grade:1});eq(ids.length,10);ok(ids.every(id=>L.skills.get(id).track==='normal'));});
check('LEARNING','奧數每日練習不混普通數學','10 個奧數技能',()=>{let ids=C.planDaily(C.blank(),L,{track:'olympiad'});eq(ids.length,10);ok(ids.every(id=>L.skills.get(id).track==='olympiad'));});
check('LEARNING','香港午夜前一毫秒','2026-09-28',()=>eq(C.hkDay(Date.UTC(2026,8,28,15,59,59,999)),'2026-09-28'));
check('LEARNING','香港午夜跨日','2026-09-29',()=>eq(C.hkDay(Date.UTC(2026,8,28,16)),'2026-09-29'));
check('LEARNING','跨月日期增加','2026-10-01',()=>eq(C.plusDay('2026-09-30',1),'2026-10-01'));
check('LEARNING','閏年日期增加','2028-02-29',()=>eq(C.plusDay('2028-02-28',1),'2028-02-29'));
check('LEARNING','無效任務不加入獎勵','outbox 為空',()=>{let s=C.blank();eq(C.enqueueReward(s,{key:'a',startedAt:fixed,completedAt:fixed,valid:false}),null);eq(s.outbox.length,0);});
check('LEARNING','相同獎勵事件冪等','只加入一筆',()=>{let s=C.blank();for(let i=0;i<3;i++)C.enqueueReward(s,{key:'normal:a',startedAt:fixed,completedAt:fixed,valid:true});eq(s.outbox.length,1);});
for(let n=1;n<=5;n++)check('LEARNING','每日完成 '+n+' 個任務','金幣總額 '+[0,1,2,4,5,5][n],()=>{let s=C.blank();for(let i=0;i<n;i++)C.standaloneAward(s,{valid:true,key:'task'+i,day:'2026-09-28'});eq(s.wallet.balance,[0,1,2,4,5,5][n]);return s.wallet;});
check('LEARNING','同一任務重派不加錢','總額 1',()=>{let s=C.blank();let e={valid:true,key:'task',day:'2026-09-28'};C.standaloneAward(s,e);C.standaloneAward(s,e);eq(s.wallet.balance,1);});
check('LEARNING','新一天同技能可獎勵','兩天總額 2',()=>{let s=C.blank();for(const d of ['2026-09-28','2026-09-29'])C.standaloneAward(s,{valid:true,key:'task',day:d});eq(s.wallet.balance,2);});
check('LEARNING','錢包達最大值不溢出','不高於 1,000,000',()=>{let s=C.blank();s.wallet.balance=1000000;eq(C.standaloneAward(s,{valid:true,key:'a',day:'2026-09-28'}),0);eq(s.wallet.balance,1000000);});
check('LEARNING','200 筆已結算不應阻擋新獎勵','已結算事件可輪替／壓縮，新任務可完成',()=>{let s=C.blank();for(let i=0;i<200;i++){let e=C.enqueueReward(s,{key:'task'+i,startedAt:fixed,completedAt:fixed,valid:true});e.settled=true;}C.enqueueReward(s,{key:'next-task',startedAt:fixed,completedAt:fixed,valid:true});},'F-OUTBOX-CAPACITY');
// Test storage in an isolated VM. Mocks are not a claim that V33 integration was tested.
function env(){let m=new Map(),failSet=false;const st={getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>{if(failSet)throw Error('QuotaExceededError');m.set(k,String(v));},removeItem:k=>m.delete(k)};const x={WQMathCore:C,localStorage:st,crypto:{randomUUID:()=> 'abcd-'+Math.random().toString(36).slice(2)},Date,Math};vm.createContext(x);vm.runInContext(fs.readFileSync(ROOT+'/source/maths_script_2.js','utf8'),x);const S=x.WQMathStorage,b=S.standalone();return {x,m,st,S,b,fail:v=>failSet=v,newStore:()=>new S.Store(b,L)};}
const storeCases=[];function sc(n,e,f,issue=''){storeCases.push([n,e,f,issue]);}
sc('訪客不落盤','沒有 state localStorage',()=>{let e=env(),s=e.newStore();s.change(n=>n.serial++);eq(e.m.size,0);});
sc('新檔案初始化','持久化及孩子資料一致',()=>{let e=env(),c=e.b.add('測試',3,true),s=e.newStore();eq(s.profile.id,c.id);ok(s.profile.persistent);});
sc('變更後可重新讀取','serial=9',()=>{let e=env();e.b.add('測試',3,true);let s=e.newStore();s.change(n=>n.serial=9);eq(e.newStore().state.serial,9);});
sc('revision 隨寫入增加','revision=2',()=>{let e=env();e.b.add('測試',3,true);let s=e.newStore();s.change(n=>n.serial++);s.change(n=>n.serial++);eq(s.state.revision,2);});
sc('孩子 A/B 隔離','各自 serial=1/2',()=>{let e=env(),a=e.b.add('A',3,true),sa=e.newStore();sa.change(n=>n.serial=1);let b=e.b.add('B',2,true),sb=e.newStore();sb.change(n=>n.serial=2);e.b.switch(a.id);eq(e.newStore().state.serial,1);e.b.switch(b.id);eq(e.newStore().state.serial,2);});
sc('孩子切換後舊實例拒寫','throw',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore();e.b.add('B',3,true);assert.throws(()=>s.change(n=>n.serial++));});
sc('順序分頁衝突不覆蓋','第二個實例拒寫',()=>{let e=env();e.b.add('A',3,true);let a=e.newStore(),b=e.newStore();a.change(n=>n.serial=5);assert.throws(()=>b.change(n=>n.serial=9));eq(e.newStore().state.serial,5);});
sc('容量不足不改記憶體','原 serial 保留',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore();e.fail(true);assert.throws(()=>s.change(n=>n.serial=5));eq(s.state.serial,0);});
sc('無效交易不寫入','原資料保留',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore();assert.throws(()=>s.change(n=>n.wallet.balance=-1));eq(s.state.wallet.balance,0);});
sc('損壞 JSON 進入只讀','保留原始字串',()=>{let e=env();e.b.add('A',3,true);let k=e.newStore().key;e.st.setItem(k,'{broken');let s=e.newStore();ok(s.readOnly);eq(e.st.getItem(k),'{broken');});
sc('損壞 schema 進入只讀','不覆蓋',()=>{let e=env();e.b.add('A',3,true);let k=e.newStore().key;e.st.setItem(k,JSON.stringify({schema:9}));ok(e.newStore().readOnly);});
sc('只讀實例拒絕写入','原始字串不變',()=>{let e=env();e.b.add('A',3,true);let k=e.newStore().key;e.st.setItem(k,'!');let s=e.newStore();assert.throws(()=>s.change(n=>n.serial++));eq(e.st.getItem(k),'!');});
sc('匯出格式及 owner','正確欄位',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore(),v=s.export();eq(v.format,'wordquest-maths');eq(v.owner,s.scope);eq(v.version,1);});
sc('同一孩子匯入','serial 還原',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore();s.change(n=>n.serial=2);let v=clone(s.export());s.change(n=>n.serial=5);s.import(v);eq(s.state.serial,2);});
sc('另一孩子備份拒絕','throw',()=>{let e=env();e.b.add('A',3,true);let v=e.newStore().export();e.b.add('B',3,true);assert.throws(()=>e.newStore().import(v));});
sc('非數學備份拒絕','throw',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore(),v=s.export();v.format='english';assert.throws(()=>s.import(v));});
sc('錯誤備份版本拒絕','throw',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore(),v=s.export();v.version=2;assert.throws(()=>s.import(v));});
sc('匯入之前保留復原快照','before-restore 存在',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore();s.change(n=>n.serial=3);let v=clone(s.export());s.import(v);ok(e.st.getItem(s.key+':before-restore'));});
sc('匯入不重派獎勵','outbox 已 settled',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore(),v=clone(s.export());v.state=stateReward();s.import(v);ok(s.state.outbox.every(x=>x.settled));eq(s.flush(),0);});
sc('匯入清除執行中課堂','current=null',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore(),v=clone(s.export());v.state=stateCurrent();s.import(v);eq(s.state.current,null);});
sc('本機 flush 派發一次','重試不增加',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore();s.change(n=>C.enqueueReward(n,{key:'normal:a',startedAt:fixed,completedAt:fixed,valid:true}));eq(s.flush(),1);eq(s.flush(),0);eq(s.balance(),1);});
sc('訪客 flush 不派錢','0',()=>{let e=env(),s=e.newStore();eq(s.flush(),0);});
sc('五個本機任務每日上限','總額 5',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore();for(let i=0;i<5;i++)s.change(n=>C.enqueueReward(n,{key:'normal:a'+i,startedAt:fixed,completedAt:fixed,valid:true}));eq(s.flush(),5);eq(s.balance(),5);});
sc('重讀獎勵收據','不重派',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore();s.change(n=>C.enqueueReward(n,{key:'normal:a',startedAt:fixed,completedAt:fixed,valid:true}));s.flush();eq(e.newStore().flush(),0);});
sc('空暱稱拒絕','throw',()=>{let e=env();assert.throws(()=>e.b.add(' ',3,true));});
sc('過長暱稱拒絕','throw',()=>{let e=env();assert.throws(()=>e.b.add('a'.repeat(25),3,true));});
sc('沒有家長同意拒絕','throw',()=>{let e=env();assert.throws(()=>e.b.add('A',3,false));});
sc('年級 0 拒絕','throw',()=>{let e=env();assert.throws(()=>e.b.add('A',0,true));});
sc('年級 7 拒絕','throw',()=>{let e=env();assert.throws(()=>e.b.add('A',7,true));});
sc('第 21 學員拒絕','throw',()=>{let e=env();for(let i=0;i<20;i++)e.b.add('A'+i,3,true);assert.throws(()=>e.b.add('21',3,true));});
sc('切换不存在學員拒絕','throw',()=>{let e=env();assert.throws(()=>e.b.switch('missing'));});
sc('切換訪客','persistent=false',()=>{let e=env();e.b.add('A',3,true);e.b.guest();ok(!e.b.profile().persistent);});
sc('刪除學員主進度','原 key 不存在',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore();s.change(n=>n.serial=5);e.b.remove();eq(e.st.getItem(s.key),null);});
sc('刪除學員亦刪復原快照','主進度與 before-restore 均不存在',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore();s.change(n=>n.serial=5);s.import(clone(s.export()));e.b.remove();eq(e.st.getItem(s.key+':before-restore'),null);},'F-DELETE-BACKUP');
sc('損壞孩子名單可退回安全狀態','應可提供恢復介面／訪客，而非未處理例外',()=>{let e=env();e.st.setItem('wqm-profiles-v1','{broken');e.newStore();},'F-REGISTRY-BOOT');
sc('完整關閉 localStorage 可訪客試玩','訪客應可啟動',()=>{let e=env();e.st.getItem=()=>{throw Error('SecurityError')};e.newStore();},'F-REGISTRY-BOOT');
sc('normal=[] 不應靜默遺失掌握度','無效備份應拒絕；或寫入可保留掌握度',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore();let raw=C.blank();raw.mastery.normal=[];e.st.setItem(s.key,JSON.stringify(raw));s=e.newStore();if(s.readOnly)return '安全拒絕';s.change(n=>C.record(n,L,q0,correct(q0),{id:'a',at:fixed}));ok(e.newStore().state.mastery.normal[q0.skill],'答案有保存但掌握度在重讀後遺失');},'F-ARRAY-STATE');
sc('usage=[] 不應漏記時限','無效備份拒絕或保留時間',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore();let raw=C.blank();raw.usage=[];e.st.setItem(s.key,JSON.stringify(raw));s=e.newStore();if(s.readOnly)return '安全拒絕';s.change(n=>n.usage['2026-09-28']=60000);eq(e.newStore().state.usage['2026-09-28'],60000);},'F-ARRAY-STATE');
sc('沒有英文橋接介面','返回 null 而不是改動未知帳戶',()=>{let e=env();eq(e.S.createHostBridge(),null);});
sc('已結算收據累積 200 筆後可繼續','新任務獎勵可寫入',()=>{let e=env();e.b.add('A',3,true);let s=e.newStore();s.change(n=>{for(let i=0;i<200;i++){const ev=C.enqueueReward(n,{key:'t'+i,startedAt:fixed,completedAt:fixed,valid:true});ev.settled=true;}});s.change(n=>C.enqueueReward(n,{key:'next',startedAt:fixed,completedAt:fixed,valid:true}));},'F-OUTBOX-CAPACITY');
console.log('STORAGE planned',storeCases.length);
for(const [n,e,f,i] of storeCases)check('STORAGE',n,e,f,i);
fs.writeFileSync(ROOT+'/results/core_results.json',JSON.stringify(results,null,2));
const counts={};for(const r of results){counts[r.category]??={PASS:0,FAIL:0};counts[r.category][r.status]++;}
console.log(JSON.stringify(counts,null,2));console.log('TOTAL',results.length,'fail',results.filter(r=>r.status==='FAIL').length);
