/* R3 family data contracts. Local backups are unencrypted; checksums detect damage, not authorship. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.WQFamilyCore=api;})(globalThis,function(){'use strict';
 const VERSION=1, DAY=86400000, BAD=new Set(['__proto__','constructor','prototype']);
 const assert=(v,m)=>{if(!v)throw Error(m);};const clone=x=>JSON.parse(JSON.stringify(x));
 const plain=x=>!!x&&typeof x==='object'&&!Array.isArray(x);
 const id=x=>typeof x==='string'&&/^[A-Za-z0-9_.:-]{1,100}$/.test(x)&&!BAD.has(x);
 function scan(x,depth=0,budget={n:0}){assert(depth<35&&++budget.n<1000000,'備份資料過大或層數過多');if(x&&typeof x==='object')for(const k of Object.keys(x)){assert(!BAD.has(k),'備份含不安全欄位');scan(x[k],depth+1,budget);}else if(typeof x==='number')assert(Number.isFinite(x),'資料含無效數值');}
 function day(now=Date.now()){return new Date(now+28800000).toISOString().slice(0,10);}
 function validDay(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s+'T00:00:00Z'))&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s;}
 function defaults(){return {schema:1,revision:0,limitMinutes:45,englishMinutes:10,mathMinutes:10,olympiadMinutes:0,usage:{},migrationReceipts:[],voice:{mode:'device',endpoint:'',voice:'zh-HK-HiuMaanNeural',consent:false},createdAt:Date.now()};}
 function validateSettings(v){scan(v);assert(plain(v)&&v.schema===1,'跨科設定版本不支援');const out=clone(v);for(const [k,a,b]of [['revision',0,1e9],['limitMinutes',5,180],['englishMinutes',0,60],['mathMinutes',0,60],['olympiadMinutes',0,60]])assert(Number.isInteger(out[k])&&out[k]>=a&&out[k]<=b,'跨科時限或學習配額不正確');assert(out.englishMinutes+out.mathMinutes+out.olympiadMinutes<=out.limitMinutes,'三科建議時間合計不能超過全站時限');assert(plain(out.usage),'使用時間格式無效');assert(Object.keys(out.usage).length<=50,'學員數過多');for(const [cid,days]of Object.entries(out.usage)){assert(id(cid)&&plain(days),'使用時間學員無效');assert(Object.keys(days).length<=400,'使用時間超過400天');for(const [d,row]of Object.entries(days)){assert(validDay(d)&&plain(row),'使用日期無效');assert(Object.keys(row).length===4,'使用紀錄含未知欄位');let total=0;for(const k of ['english','math','olympiad','arcade']){assert(Number.isInteger(row[k])&&row[k]>=0&&row[k]<=DAY,'使用時間超出範圍');total+=row[k];}assert(total<=DAY,'每日總時間超過24小時');}}
  assert(Array.isArray(out.migrationReceipts)&&out.migrationReceipts.length<=300,'搬移收據過多');for(const r of out.migrationReceipts)assert(plain(r)&&typeof r.digest==='string'&&/^[a-f0-9]{64}$/.test(r.digest)&&id(r.target)&&Number.isFinite(r.at),'搬移收據無效');
  assert(plain(out.voice)&&['device','server'].includes(out.voice.mode)&&typeof out.voice.consent==='boolean','聲線設定無效');assert(typeof out.voice.endpoint==='string'&&out.voice.endpoint.length<=240&&(!out.voice.endpoint||/^\/api\/[A-Za-z0-9_/-]+$/.test(out.voice.endpoint)),'語音服務只能使用同網站的 /api/ 路徑');assert(typeof out.voice.voice==='string'&&/^[A-Za-z0-9-]{1,64}$/.test(out.voice.voice),'聲線名稱無效');return out;
 }
 function usageTotal(settings,cid,d=day()){const r=settings.usage[cid]?.[d];return r?['english','math','olympiad','arcade'].reduce((a,b)=>a+r[b],0):0;}
 function addUsage(settings,cid,subject,ms,now=Date.now()){assert(id(cid)&&['english','math','olympiad','arcade'].includes(subject),'計時身份無效');assert(Number.isFinite(ms)&&ms>=0,'計時無效');ms=Math.min(5000,Math.floor(ms));const d=day(now);const days=settings.usage[cid]||(settings.usage[cid]={});const r=days[d]||(days[d]={english:0,math:0,olympiad:0,arcade:0});const remaining=Math.max(0,DAY-Object.values(r).reduce((a,b)=>a+b,0));r[subject]+=Math.min(ms,remaining);for(const old of Object.keys(days).sort().slice(0,-365))delete days[old];return usageTotal(settings,cid,d);}
 function portableMath(v,core,lib){assert(v?.format==='wordquest-maths'&&v.version===1,'不是支援的數學備份');scan(v);assert(typeof v.owner==='string'&&v.owner.length<=210&&plain(v.profile)&&id(v.profile.id),'舊學員身份格式不正確');assert(typeof v.profile.name==='string'&&v.profile.name.length<=40&&Number.isInteger(v.profile.grade)&&v.profile.grade>=1&&v.profile.grade<=6,'舊學員姓名或年級無效');const state=core.validateState(v.state,lib);return {format:v.format,version:1,owner:v.owner,profile:clone(v.profile),state};}
 function migrateMath(v,target,core,lib){const input=portableMath(v,core,lib);assert(id(target.id)&&typeof target.account==='string','目標孩子無效');const state=clone(input.state);state.outbox.forEach(e=>{e.settled=true;e.award=0;});state.wallet={balance:0,days:{}};state.current=null;return {format:'wordquest-maths',version:1,owner:target.account+':'+target.id,profile:{id:target.id,name:target.name,grade:target.grade},state:core.validateState(state,lib)};}
 function envelope(v){scan(v);assert(plain(v)&&v.format==='wordquest-family'&&v.version===VERSION,'不是R3家庭完整備份');assert(typeof v.createdAt==='string'&&validDay(v.createdAt.slice(0,10))&&Number.isFinite(Date.parse(v.createdAt)),'備份日期無效');assert(plain(v.payload)&&plain(v.payload.english)&&Array.isArray(v.payload.math)&&Array.isArray(v.payload.media),'完整備份缺少資料');assert(v.payload.math.length<=50&&v.payload.media.length<=5000,'備份項目過多');assert(plain(v.integrity)&&v.integrity.algorithm==='SHA-256'&&/^[a-f0-9]{64}$/.test(v.integrity.digest),'備份校驗碼無效');return v;}
 function validatePayload(p,englishValidator,core,lib){scan(p);assert(p.sourceOwner===undefined||id(p.sourceOwner),'備份來源身份無效');const english=englishValidator(p.english),seen=new Set();const children=new Set(english.children.map(c=>c.id));const math=p.math.map(row=>{assert(plain(row)&&children.has(row.childId)&&!seen.has(row.childId),'數學資料重複或不屬於備份孩子');seen.add(row.childId);const state=row.state===null?null:core.validateState(row.state,lib);if(state)state.outbox.forEach(e=>e.settled=true);const recovery=row.recovery===null?null:core.validateState(row.recovery,lib);if(recovery)recovery.outbox.forEach(e=>e.settled=true);return {childId:row.childId,state,recovery};});assert(math.length===english.children.length,'備份缺少孩子的數學欄位');const characterPreferences=clone(p.characterPreferences||[]);assert(Array.isArray(characterPreferences)&&characterPreferences.length<=100,'角色設定過多');const ps=new Set();for(const row of characterPreferences){assert(plain(row)&&children.has(row.childId)&&['normal','sandbox'].includes(row.mode)&&!ps.has(row.mode+':'+row.childId),'角色設定身份不正確');ps.add(row.mode+':'+row.childId);assert(plain(row.preferences)&&['show','motion','compact'].every(k=>typeof row.preferences[k]==='boolean')&&['rabbit','panda'].includes(row.preferences.gameBuddy)&&(row.preferences.guide===undefined||row.preferences.guide==='auto'||['owl','fox','star','bee','rabbit','panda'].includes(row.preferences.guide)),'角色偏好無效');}const family=validateSettings(p.family);for(const cid of Object.keys(family.usage))assert(children.has(cid),'跨科資料含其他孩子');const keys=new Set();let total=0;const media=p.media.map(row=>{assert(plain(row)&&typeof row.key==='string'&&row.key.length>0&&row.key.length<500&&!keys.has(row.key),'媒體識別碼無效或重複');keys.add(row.key);assert(['audio','image','note'].includes(row.kind),'媒體類別無效');assert(plain(row.meta),'媒體附加資料無效');if(row.kind==='note'){assert(!row.data,'文字備註不可含二進制');return clone(row);}assert(typeof row.mime==='string'&&(/^(image\/(png|jpeg|webp|gif)|audio\/(wav|x-wav|ogg|mpeg|mp4|webm))$/).test(row.mime),'不支援的媒體格式');assert(typeof row.data==='string'&&/^data:[^;,]+;base64,[A-Za-z0-9+/]*={0,2}$/.test(row.data)&&row.data.startsWith('data:'+row.mime+';base64,'),'媒體內容格式無效');assert(row.mime.startsWith(row.kind+'/'),'媒體類別與格式不一致');assert(row.data.split(',')[1].length%4===0,'媒體Base64長度無效');total+=row.data.length;assert(row.data.length<=30000000&&total<=110000000,'媒體備份過大');return clone(row);});return {sourceOwner:p.sourceOwner,english,math,family,media,characterPreferences};}
 function weekly(english,math,cid,now=Date.now()){const start=Date.parse(day(now)+'T00:00:00+08:00')-6*DAY,end=now;const words=new Set(english.words.filter(w=>w.childId===cid).map(w=>w.id));const eng=english.attempts.filter(a=>words.has(a.wordId)&&Date.parse(a.time)>=start&&Date.parse(a.time)<=end&&!a.technical&&a.correct!==null);const rows={english:{attempts:eng.length,correct:eng.filter(a=>a.correct===true).length,assisted:eng.filter(a=>a.assisted).length},normal:{attempts:0,correct:0,assisted:0},olympiad:{attempts:0,correct:0,assisted:0}};for(const a of math?.attempts||[])if(a.at>=start&&a.at<=end){const r=rows[a.track];r.attempts++;if(a.correct)r.correct++;if(a.hint>0)r.assisted++;}return {from:day(start),to:day(now),rows,mathWeak:Object.entries(math?.mastery?.normal||{}).filter(([,v])=>v.last&&v.score<80).sort((a,b)=>a[1].score-b[1].score).slice(0,5).map(([skill,m])=>({skill,score:m.score})),scope:'最近七天的實際紀錄；未記錄時段不補估'};}
 return Object.freeze({VERSION,clone,id,scan,day,validDay,defaults,validateSettings,usageTotal,addUsage,portableMath,migrateMath,envelope,validatePayload,weekly});
});
