
'use strict';
class CloudRun extends WQGame{
 constructor(a){super(a);this.lane=0;this.rotation=0;this.distance=0;this.jump=0;this.tiles=Array.from({length:18},(_,i)=>this.make(i*.9,i<4));this.tools([]);this.hint('← → 換跑道；空白鍵／跳躍掠過缺口。');}
 make(z,safe=false){const holes=Array.from({length:6},()=>!safe&&this.r()<[.16,.25,.34][this.d]);holes[Math.floor(this.r()*6)]=false;return{z,holes,star:Math.floor(this.r()*6),col:Math.floor(this.r()*3)};}
 act(k){if(k==='left')this.lane=(this.lane+5)%6;if(k==='right')this.lane=(this.lane+1)%6;if(k==='action'&&this.jump<=0){this.jump=.68;this.sound(380,.08);}}
 update(dt){const speed=[1.45,1.85,2.25][this.d];this.distance+=dt*speed;this.jump=Math.max(0,this.jump-dt);let dest=-this.lane*Math.PI/3,diff=(dest-this.rotation+Math.PI*3)%(Math.PI*2)-Math.PI;this.rotation+=diff*Math.min(1,dt*12);this.score=Math.floor(this.distance*20);this.stat=`前進 ${Math.floor(this.distance*6)} 米`;for(const s of this.tiles)s.z-=dt*speed;while(this.tiles[0].z<0){const s=this.tiles.shift();if(s.holes[this.lane]&&this.jump===0){this.end(`今次跑了 ${Math.floor(this.distance*6)} 米。換到完整跑道，或提前跳過缺口。`,'跑道中斷了');return;}if(!s.holes[this.lane]&&s.star===this.lane)this.sound(800,.04);this.tiles.push(this.make(this.tiles[this.tiles.length-1].z+.9));}}
 draw(){const c=this.c;D.bg(c,'night');for(let i=0;i<45;i++){const x=(i*177+13)%800,y=(i*53)%500;D.circle(c,x,y,1+(i%3===0), '#e2e5c54d');}const p=(z,k)=>{const rr=360/(1+z*.48),a=Math.PI/3*(k-.5)+Math.PI/2+this.rotation;return{x:400+Math.cos(a)*rr,y:235+Math.sin(a)*rr};};for(const s of [...this.tiles].reverse())for(let k=0;k<6;k++){if(s.holes[k])continue;D.poly(c,[p(s.z,k),p(s.z,k+1),p(s.z+.82,k+1),p(s.z+.82,k)],s.col===0?'#577b79':s.col===1?'#648a82':'#769488','#bdd6ad50',1);if(k===s.star){const q1=p(s.z+.4,k),q2=p(s.z+.4,k+1);D.star(c,(q1.x+q2.x)/2,(q1.y+q2.y)/2,Math.max(3,12/(1+s.z*.3)),'#f0d084');}}D.circle(c,400,235,15,'#b8d0b2');let jy=this.jump>0?Math.sin((.68-this.jump)/.68*Math.PI)*88:0;D.ellipse(c,400,494,35,8,'#0d252a55');D.animal(c,400,443-jy,.86,'rabbit','#d8a85a');D.badge(c,'雲端探索 · 左右跑道皆可行',400,37,'#e9eddccc');this.noticeDraw();}
}
registerGame({id:'cloud-run',name:'雲端跑道',en:'CLOUD RUN',category:'動作',desc:'轉換六面跑道，跳過星空缺口。',tag:'空間跑酷',guide:'角色會自動前進。用左右鍵切換隧道的六面跑道，遇到空格就跳過。跳躍不能連按；先看遠一點的路。',design:'原創六面隧道跑酷；三種速度與缺口密度。',keys:[['left','←'],['right','→'],['action','跳躍']]},CloudRun);

class ValleyRace extends WQGame{
 constructor(a){super(a);this.path=[];this.edit=false;this.ghost=[];this.ghostBest=Infinity;this.samples=[];this.lap=0;this.nextGate=1;this.lapTime=0;this.buildTrack();this.startCar();this.toolbar();this.hint('自動加速；← → 轉向，↓ 煞車。順序經過 4 個路標才算一圈。');}
 toolbar(){this.tools([{id:'track',label:this.edit?'完成自製賽道':'自製賽道'},{id:'default',label:'恢復原賽道'}]);}
 buildTrack(){this.path=Array.from({length:100},(_,i)=>{const t=i/100*Math.PI*2,scale=1+.11*this.d*Math.sin(t*3);return{x:400+285*Math.cos(t)*scale,y:282+178*Math.sin(t)};});}
 startCar(){const p=this.path[0],q=this.path[1];this.car={x:p.x,y:p.y,a:Math.atan2(q.y-p.y,q.x-p.x),v:0};this.nextGate=1;this.lapTime=0;this.samples=[];this.sampleInterval=.10;}
 tool(k){if(k==='track'){if(!this.edit){this.edit=true;this.editPoints=[];this.say('在畫面點至少 5 個路點，然後按完成。');}else{if(!WQCore.validTrack(this.editPoints)){this.say('請放至少 5 個不同路點；相鄰路點相隔 25 像素，圍出有面積的賽道。');return;}this.path=this.editPoints.slice();this.lap=0;this.score=0;this.edit=false;this.ghost=[];this.ghostBest=Infinity;this.startCar();}this.toolbar();}if(k==='default'){this.edit=false;this.ghost=[];this.ghostBest=Infinity;this.lap=0;this.score=0;this.buildTrack();this.startCar();this.toolbar();}}
 pointer(type,p){if(type==='down'&&this.edit&&this.editPoints.length<18){this.editPoints.push({x:WQCore.clamp(p.x,60,740),y:WQCore.clamp(p.y,90,480)});}}
 update(dt){if(this.edit){this.stat='賽道編輯';return;}this.lapTime+=dt;const a=this.car,brake=this.keys.has('down'),steer=(this.keys.has('right')?1:0)-(this.keys.has('left')?1:0);let near={d:Infinity,t:0,i:0};for(let i=0;i<this.path.length;i++){const n=WQCore.nearest(a,this.path[i],this.path[(i+1)%this.path.length]);if(n.d<near.d)near={...n,i};}const roadWidth=[43,37,32][this.d],target=brake?30:near.d>roadWidth?52:[165,195,225][this.d];a.v+=(target-a.v)*Math.min(1,dt*1.8);a.a+=steer*dt*(.7+a.v/95);a.x=WQCore.clamp(a.x+Math.cos(a.a)*a.v*dt,18,782);a.y=WQCore.clamp(a.y+Math.sin(a.a)*a.v*dt,65,525);if(!this.samples.length||this.lapTime-this.samples.at(-1).t >= (this.sampleInterval||.10)){
 this.samples.push({x:Math.round(a.x*10)/10,y:Math.round(a.y*10)/10,a:Math.round(a.a*1000)/1000,t:Math.round(this.lapTime*1000)/1000});
 if(this.samples.length>1200){this.samples=this.samples.filter((_,i)=>i%2===0);this.sampleInterval=(this.sampleInterval||.10)*2;}
 }const progress=(near.i+near.t)/this.path.length,gate=this.nextGate%4/4;const pd=Math.min(Math.abs(progress-gate),1-Math.abs(progress-gate));if(pd<.035&&near.d<roadWidth+10){this.nextGate++;this.sound(420+this.nextGate*70,.07);if(this.nextGate===5){this.lap++;const lapScore=Math.max(10,Math.round(3000-this.lapTime*70));this.score+=lapScore;if(this.lapTime<this.ghostBest){this.ghostBest=this.lapTime;this.ghost=this.samples.slice();}this.say(`完成第 ${this.lap} 圈 · ${this.lapTime.toFixed(2)} 秒`);this.lapTime=0;this.samples=[];this.sampleInterval=.10;this.nextGate=1;}}this.stat=`第 ${this.lap+1} 圈 · ${this.lapTime.toFixed(1)} 秒`;}
 draw(){const c=this.c;D.bg(c);D.hills(c,490);if(this.edit){D.badge(c,'點出你的賽道，至少 5 個路點');D.line(c,this.editPoints,'#c1c5a9',64);this.editPoints.forEach((p,i)=>{D.circle(c,p.x,p.y,13,'#477c64');D.text(c,i+1,p.x,p.y,14,'white');});return;}const closed=this.path.concat(this.path[0]);D.line(c,closed,'#a1b783',100);D.line(c,closed,'#f6eed7',88-this.d*9);D.line(c,closed,'#c7be9c',2,[12,12]);for(let i=0;i<4;i++){const p=this.path[Math.floor(i*this.path.length/4)];D.circle(c,p.x,p.y,16,(this.nextGate%4===i)?'#dbad59':'#faf6e5');D.text(c,i===0?'起':i,p.x,p.y,13,'#526f50');}if(this.ghost.length){const p=this.ghost.find(p=>p.t>=this.lapTime);if(p){c.globalAlpha=.28;D.car(c,p.x,p.y,p.a,.65,'#609487');c.globalAlpha=1;}}D.car(c,this.car.x,this.car.y,this.car.a,.65);D.animal(c,398,267,.62,'fox');D.badge(c,'風谷計時賽',400,36);D.text(c,'順時針經過 1 → 2 → 3 → 起點',400,340,14,'#658158');this.noticeDraw();}
}
registerGame({id:'valley-race',name:'風谷賽道',en:'VALLEY RACE',category:'動作',desc:'跑出一條靚路線，挑戰上一圈。',tag:'計時賽車',guide:'車會自動加速，左右鍵轉向，下鍵煞車。留在米色道路內，順時針經過四個路標。三圈完成一局。圈速只用作紀錄，不是倒數；手機用轉向及煞車按鈕。',design:'俯視 2D 賽車，包含路面減速、圈數檢查、影子車及路點編輯器；不是原作的 3D 翻圈賽車。',keys:[['left','←'],['right','→'],['down','煞車']]},ValleyRace);

class DriftPath extends WQGame{
 constructor(a){super(a);this.pos={x:0,y:0};this.dir=0;this.camera={x:0,y:0};this.nodes=[{x:-150,y:0},{x:145,y:0}];for(let i=0;i<22;i++){const p=this.nodes[this.nodes.length-1],len=120+this.r()*120;this.nodes.push({x:p.x+(i%2?len:0),y:p.y+(i%2?0:-len)});}this.trail=[];this.travel=0;this.tools([]);this.hint('按一次「轉彎」就改方向；在每個轉角中心再按。');}
 act(k){if(k==='action'){this.dir=1-this.dir;this.sound(330+this.dir*80,.04);}}
 update(dt){const speed=[83,108,132][this.d];this.pos.x+=this.dir===0?speed*dt:0;this.pos.y-=this.dir===1?speed*dt:0;this.travel+=speed*dt;this.camera.x+=(this.pos.x-this.camera.x)*dt*4;this.camera.y+=(this.pos.y-this.camera.y)*dt*4;this.trail.push({...this.pos});if(this.trail.length>28)this.trail.shift();const d=Math.min(...this.nodes.slice(0,-1).map((p,i)=>WQCore.nearest(this.pos,p,this.nodes[i+1]).d));if(d>[39,34,30][this.d]){this.end(`完成 ${Math.floor(this.travel/10)} 米。到轉角中心才切換方向會更穩。`,'偏離小徑了');return;}this.score=Math.floor(this.travel);this.stat=`${Math.floor(this.travel/10)} 米`;if(WQCore.distance(this.pos,this.nodes[this.nodes.length-1])<50)this.end('你完成了整條漂移小徑！','路線完成');}
 draw(){const c=this.c;D.bg(c,'blue');D.cloud(c,100,110,1.5);D.cloud(c,690,70,.9);const tr=p=>({x:310+((p.x-this.camera.x)-(p.y-this.camera.y))*.7,y:365+((p.x-this.camera.x)+(p.y-this.camera.y))*.37});const pts=this.nodes.map(tr);D.line(c,pts.map(p=>({x:p.x,y:p.y+12})),'#789b94',63);D.line(c,pts,'#f5ead1',63);D.line(c,pts,'#cbbf97',2,[8,13]);this.nodes.forEach((p,i)=>{if(i>0&&i<this.nodes.length-1){const v=tr(p);D.circle(c,v.x,v.y,5,'#d7a75c');}});D.line(c,this.trail.map(tr),'#d5997544',11);const p=tr(this.pos);D.car(c,p.x,p.y,this.dir?-Math.atan(.37/.7):Math.atan(.37/.7),.65,'#d9896c');D.badge(c,'一下轉彎，一路前進');}
}
registerGame({id:'drift-path',name:'漂移小徑',en:'DRIFT PATH',category:'動作',desc:'一個按鈕，掌握每個轉角時機。',tag:'一鍵轉向',guide:'小車只沿兩個方向前進。按一次就轉向，再按一次就轉回。在轉角的中央切換方向，保持在米色小徑之內。',design:'等角投影道路、持續前進及精確路面判斷；不設撞車攻擊。',keys:[['action','轉彎']]},DriftPath);

class MoonBells extends WQGame{
 constructor(a){super(a);this.p={x:400,y:440,vy:-470};this.camera=0;this.maxH=0;this.bells=[{x:400,y:495,id:0}];for(let i=1;i<75;i++){const last=this.bells[i-1];this.bells.push({x:WQCore.clamp(last.x+(this.r()-.5)*(260+this.d*40),100,700),y:495-i*(75+this.d*10),id:i});}this.target=null;this.tools([]);this.hint('拖動手指／滑鼠，或按 ← →，引導兔仔落到下一個鈴鐺。');}
 pointer(type,p){if(type==='move'||type==='down')this.target=p.x;}
 update(dt){const p=this.p;const old=p.y;let dx=(this.keys.has('right')?1:0)-(this.keys.has('left')?1:0);if(dx){p.x+=dx*380*dt;this.target=null;}else if(this.target!==null)p.x+=WQCore.clamp(this.target-p.x,-430*dt,430*dt);p.x=WQCore.clamp(p.x,30,770);p.vy+=760*dt;p.y+=p.vy*dt;if(p.vy>0)for(const b of this.bells){if(old+27<=b.y&&p.y+27>=b.y&&Math.abs(p.x-b.x)<[54,46,38][this.d]){p.y=b.y-27;p.vy=-470;if(!b.used){b.used=true;this.score+=20;this.sound(600+(b.id%8)*60,.14);}break;}}this.maxH=Math.max(this.maxH,440-p.y);this.camera=Math.min(this.camera,p.y-225);this.stat=`高度 ${Math.floor(this.maxH/10)} 米`;if(p.y-this.camera>660)this.end(`跳到 ${Math.floor(this.maxH/10)} 米。看準下一個鈴鐺，慢慢移過去。`,'今次跳到這裏');}
 draw(){const c=this.c;D.bg(c,'night');D.circle(c,650,88,39,'#f4deb1');D.circle(c,635,76,39,'#2a474e');for(let i=0;i<55;i++)D.star(c,(i*137+17)%800,((i*73-this.camera*.15)%580+580)%580,2+(i%2),'#e4e8cf66');for(const b of this.bells){const y=b.y-this.camera;if(y<-40||y>590)continue;D.ellipse(c,b.x,y+8,31,7,'#0b262844');D.round(c,b.x-20,y-14,40,28,12,b.used?'#a9bca7':'#eed18c');D.circle(c,b.x,y-16,7,b.used?'#a9bca7':'#f6d98e');D.line(c,[{x:b.x-22,y:y+11},{x:b.x+22,y:y+11}],'#f4e6b7',3);D.circle(c,b.x,y+15,4,'#bb9864');}D.animal(c,this.p.x,this.p.y-this.camera,.66,'rabbit','#92bda3');D.badge(c,'跟着鈴聲，跳近月亮',400,34,'#f3eedccc');}
}
registerGame({id:'moon-bells',name:'月光跳鈴',en:'MOON BELLS',category:'動作',desc:'引導兔仔，踏着鈴鐺向上跳。',tag:'垂直跳躍',guide:'兔仔會自動跳起。用左右方向鍵或 A、D 移動，手機用下方方向按鈕。讓兔仔下降時踏到鈴鐺，就會再次彈起。',design:'連續跳躍、上捲鏡頭、程序路線與合成鈴聲；不含傷害動畫。',keys:[['left','←'],['right','→']]},MoonBells);

class ForestPong extends WQGame{
 constructor(a){super(a);this.px=400;this.ax=400;this.hits=0;this.us=0;this.ai=0;this.serve(1);this.tools([]);this.hint('左右拖動球拍；擊球位置會改變回球角度。先得 5 分取勝。');}
 serve(dir){this.ball={x:400,y:280,vx:90*(this.r()>.5?1:-1),vy:dir*[240,300,360][this.d]};this.wait=.8;}
 pointer(type,p){if(type==='move'||type==='down')this.px=WQCore.clamp(p.x,152,648);}
 update(dt){this.px=WQCore.clamp(this.px+((this.keys.has('right')?1:0)-(this.keys.has('left')?1:0))*430*dt,152,648);if(this.wait>0){this.wait-=dt;return;}const b=this.ball,oldy=b.y;b.x+=b.vx*dt;b.y+=b.vy*dt;this.ax+=WQCore.clamp(b.x-this.ax,-[150,235,335][this.d]*dt,[150,235,335][this.d]*dt);this.ax=WQCore.clamp(this.ax,145,655);if(b.x<108){b.x=108;b.vx=Math.abs(b.vx);}if(b.x>692){b.x=692;b.vx=-Math.abs(b.vx);}if(b.vy>0&&oldy<=473&&b.y>=473&&Math.abs(b.x-this.px)<[77,65,55][this.d]){const offset=(b.x-this.px)/[77,65,55][this.d];const speed=Math.min(600,Math.hypot(b.vx,b.vy)*1.04);b.y=472;b.vx=offset*speed*.82;b.vy=-Math.sqrt(speed*speed-b.vx*b.vx);this.hits++;this.score+=10;this.sound(520,.05);}if(b.vy<0&&oldy>=87&&b.y<=87&&Math.abs(b.x-this.ax)<61){const speed=Math.min(590,Math.hypot(b.vx,b.vy)*1.03),off=(b.x-this.ax)/65;b.y=88;b.vx=off*speed*.78;b.vy=Math.sqrt(speed*speed-b.vx*b.vx);this.sound(370,.04);}if(b.y>555){this.ai++;this.serve(-1);}if(b.y<5){this.us++;this.score+=100;this.serve(1);}this.stat=`你 ${this.us} : ${this.ai} 森林隊`;if(this.us>=5||this.ai>=5)this.end(`你 ${this.us} : ${this.ai} 森林隊 · 共回球 ${this.hits} 次。`,this.us>=5?'這場贏了！':'友誼賽完成');}
 draw(){const c=this.c;D.bg(c);D.round(c,81,34,638,492,30,'#a8bd92');D.round(c,100,48,600,466,18,'#467b6a');D.round(c,116,64,568,432,8,null,'#dcebc7');D.line(c,[{x:400,y:66},{x:400,y:494}],'#dcebc777',2);D.line(c,[{x:105,y:280},{x:695,y:280}],'#e8edcd',4,[8,7]);D.round(c,this.ax-52,69,104,17,8,'#e7b06f');D.round(c,this.px-[65,53,43][this.d],475,[130,106,86][this.d],18,9,'#e6ebbc');D.ellipse(c,this.ball.x+5,this.ball.y+8,10,5,'#183a3044');D.circle(c,this.ball.x,this.ball.y,9,'#fff6da');D.text(c,'森林隊',51,85,12,'#58714d');D.text(c,'你',51,484,14,'#456c53');D.text(c,`${this.us} : ${this.ai}`,400,242,44,'#e2e6c440',700);if(this.wait>0)D.badge(c,'準備開球',400,328);}
}
registerGame({id:'forest-pong',name:'森林乒乓',en:'FOREST PONG',category:'運動',desc:'控制落點，與森林隊來回對打。',tag:'反應球賽',guide:'用左右鍵或 A、D 控制下方球拍，手機用左右按鈕。球碰到球拍邊緣會斜飛。先取得 5 分獲勝，失 3 分則結束這局。',design:'有角度的回球物理、分級電腦對手與完整一場計分。',keys:[['left','←'],['right','→']]},ForestPong);

class BounceBasket extends WQGame{
 constructor(a){super(a);this.two=false;this.player=0;this.turnScores=[0,0];this.shots=0;this.hoop={x:590,y:225};this.drag=null;this.charging=false;this.charge=0;this.resetBall();this.toolbar();this.hint('按住 Space 或「蓄力投籃」，放開出手。系統取消觸控時不會自動投球。');}
 toolbar(){this.tools([{id:'mode',label:this.two?'雙人輪流：開':'單人練習'},{id:'ball',label:'收回籃球'}]);}
 resetBall(){this.ball={x:170,y:397,vx:0,vy:0};this.flying=false;this.flight=0;this.scored=false;this.charge=0;}
 tool(k){if(k==='mode'){this.two=!this.two;this.player=0;this.shots=0;this.turnScores=[0,0];this.score=0;this.resetBall();this.toolbar();}if(k==='ball'&&this.flying)this.finishShot();}
 key(k,on){if(k==='action'){if(on&&!this.flying){this.charging=true;this.charge=0;}if(!on&&this.charging){this.charging=false;const v=350+this.charge*290;this.launch(v*.82,-v*.86);}}else super.key(k,on);}
 pointer(type,p){if(type==='down'&&!this.flying&&Math.hypot(p.x-this.ball.x,p.y-this.ball.y)<95){this.drag=p;this.pull=p;}if(type==='move'&&this.drag)this.pull=p;if((type==='up'||type==='cancel')&&this.drag){if(type==='up'){const dx=this.drag.x-p.x,dy=this.drag.y-p.y;this.launch(WQCore.clamp(dx*4,-550,650),WQCore.clamp(dy*4,-780,450));}this.drag=null;}}
 launch(vx,vy){if(this.flying)return;this.ball.vx=vx;this.ball.vy=vy;this.flying=true;this.sound(280,.04);}
 finishShot(){this.shots++;this.player=this.two?1-this.player:0;this.resetBall();if(this.shots>=(this.two?10:7))this.end(this.two?`甲方 ${this.turnScores[0]} 分，乙方 ${this.turnScores[1]} 分。`:`7 球共取得 ${this.score} 分。`,'投籃練習完成');}
 update(dt){if(this.charging)this.charge=Math.min(1,this.charge+dt*.75);this.hoop.x=590+(this.d===2?Math.sin(this.t*.6)*50:0);this.hoop.y=225+(this.d===1?Math.sin(this.t*.5)*25:0);if(this.flying){const b=this.ball,oldy=b.y;b.vy+=570*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;this.flight+=dt;if(b.vy>0&&oldy<this.hoop.y&&b.y>=this.hoop.y&&Math.abs(b.x-this.hoop.x)<[39,33,28][this.d]&&!this.scored){this.scored=true;this.score+=3;this.turnScores[this.player]+=3;this.sound(850,.15);this.say('入球！+3 分');}for(const sx of [this.hoop.x-45,this.hoop.x+45]){const n=WQCore.nearest(b,{x:sx,y:this.hoop.y-2},{x:sx,y:this.hoop.y+2});if(n.d<12){const nx=(b.x-n.x)/(n.d||1),ny=(b.y-n.y)/(n.d||1),dot=b.vx*nx+b.vy*ny;if(dot<0){b.vx-=1.6*dot*nx;b.vy-=1.6*dot*ny;}}}if(b.x>662&&b.x<680&&b.y>145&&b.y<254&&b.vx>0){b.x=661;b.vx*=-.7;}if(b.y>475){b.y=475;b.vy=-Math.abs(b.vy)*.52;b.vx*=.73;}if(this.flight>5||(this.flight>1.3&&Math.abs(b.vx)<18&&Math.abs(b.vy)<35)||b.x<-40||b.x>850)this.finishShot();}this.stat=this.two?`${this.player?'乙方':'甲方'}投籃 · ${this.shots+1}/10`:`第 ${Math.min(7,this.shots+1)} / 7 球`;}
 draw(){const c=this.c;D.bg(c,'cream');D.hills(c,520);D.round(c,68,462,664,48,13,'#cba874');D.line(c,[{x:70,y:484},{x:733,y:484}],'#eee0b7',2);D.round(c,663,131,10,351,3,'#8a9f83');D.round(c,632,145,43,112,6,'#f9f3df','#849e83');D.round(c,638,181,27,50,3,null,'#c4a170');D.line(c,[{x:this.hoop.x+45,y:this.hoop.y},{x:660,y:this.hoop.y}],'#db9271',5);const left=this.hoop.x-45,right=this.hoop.x+45;D.line(c,[{x:left,y:this.hoop.y},{x:right,y:this.hoop.y}],'#d89069',6);D.poly(c,[{x:left,y:this.hoop.y+4},{x:right,y:this.hoop.y+4},{x:right-15,y:this.hoop.y+64},{x:left+15,y:this.hoop.y+64}], '#fffef03d','#a5b5a4',2);for(let i=1;i<5;i++)D.line(c,[{x:left+18*i,y:this.hoop.y+5},{x:left+15+12*i,y:this.hoop.y+61}],'#a5b5a4',1);D.animal(c,125,429,.86,this.player?'fox':'rabbit');const b=this.ball;D.circle(c,b.x,b.y,14,'#dca168','#9e795a');D.line(c,[{x:b.x-13,y:b.y},{x:b.x+13,y:b.y}],'#a87950',1.5);D.line(c,[{x:b.x,y:b.y-13},{x:b.x,y:b.y+13}],'#a87950',1.5);if(this.drag){const vx=(this.drag.x-this.pull.x)*4,vy=(this.drag.y-this.pull.y)*4;const ps=[];for(let i=0;i<13;i++){const t=i*.07;ps.push({x:b.x+vx*t,y:b.y+vy*t+285*t*t});}D.line(c,ps,'#829b72',3,[4,9]);D.line(c,[this.drag,this.pull],'#d39d64',3);}if(this.charging){D.round(c,92,320,175,16,8,'#d8d8bd');D.round(c,92,320,175*this.charge,16,8,'#72976b');}D.badge(c,this.two?`甲 ${this.turnScores[0]}　·　乙 ${this.turnScores[1]}`:'按住 Space 蓄力，放開投籃');this.noticeDraw();}
}
registerGame({id:'bounce-basket',name:'跳跳投籃',en:'BOUNCE BASKET',category:'運動',desc:'按住蓄力、放手投籃，掌握恰好的力度。',tag:'物理投籃',guide:'按住 Space 蓄力，再放開投籃；手機按住「蓄力投籃」再放開。力度條幫你掌握距離。球從籃框上方落入得分；最多 7 球，或失 3 球後結算。',design:'拋物線、籃框碰撞、移動籃框及雙人輪流計分；不是多人即時搶球。',keys:[['action','蓄力投籃']]},BounceBasket);

class MeadowCricket extends WQGame{
 constructor(a){super(a);this.round=0;this.hit=0;this.wait=.8;this.swing=0;this.launchBall();this.tools([]);this.hint('球到金色擊球圈時，按一下「揮棒」。共 10 球。');}
 launchBall(){this.ball={x:710,y:385,mode:'pitch',vx:-[235,305,375][this.d],vy:0};this.wait=.8;this.didSwing=false;}
 act(k){if(k!=='action'||this.didSwing||this.wait>0||this.ball.mode!=='pitch')return;this.didSwing=true;this.swing=.3;const err=Math.abs(this.ball.x-210),window=[70,55,42][this.d];if(err<window){const points=err<window*.3?6:err<window*.65?4:1;this.score+=points;this.hit++;this.ball.mode='hit';this.ball.vx=380+points*20;this.ball.vy=-370-points*30;this.sound(650+points*45,.1);this.say(points===6?'正中甜區！6 分':`${points} 分，好球！`);}else{this.say('揮早了，看準金色圈再按。');}}
 pointer(type){if(type==='down')this.act('action');}
 update(dt){this.swing=Math.max(0,this.swing-dt);if(this.wait>0){this.wait-=dt;return;}const b=this.ball;b.x+=b.vx*dt;if(b.mode==='pitch')b.y=392-Math.abs(Math.sin((710-b.x)/140))*35;else{b.vy+=530*dt;b.y+=b.vy*dt;}if(b.x<95||b.x>865||b.y>580){this.round++;if(this.round>=10){this.end(`總分 ${this.score}，成功擊中 ${this.hit} / 10 球。`,'草地球賽完成');return;}this.launchBall();}this.stat=`第 ${this.round+1} / 10 球`;}
 draw(){const c=this.c;D.bg(c);D.cloud(c,143,95,1);D.cloud(c,620,120,1.4);D.hills(c,405);D.round(c,135,381,600,94,30,'#dbc79b');D.line(c,[{x:205,y:396},{x:670,y:396}],'#f7ebc8',2,[12,15]);D.circle(c,210,385,[45,38,32][this.d],'#f7e3a54d','#ebc36c');D.line(c,[{x:180,y:382},{x:180,y:439}],'#b88b60',5);D.line(c,[{x:193,y:382},{x:193,y:439}],'#b88b60',5);D.animal(c,150,396,.82,'rabbit','#ba9461');c.save();c.translate(170,385);c.rotate(this.swing>0?-1.1:.4);D.round(c,-5,-3,13,75,5,'#a98356');D.round(c,-9,24,22,61,6,'#f2d499');c.restore();D.animal(c,725,372,.67,'fox');D.circle(c,this.ball.x,this.ball.y,10,'#fff7df','#c8b080');D.badge(c,'看準時機，只需一下');this.noticeDraw();}
}
registerGame({id:'meadow-cricket',name:'草地擊球',en:'MEADOW CRICKET',category:'運動',desc:'球到甜區才出手，揮出漂亮一球。',tag:'時機挑戰',guide:'球由右方過來，到達左邊金色圈時按「揮棒」或空白鍵。越接近中心，得分越高。每球只能揮一次，共 10 球。',design:'依實際擊球時機判定 1、4、6 分，難度改變球速與有效範圍。',keys:[['action','揮棒']]},MeadowCricket);

