/* WordQuest arcade physics. Original artwork and rules. No network, audio or DOM. */
(function(root){'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const rnd=s=>{let n=s.seed|0;n^=n<<13;n^=n>>>17;n^=n<<5;s.seed=n|0;return(n>>>0)/4294967296;};
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const spec={
 kart:{id:'kart',name:'彎道競速',tag:'路線 × 速度',cost:5,w:720,h:480,description:'轉彎、飄移、超車。與三位車手跑完三圈。',keys:'← → 轉向 · 空白鍵飄移 · X 加速',metric:'完成三圈'},
 volley:{id:'volley',name:'沙灘排球',tag:'時機 × 球路',cost:4,w:720,h:480,description:'接球、跳起扣球。先取五分贏一場。',keys:'← → 移動 · 空白鍵跳躍 · X 扣球',metric:'贏得回合'},
 stairs:{id:'stairs',name:'深層探險',tag:'落點 × 判斷',cost:3,w:420,h:600,description:'逐層下降，避開頂部。平台會移動、碎裂或彈起。',keys:'← → 移動；留意平台邊緣',metric:'最深樓層'},
 shooter:{id:'shooter',name:'星際防線',tag:'走位 × 應變',cost:4,w:480,h:640,description:'自動發射，移動避彈。每四波迎戰大型無人機。',keys:'方向鍵或拖動飛船 · X／空白鍵護盾',metric:'最高分'},
 memory:{id:'memory',name:'圖形配對',tag:'觀察 × 記憶',cost:3,w:640,h:480,description:'四、六或八對圖形。用更少翻牌次數完成。',keys:'方向鍵選牌 · 空白鍵翻牌；亦可直接按牌',metric:'最少翻牌'},
 simon:{id:'simon',name:'音階密碼',tag:'聲音 × 次序',cost:3,w:600,h:480,description:'看形狀、聽音階，再按相同次序。逐輪增加長度。',keys:'1 2 3 4 或按形狀；示範中不用按',metric:'最長次序'}
};
// Track has a changing centre line; distance/steering are not three fixed lanes.
const track=[];let length=0;
for(let i=0;i<=240;i++){const a=i/240*Math.PI*2;const p={x:360+258*Math.cos(a)+18*Math.sin(3*a),y:238+157*Math.sin(a)+18*Math.cos(2*a)};if(i)length+=dist(p,track[i-1]);p.s=length;track.push(p);}
function trackAt(s){s=((s%length)+length)%length;let lo=0,hi=track.length-1;while(hi-lo>1){let m=(lo+hi)>>1;if(track[m].s<s)lo=m;else hi=m;}const a=track[lo],b=track[hi],f=(s-a.s)/(b.s-a.s||1),dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy);return{x:a.x+(b.x-a.x)*f,y:a.y+(b.y-a.y)*f,tx:dx/l,ty:dy/l,nx:-dy/l,ny:dx/l,angle:Math.atan2(dy,dx)};}
function curveAt(s){const a=trackAt(s),b=trackAt(s+26);let d=b.angle-a.angle;while(d>Math.PI)d-=2*Math.PI;while(d< -Math.PI)d+=2*Math.PI;return d/26;}
function create(game,level=1,seed=Date.now()){if(!spec[game])throw Error('Unknown game');level=clamp(Math.round(level),0,2);const s={v:1,game,level,seed:(seed|0)||12887,time:0,score:0,result:null,event:[],w:spec[game].w,h:spec[game].h};
if(game==='kart')Object.assign(s,{distance:0,offset:0,speed:0,laps:0,boosts:1,boost:0,drift:0,wasDrift:false,pickup:360,collision:0,cars:[{s:-18,off:-20,speed:0},{s:-38,off:14,speed:0},{s:-54,off:-2,speed:0}],rank:1});
if(game==='volley')Object.assign(s,{p:{x:180,y:380,vx:0,vy:0},ai:{x:540,y:380,vx:0,vy:0,target:540,react:0},ball:{x:180,y:244,vx:165,vy:-265},points:[0,0],servePause:.8,serveSide:0,jumpHeld:false,hitCool:0,hitFlash:0});
if(game==='stairs'){Object.assign(s,{player:{x:210,y:171,vx:0,vy:0},camera:0,nextId:1,platforms:[],floor:0,lives:3,inv:0,gems:0});for(let i=0;i<8;i++)addPlatform(s,200+i*92,i===0?210:undefined);}
if(game==='shooter')Object.assign(s,{p:{x:240,y:550,hp:3,inv:0},bullets:[],enemies:[],sparks:[],drops:[],wave:0,waveClock:1,shot:0,shield:0,shieldCooldown:0,nextEnemy:1,bosses:0,chain:0});
if(game==='memory'){const n=[4,6,8][level];const cards=Array.from({length:n*2},(_,i)=>Math.floor(i/2));for(let i=cards.length-1;i>0;i--){let j=Math.floor(rnd(s)*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]];}Object.assign(s,{cards,open:[],matched:[],wait:0,moves:0,cursor:0,previousSpace:false});}
if(game==='simon')Object.assign(s,{sequence:[Math.floor(rnd(s)*4),Math.floor(rnd(s)*4)],phase:'show',showIndex:0,phaseClock:.45,lit:-1,answer:0,lives:[3,3,2][level],best:0});
return s;}
function addPlatform(s,y,centre){const prior=s.platforms.at(-1),id=s.nextId++;const width=[124,108,94][s.level];const cx=centre===undefined?clamp((prior?prior.base:210)+(rnd(s)*2-1)*76,68,352):centre;let kind='normal';if(id>7){const r=rnd(s);kind=r<.19?'moving':r<.34?'crumble':r<.44?'spring':'normal';}s.platforms.push({id,base:cx,x:cx-width/2,y,w:width,kind,phase:rnd(s)*6.28,crack:0,broken:false,gem:id%3===0,taken:false});}
function tick(s,input={},dt=1/60){s.event=[];if(s.result)return s;dt=clamp(Number(dt)||0,0,.05);s.time+=dt;
if(s.game==='kart')kart(s,input,dt);if(s.game==='volley')volley(s,input,dt);if(s.game==='stairs')stairs(s,input,dt);if(s.game==='shooter')shooter(s,input,dt);if(s.game==='memory')memory(s,input,dt);if(s.game==='simon')simon(s,input,dt);return s;}
function end(s,title,won=false){if(s.result)return;s.result={title,won,score:Math.round(s.score),seconds:Math.round(s.time*10)/10};s.event.push({fx:won?'win':'end'});}
function kart(s,i,dt){const steer=(i.right?1:0)-(i.left?1:0);if(i.special&&!i.specialHeld&&s.boosts>0){s.boost=1.4;s.boosts--;s.event.push({fx:'boost'});}i.specialHeld=!!i.special;s.boost=Math.max(0,s.boost-dt);s.collision=Math.max(0,s.collision-dt);const drifting=!!i.action&&!!steer&&s.speed>70;
if(drifting)s.drift=Math.min(1.8,s.drift+dt);if(s.wasDrift&&!i.action&&s.drift>.42){s.boost=Math.max(s.boost,s.drift*.65);s.event.push({fx:'boost'});s.drift=0;}if(!drifting&&i.action)s.drift=Math.max(0,s.drift-dt);s.wasDrift=!!i.action;
const cv=curveAt(s.distance),offroad=Math.abs(s.offset)>39;let target=(s.boost?235:154)*(offroad?.36:1)*(drifting?.85:1);if(s.collision>0)target*=.48;s.speed+=(target-s.speed)*Math.min(1,dt*3.2);s.offset+=steer*(drifting?105:84)*dt -cv*s.speed*s.speed*(s.level===0?.075:.23)*dt;s.offset=clamp(s.offset,-65,65);s.distance+=Math.max(12,s.speed*(1-Math.min(.2,Math.abs(s.offset)*.0015)))*dt;
if(s.distance>=s.pickup){s.pickup+=390;s.boosts=Math.min(2,s.boosts+1);s.event.push({fx:'collect'});}s.cars.forEach((c,n)=>{c.speed+=(105+s.level*15+n*3-c.speed)*dt*1.6;c.s+=c.speed*dt;c.off=Math.sin(s.time*.65+n*2)*24;if(Math.abs(c.s-s.distance)<14&&Math.abs(c.off-s.offset)<17&&s.collision===0){s.collision=.45;s.offset+=s.offset>=c.off?8:-8;s.event.push({fx:'bump'});}});s.rank=1+s.cars.filter(c=>c.s>s.distance).length;s.laps=Math.floor(s.distance/length);s.score=Math.floor(s.distance/10);if(s.distance>=length*3)end(s,'完成三圈 · 第 '+s.rank+' 名',true);}
function volley(s,i,dt){s.hitCool=Math.max(0,s.hitCool-dt);s.hitFlash=Math.max(0,s.hitFlash-dt);if(s.servePause>0){s.servePause-=dt;s.ball.x=s.serveSide?540:180;s.ball.y=230;if(s.servePause<=0){s.ball.vx=s.serveSide?-175:175;s.ball.vy=-330;}return;}
const ground=389,p=s.p,a=s.ai,b=s.ball;const move=(actor,dir,jump,speed)=>{actor.vx=dir*speed;actor.x+=actor.vx*dt;if(jump&&actor.y>=ground-.1)actor.vy=-390;actor.vy+=930*dt;actor.y+=actor.vy*dt;if(actor.y>=ground){actor.y=ground;actor.vy=0;}};
move(p,(i.right?1:0)-(i.left?1:0),i.action&&!s.jumpHeld,225);p.x=clamp(p.x,35,321);s.jumpHeld=!!i.action;
a.react-=dt;if(a.react<=0){a.react=[.32,.22,.13][s.level];a.target=b.x>340?clamp(b.x+(b.vx*.16)+18,399,680):535;}
const adir=Math.abs(a.target-a.x)>8?Math.sign(a.target-a.x):0;const ajump=b.x>360&&Math.abs(a.x-b.x)<64&&b.y>215&&b.y<315&&b.vy> -140;move(a,adir,ajump,[140,169,190][s.level]);a.x=clamp(a.x,399,685);
b.vy+=575*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<13){b.x=13;b.vx=Math.abs(b.vx)*.88;}if(b.x>707){b.x=707;b.vx=-Math.abs(b.vx)*.88;}if(b.y<18){b.y=18;b.vy=Math.abs(b.vy)*.7;}
for(const [actor,side]of [[p,1],[a,-1]]){const dx=b.x-actor.x,dy=b.y-actor.y,d=Math.hypot(dx,dy);if(d<42){let nx=dx/(d||1),ny=dy/(d||1);if(ny>-.12)ny=-.25;const normalLength=Math.hypot(nx,ny)||1;nx/=normalLength;ny/=normalLength;b.x=actor.x+nx*44;b.y=actor.y+ny*44;const spike=side===1?i.special&&s.hitCool===0&&p.y<355:a.y<355&&b.x>380;if(spike){b.vx=side*(285+s.level*12);b.vy=60;s.hitCool=.55;s.hitFlash=.25;}else{b.vx=clamp(nx*260+actor.vx*.34+side*65,-340,340);b.vy=-Math.max(330,Math.abs(b.vy)*.72+(-actor.vy)*.25);}s.event.push({fx:'ball'});}}
if(b.y>=226&&Math.abs(b.x-360)<17){if(b.y<244&&b.vy>0){b.y=226;b.vy=-Math.abs(b.vy)*.8;}else{b.x=b.x<360?342:378;b.vx=(b.x<360?-1:1)*Math.max(70,Math.abs(b.vx));}}
if(b.y>=414){const winner=b.x>360?0:1;s.points[winner]++;s.score=s.points[0];s.event.push({fx:winner===0?'point':'bump'});if(Math.max(...s.points)>=5)end(s,s.points[0]>s.points[1]?'你贏了這場':'再挑戰一場',s.points[0]>s.points[1]);else{s.serveSide=winner===0?0:1;s.servePause=1.1;p.x=180;a.x=540;p.y=a.y=389;p.vy=a.vy=0;}}}
function stairs(s,i,dt){const p=s.player,speed=[25,34,44][s.level]+Math.min(27,s.floor*.55);s.camera+=speed*dt;s.inv=Math.max(0,s.inv-dt);p.vx=((i.right?1:0)-(i.left?1:0))*[208,223,240][s.level];p.x=clamp(p.x+p.vx*dt,14,406);const prev=p.y;p.vy=Math.min(500,p.vy+780*dt);p.y+=p.vy*dt-speed*dt;
for(const f of s.platforms){f.y-=speed*dt;if(f.kind==='moving')f.x=f.base-f.w/2+Math.sin(s.time*1.6+f.phase)*23;if(f.crack>0){f.crack+=dt;if(f.crack>.75)f.broken=true;}
if(!f.broken&&p.vy>=0&&prev+15<=f.y+speed*dt+7&&p.y+15>=f.y&&p.x>f.x-9&&p.x<f.x+f.w+9){p.y=f.y-15;p.vy=f.kind==='spring'?-240:0;if(f.kind==='crumble'&&!f.crack)f.crack=.001;s.floor=Math.max(s.floor,f.id-1);if(f.gem&&!f.taken){f.taken=true;s.gems++;s.event.push({fx:'collect'});}}
}
s.platforms=s.platforms.filter(f=>f.y> -60);while((s.platforms.at(-1)?.y||0)<740)addPlatform(s,(s.platforms.at(-1)?.y||620)+[94,98,102][s.level]);s.score=s.floor*10+s.gems*5;
if((p.y<56||p.y>620)&&s.inv===0){s.lives--;s.event.push({fx:'bump'});if(!s.lives){end(s,'到達第 '+s.floor+' 層');return;}const f=s.platforms.find(f=>f.y>200&&f.y<420&&!f.broken)||s.platforms[0];p.x=f.x+f.w/2;p.y=f.y-17;p.vy=0;s.inv=1.6;}}
function spawnWave(s){s.wave++;if(s.wave%4===0){s.enemies.push({id:s.nextEnemy++,x:240,y:65,base:240,hp:34+s.level*12,maxHp:34+s.level*12,boss:true,t:0,fire:1.7,cue:0});return;}const n=4+s.level;for(let j=0;j<n;j++)s.enemies.push({id:s.nextEnemy++,x:50+j*380/(n-1),base:50+j*380/(n-1),y:-40-j*26,hp:s.level===2?3:2,maxHp:3,boss:false,t:j*.3,fire:1.3+rnd(s)*1.5,cue:0});}
function shooter(s,i,dt){const p=s.p;p.inv=Math.max(0,p.inv-dt);s.shield=Math.max(0,s.shield-dt);s.shieldCooldown=Math.max(0,s.shieldCooldown-dt);if((i.special||i.action)&&s.shieldCooldown===0){s.shield=2.2;s.shieldCooldown=10;s.event.push({fx:'shield'});}
if(i.aim){p.x+=(clamp(i.aim.x,18,462)-p.x)*Math.min(1,dt*13);p.y+=(clamp(i.aim.y,310,610)-p.y)*Math.min(1,dt*13);}else{p.x=clamp(p.x+((i.right?1:0)-(i.left?1:0))*265*dt,18,462);p.y=clamp(p.y+((i.down?1:0)-(i.up?1:0))*265*dt,310,610);}
s.shot-=dt;if(s.shot<=0){s.shot=.15;s.bullets.push({x:p.x-6,y:p.y-20,vx:0,vy:-435,own:true},{x:p.x+6,y:p.y-20,vx:0,vy:-435,own:true});}
s.waveClock-=dt;if(s.waveClock<=0&&s.enemies.length===0){spawnWave(s);s.waveClock=7;}
for(const e of s.enemies){e.t+=dt;if(e.boss){e.x=240+Math.sin(e.t*.7)*150;e.y=70+Math.sin(e.t)*12;}else{e.y+=([28,40,50][s.level]+s.wave)*dt;e.x=clamp(e.base+Math.sin(e.t*1.8)*26,20,460);}e.fire-=dt;e.cue=e.fire<.35?1:0;if(e.fire<=0&&e.y>0){e.fire=e.boss?1.3:[2.1,1.65,1.3][s.level];if(e.boss){for(let j=-3;j<=3;j++){let angle=Math.PI/2+j*.21;s.bullets.push({x:e.x,y:e.y+25,vx:Math.cos(angle)*155,vy:Math.sin(angle)*155,own:false});}}else{const angle=Math.atan2(p.y-e.y,p.x-e.x);s.bullets.push({x:e.x,y:e.y+18,vx:Math.cos(angle)*(105+s.level*20),vy:Math.sin(angle)*(105+s.level*20),own:false});}}if(e.y>665)e.hp=0;}
for(const b of s.bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.own){for(const e of s.enemies){if(e.hp>0&&Math.hypot(b.x-e.x,b.y-e.y)<(e.boss?38:18)){e.hp--;b.dead=true;if(e.hp<=0){s.score+=e.boss?150:15;s.event.push({fx:'hit'});s.sparks.push({x:e.x,y:e.y,t:.3});if(e.boss){s.bosses++;p.hp=Math.min(4,p.hp+1);}else if(rnd(s)<.12)s.drops.push({x:e.x,y:e.y});}break;}}}else if(dist(b,p)<(s.shield>0?40:16)){b.dead=true;if(s.shield===0&&p.inv===0){p.hp--;p.inv=1.2;s.event.push({fx:'bump'});}}}
for(const e of s.enemies)if(e.hp>0&&dist(e,p)<(e.boss?50:30)&&p.inv===0&&s.shield===0){p.hp--;p.inv=1.2;e.hp=0;s.event.push({fx:'bump'});}
s.bullets=s.bullets.filter(b=>!b.dead&&b.x> -40&&b.x<520&&b.y> -30&&b.y<690).slice(-250);s.enemies=s.enemies.filter(e=>e.hp>0);for(const d of s.drops){d.y+=78*dt;if(dist(d,p)<26){d.dead=true;p.hp=Math.min(4,p.hp+1);s.event.push({fx:'collect'});}}s.drops=s.drops.filter(d=>!d.dead&&d.y<660);for(const z of s.sparks)z.t-=dt;s.sparks=s.sparks.filter(z=>z.t>0);if(p.hp<=0)end(s,'到達第 '+s.wave+' 波 · '+s.score+' 分');}
function memoryCells(s){const cols=4,rows=s.cards.length/4,cw=114,ch=Math.min(106,336/rows),left=92,top=60;return s.cards.map((v,j)=>({x:left+(j%cols)*cw,y:top+Math.floor(j/cols)*(ch+12),w:cw-12,h:ch}));}
function memory(s,i,dt){if(s.wait>0){s.wait-=dt;if(s.wait<=0)s.open=[];return;}if(Number.isInteger(i.cell)){const j=i.cell;i.cell=null;if(j<0||j>=s.cards.length||s.open.includes(j)||s.matched.includes(j))return;s.open.push(j);s.moves++;s.event.push({fx:'card'});if(s.open.length===2){const[a,b]=s.open;if(s.cards[a]===s.cards[b]){s.matched.push(a,b);s.open=[];s.event.push({fx:'point'});if(s.matched.length===s.cards.length){s.score=Math.max(1,1000-s.moves*9-Math.floor(s.time));end(s,s.moves+' 次翻牌 · 全部配對',true);}}else s.wait=.8;}}}
function simonCells(){return[{x:115,y:62,w:176,h:150},{x:309,y:62,w:176,h:150},{x:115,y:230,w:176,h:150},{x:309,y:230,w:176,h:150}];}
function simon(s,i,dt){const flash=[.55,.43,.32][s.level];if(s.phase==='show'){i.cell=null;s.phaseClock-=dt;if(s.phaseClock<=0){if(s.lit<0){if(s.showIndex>=s.sequence.length){s.phase='input';s.answer=0;s.lit=-1;return;}s.lit=s.sequence[s.showIndex];s.event.push({note:s.lit});s.phaseClock=flash;}else{s.lit=-1;s.showIndex++;s.phaseClock=.2;}}return;}if(s.phase==='between'){i.cell=null;s.phaseClock-=dt;if(s.phaseClock<=0){s.sequence.push(Math.floor(rnd(s)*4));s.phase='show';s.showIndex=0;s.lit=-1;s.phaseClock=.35;}return;}
if(s.lit>=0){s.phaseClock-=dt;if(s.phaseClock<=0)s.lit=-1;}
if(Number.isInteger(i.cell)){const j=i.cell;i.cell=null;if(j<0||j>3)return;s.lit=j;s.phaseClock=.22;s.event.push({note:j});if(j!==s.sequence[s.answer]){s.lives--;if(!s.lives){s.score=s.best;end(s,'記住了 '+s.best+' 個音');}else{s.phase='show';s.showIndex=0;s.lit=-1;s.phaseClock=.9;s.answer=0;s.event.push({fx:'bump'});}return;}s.answer++;if(s.answer===s.sequence.length){s.best=s.sequence.length;s.score=s.best;if(s.best>=20)end(s,'完成二十個音的挑戰',true);else{s.phase='between';s.phaseClock=.8;s.lit=-1;s.event.push({fx:'point'});}}}}
function hitCell(s,x,y){const boxes=s.game==='memory'?memoryCells(s):s.game==='simon'?simonCells():[];return boxes.findIndex(b=>x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h);}
function snapshotValid(s,game,level){if(!s||s.v!==1||s.game!==game||s.level!==level||!Number.isFinite(s.time)||s.time<0||s.time>180.5)return false;const schema=create(game,level,1);if(Object.keys(schema).some(k=>!(k in s)||((schema[k]!==null)&&((Array.isArray(schema[k])&&!Array.isArray(s[k]))||(!Array.isArray(schema[k])&&typeof schema[k]!==typeof s[k])))))return false;if(game==='memory'&&(s.cards.length!==[8,12,16][level]||s.cards.some(x=>!Number.isInteger(x)||x<0||x>=s.cards.length/2)))return false;let count=0;function safe(x,depth=0){if(depth>10||++count>12000)return false;if(typeof x==='number')return Number.isFinite(x)&&Math.abs(x)<1e12;if(x===null||typeof x==='boolean')return true;if(typeof x==='string')return x.length<=240;if(Array.isArray(x))return x.length<501&&x.every(v=>safe(v,depth+1));if(typeof x==='object')return Object.keys(x).every(k=>!['__proto__','constructor','prototype'].includes(k)&&safe(x[k],depth+1));return false;}return safe(s);}
const api={spec,create,tick,trackAt,curveAt,track,trackLength:length,memoryCells,simonCells,hitCell,snapshotValid};if(typeof module==='object'&&module.exports)module.exports=api;else root.WQArcadeCore=Object.freeze(api);
})(typeof window==='object'?window:globalThis);
