
/* WordQuest V24 — pure, shared learning evidence and assessment rules.
   Thresholds are product rules, not proof of permanent knowledge. */
(function(root,f){if(typeof module==='object'&&module.exports)module.exports=f();else root.WQEducation=f();})(globalThis,function(){
'use strict';
const RECENT_MS=10*60*1000,DAY=86400000;
const clean=s=>String(s??'').normalize('NFKC').replace(/[’‘]/g,"'").replace(/[“”]/g,'"').trim().replace(/\s+/g,' ');
const wordTokens=s=>clean(s).match(/[A-Za-z0-9]+(?:'[A-Za-z0-9]+)*/g)||[];
const fullTokens=s=>clean(s).match(/[A-Za-z0-9]+(?:'[A-Za-z0-9]+)*|[^\s]/g)||[];
function punctuationSignature(s){let n=0;const a=[];for(const t of fullTokens(s)){if(/^[A-Za-z0-9]/.test(t))n++;else a.push([n,t]);}return JSON.stringify(a);}
function wholeTerm(text,term,matchCase=false){const a=matchCase?clean(text):clean(text).toLowerCase(),b=matchCase?clean(term):clean(term).toLowerCase();if(!b)return false;let i=a.indexOf(b);while(i>=0){if((!i||!/[A-Za-z0-9']/.test(a[i-1]))&&(i+b.length===a.length||!/[A-Za-z0-9']/.test(a[i+b.length])))return true;i=a.indexOf(b,i+1);}return false;}
function wordScore(answer,expected,strict=true){const a=clean(answer),e=clean(expected),lexical=a.toLowerCase()===e.toLowerCase(),capitalization=a===e;return{correct:lexical&&(!strict||capitalization),lexical,capitalization,punctuation:true,targetCorrect:lexical&&(!strict||capitalization)};}
function sentenceScore(answer,expected,target,strict=true){const a=wordTokens(answer),e=wordTokens(expected),lexical=a.map(x=>x.toLowerCase()).join(' ')===e.map(x=>x.toLowerCase()).join(' '),capitalization=lexical&&a.join(' ')===e.join(' '),punctuation=punctuationSignature(answer)===punctuationSignature(expected);const targetIsSentence=/[.!?]/.test(target)||wordTokens(target).length>4;const targetCorrect=targetIsSentence?lexical&&(!strict||capitalization):wholeTerm(answer,target,strict);return{correct:lexical&&(!strict||capitalization)&&punctuation,lexical,capitalization,punctuation,targetCorrect};}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function gap(example,target){const s=String(example),t=String(target).trim();if(!t)return{html:'',valid:false,count:0};const q=t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const re=new RegExp('(^|[^A-Za-z0-9])('+q+")(?=$|[^A-Za-z0-9])",'gi');let out='',last=0,count=0,m;while((m=re.exec(s))){const at=m.index+m[1].length;out+=escape(s.slice(last,at))+'<strong class="gap" aria-label="空格">＿＿</strong>';last=at+m[2].length;count++;}if(!count)return{html:'<span class="muted">這句例句不適合填空。請按中文意思串字。</span>',valid:false,count:0};out+=escape(s.slice(last));/* Reject morphologically revealing alternatives such as apples next to an apple blank. */const remainder=s.replace(re,'$1 ').toLowerCase();const leak=new RegExp('(^|[^a-z])'+q.toLowerCase()+"(?:s|es|'s)(?=$|[^a-z])",'i').test(remainder);if(leak)return{html:'<span class="muted">這句例句包含答案提示。請按中文意思串字。</span>',valid:false,count};return{html:out,valid:true,count};}
function validDate(v){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const d=new Date(v+'T00:00:00Z');return Number.isFinite(+d)&&d.toISOString().slice(0,10)===v;}
function policy(value,children=[],ranges=[]){const p=value==null?{}:value;if(!p||typeof p!=='object'||Array.isArray(p))throw Error('學習設定格式錯誤');if(p.v!=null&&p.v!==1)throw Error('學習設定版本錯誤');if(p.grading!=null&&!['strict','practice'].includes(p.grading))throw Error('評分模式錯誤');if(p.gradePacing!=null&&typeof p.gradePacing!=='boolean')throw Error('年級設定錯誤');const rangeLocks=Object.create(null);if(p.rangeLocks!=null){if(typeof p.rangeLocks!=='object'||Array.isArray(p.rangeLocks))throw Error('範圍鎖格式錯誤');for(const [cid,rid]of Object.entries(p.rangeLocks)){if(!children.some(c=>c.id===cid)||!ranges.some(r=>r.id===rid&&r.childId===cid))throw Error('固定範圍不存在或不屬於孩子');rangeLocks[cid]=rid;}}return{v:1,grading:p.grading||'strict',gradePacing:p.gradePacing!==false,rangeLocks};}
function pace(grade,settings,enabled=true){const g=Math.max(1,Math.min(6,grade||3));const max=[6,8,12,12,16,16][g-1],fresh=[3,4,5,5,6,6][g-1];return{dailyMax:Math.min(settings.dailyMax,enabled?max:30),dailyNew:Math.min(settings.dailyNew,enabled?fresh:10)};}
function attemptContext(x){if(x==null)return null;if(x.v!==24||!['strict','practice'].includes(x.grading)||!['independent','recent-answer','hint','scaffold'].includes(x.reason))throw Error('作答證據格式錯誤');return{v:24,grading:x.grading,reason:x.reason};}
return Object.freeze({RECENT_MS,DAY,clean,wordTokens,fullTokens,punctuationSignature,wholeTerm,wordScore,sentenceScore,gap,validDate,policy,pace,attemptContext});
});

