
/* WordQuest V22 — typed, bounded local data; one existing star wallet.
   Browser storage is NOT a trusted server or an anti-cheat mechanism. */
(function(root,f){if(typeof module==='object'&&module.exports)module.exports=f();else root.WQRewards=f();})(globalThis,function(){
'use strict';
const Schema=typeof module==='object'&&module.exports?require('./game-schema.js'):globalThis.WQGameSchema;
const groups=[['moon-bells','bounce-basket','number-garden','forest-band'],['drift-path','meadow-cricket','honey-delivery','color-workshop'],['cloud-run','forest-pong','juice-lines','honeycomb-puzzle'],['valley-race','rolling-block','block-studio','star-rhythm'],['color-orbit','garden-paths','little-engineer','forest-freezer']];
const fast=new Set(['moon-bells','bounce-basket','drift-path','meadow-cricket','star-rhythm']);
const catalog=groups.flatMap((g,i)=>g.map(id=>({id,words:[0,5,15,30,50][i],seconds:fast.has(id)?90:180,cost:fast.has(id)?5:10})));
const ids=catalog.map(g=>g.id),bad=new Set(['__proto__','prototype','constructor']),skip=new Set(['api','c','r','meta','keys','preview']);
const plans={short:{cost:5,ms:90000},standard:{cost:10,ms:180000}};
const key=w=>String(w||'').normalize('NFKC').trim().toLowerCase().replace(/\s+/g,' ');
const validWord=w=>/^[a-z]+(?:['’-][a-z]+)*$/i.test(w)&&w.length<=100;
function int(n,a,b){if(!Number.isSafeInteger(n)||n<a||n>b)throw Error('invalid integer');return n;}
function finite(n,a,b){if(!Number.isFinite(n)||n<a||n>b)throw Error('invalid number');return n;}
function text(v,max=240){if(typeof v!=='string'||v.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(v))throw Error('invalid text');return v;}
function safeId(v){text(v,100);if(!/^[A-Za-z0-9_-]{1,100}$/.test(v)||bad.has(v))throw Error('invalid ID');return v;}
function object(o){if(!o||typeof o!=='object'||Array.isArray(o))throw Error('invalid object');for(const k of Object.keys(o))if(bad.has(k))throw Error('unsafe key');return o;}
function array(a,max=50000){if(!Array.isArray(a)||a.length>max)throw Error('invalid array');return a;}
// Tagged containers prevent __proto__ writes and preserve Map/Set/Infinity in real game states.
function encode(v,depth=0){if(depth>30)throw Error('state depth');if(v===undefined)return ['u'];if(v===null||typeof v==='boolean'||typeof v==='string')return v;if(typeof v==='number'){if(Number.isNaN(v))throw Error('NaN state');return Number.isFinite(v)?v:['n',v>0?1:-1];}if(Array.isArray(v))return ['a',v.map(x=>encode(x,depth+1))];if(v instanceof Set)return ['s',[...v].map(x=>encode(x,depth+1))];if(v instanceof Map)return ['m',[...v].map(([a,b])=>[encode(a,depth+1),encode(b,depth+1)])];if(typeof v==='object'){return ['o',Object.entries(v).map(([k,x])=>{if(bad.has(k))throw Error('unsafe key');return[k,encode(x,depth+1)];})];}throw Error('unsupported state');}
function decode(v,depth=0,budget={n:0}){if(++budget.n>180000||depth>30)throw Error('state size');if(v===null||typeof v==='boolean')return v;if(typeof v==='number')return finite(v,-Number.MAX_VALUE,Number.MAX_VALUE);if(typeof v==='string')return text(v,20000);array(v,2);if(v.length!==(v[0]==='u'?1:2))throw Error('state tag arity');switch(v[0]){case'u':return undefined;case'n':if(v[1]!==1&&v[1]!==-1)throw Error('number tag');return v[1]*Infinity;case'a':return array(v[1]).map(x=>decode(x,depth+1,budget));case's':return new Set(array(v[1]).map(x=>decode(x,depth+1,budget)));case'm':return new Map(array(v[1]).map(x=>{array(x,2);if(x.length!==2)throw Error('map tuple');return [decode(x[0],depth+1,budget),decode(x[1],depth+1,budget)];}));case'o':{const o={};for(const e of array(v[1])){array(e,2);if(e.length!==2)throw Error('object tuple');const k=text(e[0],100);if(bad.has(k)||Object.hasOwn(o,k))throw Error('unsafe/duplicate key');o[k]=decode(e[1],depth+1,budget);}return o;}default:throw Error('state tag');}}
function snapshot(g){const o={};for(const[k,v]of Object.entries(g))if(!skip.has(k))o[k]=v;const snap={v:1,id:g.meta.id,d:g.d,r:g.r.state(),state:encode(o)};if(JSON.stringify(snap).length>900000)throw Error('game snapshot exceeds 900 KB');verifySnapshot(snap);return snap;}
function verifySnapshot(s){object(s);if(s.v!==1||!ids.includes(s.id))throw Error('snapshot ID');int(s.d,0,2);int(s.r,0,0xffffffff);if(JSON.stringify(s).length>900000)throw Error('snapshot too large');const state=object(decode(s.state));for(const k of Object.keys(state))if(skip.has(k)||['tick','draw','update','act','tool','pointer','key','tools','hint','say','sound','end','next','constructor'].includes(k))throw Error('unsafe state member');Schema.validate(s.id,state,s.d);return s;}
function restore(g,s,rng){verifySnapshot(s);if(s.id!==g.meta.id||s.d!==g.d)throw Error('wrong game or difficulty');const state=decode(s.state);for(const[k,v]of Object.entries(state)){if(typeof g[k]==='function')throw Error('method override');g[k]=v;}g.r=rng(s.r);g.keys.clear();return g;}
function initial(mode='legacy'){return {v:1,mode,children:{}};}
function child(){return{limit:15,difficulty:1,override:{},evidence:Object.create(null),phraseEvidence:Object.create(null),sentenceEvidence:Object.create(null),days:{},sessions:[],ticket:null,saves:{},extras:{},bests:{},hints:[],pending:{},bonusSession:null};}
function get(root,cid){if(bad.has(cid))throw Error('child ID');return root.children[cid]||(root.children[cid]=child());}
function validDate(v){text(v,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v+'T00:00:00Z'))||new Date(v+'T00:00:00Z').toISOString().slice(0,10)!==v)throw Error('invalid day');return v;}
function day(c,date){validDate(date);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Error('day');for(const k of Object.keys(c.days).sort().slice(0,-120))delete c.days[k];return c.days[date]||(c.days[date]={usedMs:0,earned:0,keys:[],bonus:false});}
function counts(c){const words=Object.values(c.evidence).filter(v=>v.qualifiedAt>0).length+Object.values(c.phraseEvidence||{}).filter(v=>v.qualifiedAt>0).length,sentences=Object.values(c.sentenceEvidence||{}).filter(v=>v.qualifiedAt>0).length;return{words,sentences,total:words+sentences};}
function count(c){return counts(c).total;}
function allowed(c,id,admin=false){const g=catalog.find(g=>g.id===id);return !!g&&(admin||c.override[id]==='open'||(c.override[id]!=='blocked'&&count(c)>=g.words));}
function reveal(c,word,now){const k=key(word);if(!validWord(k)||!Object.hasOwn(c.evidence,k)&&Object.keys(c.evidence).length>=10000)return;const e=Object.hasOwn(c.evidence,k)?c.evidence[k]:(c.evidence[k]={meaning:false,first:0,lastReveal:0,qualifiedAt:0,lastCorrect:0});e.lastReveal=Math.max(e.lastReveal,now);}
function attempt(c,{word,type,correct,hinted=false,time}){const k=key(word);if(!validWord(k)||!Object.hasOwn(c.evidence,k)&&Object.keys(c.evidence).length>=10000)return false;finite(time,1,1e15);const e=Object.hasOwn(c.evidence,k)?c.evidence[k]:(c.evidence[k]={meaning:false,first:0,lastReveal:0,qualifiedAt:0,lastCorrect:0});if(type==='meaning'&&correct&&!hinted)e.meaning=true;
 if(['spell','listenSpell'].includes(type)&&correct&&!hinted){if(e.meaning&&e.first>0&&time-e.first>=86400000&&time-e.lastReveal>=86400000)e.qualifiedAt=e.qualifiedAt||time;e.first=e.first||time;e.lastCorrect=time;}
 if(hinted||!correct)reveal(c,word,time);return !!e.qualifiedAt;}
const validPhrase=w=>typeof w==='string'&&w.length<=240&&/^[a-z]+(?:['’-][a-z]+)*(?: [a-z]+(?:['’-][a-z]+)*)+$/i.test(w);
function phraseReveal(c,word,time){const k=key(word);if(!validPhrase(k))return;c.phraseEvidence=c.phraseEvidence||Object.create(null);if(!Object.hasOwn(c.phraseEvidence,k)&&Object.keys(c.phraseEvidence).length>=10000)return;finite(time,1,1e15);const e=c.phraseEvidence[k]||(c.phraseEvidence[k]={meaning:false,first:0,lastReveal:0,qualifiedAt:0,lastCorrect:0});e.lastReveal=Math.max(e.lastReveal,time);}
function phraseAttempt(c,{word,type,correct,hinted=false,time}){const k=key(word);if(!validPhrase(k))return false;c.phraseEvidence=c.phraseEvidence||Object.create(null);if(!Object.hasOwn(c.phraseEvidence,k)&&Object.keys(c.phraseEvidence).length>=10000)return false;finite(time,1,1e15);const e=c.phraseEvidence[k]||(c.phraseEvidence[k]={meaning:false,first:0,lastReveal:0,qualifiedAt:0,lastCorrect:0});if(type==='meaning'&&correct&&!hinted)e.meaning=true;if(['spell','listenSpell'].includes(type)&&correct&&!hinted){if(e.meaning&&e.first>0&&time-e.first>=86400000&&time-e.lastReveal>=86400000)e.qualifiedAt=e.qualifiedAt||time;e.first=e.first||time;e.lastCorrect=time;}if(hinted||!correct)phraseReveal(c,word,time);return !!e.qualifiedAt;}
const validSentence=w=>typeof w==='string'&&w.length<=400&&/^[a-z0-9][a-z0-9 ,.!?;:'"’()\-]*$/i.test(w)&&w.trim().split(/\s+/).length>=2;
function sentenceReveal(c,word,time){const k=key(word);if(!validSentence(k))return;c.sentenceEvidence=c.sentenceEvidence||Object.create(null);if(!Object.hasOwn(c.sentenceEvidence,k)&&Object.keys(c.sentenceEvidence).length>=10000)return;const e=c.sentenceEvidence[k]||(c.sentenceEvidence[k]={first:0,lastReveal:0,qualifiedAt:0,lastCorrect:0});finite(time,1,1e15);e.lastReveal=Math.max(e.lastReveal,time);}
function sentenceAttempt(c,{word,correct,hinted=false,time}){const k=key(word);if(!validSentence(k))return false;finite(time,1,1e15);c.sentenceEvidence=c.sentenceEvidence||Object.create(null);if(!Object.hasOwn(c.sentenceEvidence,k)&&Object.keys(c.sentenceEvidence).length>=10000)return false;const e=c.sentenceEvidence[k]||(c.sentenceEvidence[k]={first:0,lastReveal:0,qualifiedAt:0,lastCorrect:0});if(correct&&!hinted){if(e.first>0&&time-e.first>=86400000&&time-e.lastReveal>=86400000)e.qualifiedAt=e.qualifiedAt||time;e.first=e.first||time;e.lastCorrect=time;}else sentenceReveal(c,word,time);return !!e.qualifiedAt;}
function earn(c,date,word,type,eligible){const d=day(c,date),k=key(word)+'|'+type;if(!eligible||d.keys.includes(k)||d.earned>=30)return 0;d.keys.push(k);d.earned++;return 1;}
function bonus(c,date){const d=day(c,date);if(d.bonus)return 0;d.bonus=true;const n=Math.min(5,30-d.earned);d.earned+=n;return n;}
function remainingDaily(c,date){return Math.max(0,c.limit*60000-day(c,date).usedMs);}
function purchase(c,balance,plan,date,receipt,id){if(!plans[plan])throw Error('unknown plan');int(balance,0,1000000);safeId(receipt);const existing=c.sessions.find(x=>x.id===receipt);if(existing)return{balance,ticket:c.ticket,duplicate:true};if(c.ticket&&c.ticket.remainingMs>0)throw Error('use remaining time first');if(!allowed(c,id))throw Error('game locked');const p=plans[plan];if(balance<p.cost)throw Error('insufficient stars');if(remainingDaily(c,date)<p.ms)throw Error('daily limit');const ticket={id:receipt,cost:p.cost,durationMs:p.ms,remainingMs:p.ms,usedMs:0,last:id,refunded:false};c.ticket=ticket;c.sessions.push({id:receipt,date,cost:p.cost,durationMs:p.ms,refunded:false});c.sessions=c.sessions.slice(-200);return{balance:balance-p.cost,ticket};}
function consume(c,date,ms){if(!c.ticket||c.ticket.refunded)return 0;finite(ms,0,86400000);const n=Math.min(ms,c.ticket.remainingMs,remainingDaily(c,date));c.ticket.remainingMs=Math.max(0,Math.round((c.ticket.remainingMs-n)*1e6)/1e6);c.ticket.usedMs=c.ticket.durationMs-c.ticket.remainingMs;day(c,date).usedMs=Math.round((day(c,date).usedMs+n)*1e6)/1e6;return n;}
function refund(c,balance,receipt){const t=c.ticket,r=c.sessions.find(x=>x.id===receipt);if(!t||t.id!==receipt||t.usedMs!==0||t.refunded||!r||r.refunded||r.cost!==t.cost||r.durationMs!==t.durationMs||t.remainingMs!==t.durationMs||![5,10].includes(t.cost)||t.durationMs!==(t.cost===5?90000:180000))return balance;int(balance,0,1000000-t.cost);t.refunded=true;t.remainingMs=0;r.refunded=true;return balance+t.cost;}
function validate(x,children){if(!x)return initial();object(x);if(x.v!==1||!['legacy','balanced'].includes(x.mode))throw Error('reward schema');const out=initial(x.mode),cids=new Set(children.map(c=>c.id));object(x.children);if(Object.keys(x.children).length>50)throw Error('profiles');for(const[cid,v]of Object.entries(x.children)){if(!cids.has(cid))continue;object(v);const c=child();c.limit=int(v.limit,0,60);c.difficulty=int(v.difficulty,0,2);object(v.override);for(const[id,m]of Object.entries(v.override)){if(!ids.includes(id)||!['open','blocked'].includes(m))throw Error('permission');c.override[id]=m;}
 if(!v.evidence||typeof v.evidence!=='object'||Array.isArray(v.evidence)||Object.keys(v.evidence).some(k=>k==='__proto__'))throw Error('evidence object');if(Object.keys(v.evidence).length>10000)throw Error('words');for(const[k,e]of Object.entries(v.evidence)){if(!validWord(k)||key(k)!==k)throw Error('word key');object(e);c.evidence[k]={meaning:e.meaning===true,first:finite(e.first,0,1e15),lastReveal:finite(e.lastReveal,0,1e15),qualifiedAt:finite(e.qualifiedAt,0,1e15),lastCorrect:finite(e.lastCorrect,0,1e15)};}
 const phrases=object(v.phraseEvidence||{});if(Object.keys(phrases).length>10000)throw Error('phrase evidence limit');for(const[k,e]of Object.entries(phrases)){if(!validPhrase(k)||key(k)!==k)throw Error('phrase key');object(e);c.phraseEvidence[k]={meaning:e.meaning===true,first:finite(e.first,0,1e15),lastReveal:finite(e.lastReveal,0,1e15),qualifiedAt:finite(e.qualifiedAt,0,1e15),lastCorrect:finite(e.lastCorrect,0,1e15)};}
 const sentences=object(v.sentenceEvidence||{});if(Object.keys(sentences).length>10000)throw Error('sentence evidence limit');for(const[k,e]of Object.entries(sentences)){if(!validSentence(k)||key(k)!==k)throw Error('sentence key');object(e);c.sentenceEvidence[k]={first:finite(e.first,0,1e15),lastReveal:finite(e.lastReveal,0,1e15),qualifiedAt:finite(e.qualifiedAt,0,1e15),lastCorrect:finite(e.lastCorrect,0,1e15)};}
 object(v.days);if(Object.keys(v.days).length>121)throw Error('days');for(const[k,d]of Object.entries(v.days)){day(c,k);c.days[k]={usedMs:finite(d.usedMs,0,86400000),earned:int(d.earned,0,30),keys:array(d.keys,10000).map(x=>text(x,400)),bonus:d.bonus===true};}
 c.sessions=array(v.sessions,200).map(r=>({id:safeId(r.id),date:validDate(r.date),cost:int(r.cost,0,10),durationMs:finite(r.durationMs,0,86400000),refunded:r.refunded===true}));if(new Set(c.sessions.map(r=>r.id)).size!==c.sessions.length)throw Error('duplicate receipts');for(const r of c.sessions){if(r.cost!==0&&(r.cost!==5||r.durationMs!==90000)&&(r.cost!==10||r.durationMs!==180000))throw Error('receipt price mismatch');if(r.cost===0&&r.refunded)throw Error('free transfer refund');}
 if(v.ticket){const t=object(v.ticket);c.ticket={id:safeId(t.id),cost:int(t.cost,0,10),durationMs:finite(t.durationMs,0,86400000),remainingMs:finite(t.remainingMs,0,t.durationMs),usedMs:finite(t.usedMs,0,t.durationMs),last:ids.includes(t.last)?t.last:ids[0],refunded:t.refunded===true};const r=c.sessions.find(r=>r.id===t.id);if(!r||r.cost!==c.ticket.cost||r.durationMs!==c.ticket.durationMs||r.refunded!==c.ticket.refunded||!ids.includes(t.last))throw Error('ticket mismatch');if(c.ticket.refunded){if(c.ticket.usedMs!==0||c.ticket.remainingMs!==0)throw Error('refunded ticket has time');}else if(Math.abs(c.ticket.usedMs+c.ticket.remainingMs-c.ticket.durationMs)>.001)throw Error('ticket time mismatch');}
 c.quarantine=Object.create(null);const quarantined=object(v.quarantine||{});if(Object.keys(quarantined).length>60)throw Error('quarantine limit');for(const[k,q]of Object.entries(quarantined)){if(!/^[a-z-]+\|[0-2]$/.test(k)||!ids.includes(k.split('|')[0]))throw Error('quarantine slot');object(q);c.quarantine[k]={reason:text(q.reason,200),raw:q.raw&&JSON.stringify(q.raw).length<=900000?JSON.parse(JSON.stringify(q.raw)):null};}object(v.saves);for(const[k,s]of Object.entries(v.saves)){if(!/^[a-z-]+\|[0-2]$/.test(k)||!ids.includes(k.split('|')[0]))throw Error('save key');try{verifySnapshot(s);if(k.split('|')[0]!==s.id||Number(k.split('|')[1])!==s.d)throw Error('save owner or difficulty');c.saves[k]=JSON.parse(JSON.stringify(s));}catch(e){c.quarantine[k]={reason:String(e.message).slice(0,200),raw:JSON.stringify(s).length<=900000?s:null};}}if(Object.keys(c.saves).length>60)throw Error('saves');
 c.extras=decode(encode(object(v.extras)));if(JSON.stringify(c.extras).length>60000)throw Error('extras');object(v.bests);for(const[k,n]of Object.entries(v.bests)){if(!ids.includes(k.split('|')[0]))throw Error('best key');c.bests[k]=finite(n,0,1e15);}
 c.hints=array(v.hints||[],2000).map(x=>text(x,100));c.pending={};for(const[k,p]of Object.entries(object(v.pending||{}))){safeId(k);c.pending[k]={en:text(p.en),wordId:safeId(p.wordId)};}if(Object.keys(c.pending).length>10000)throw Error('corrections');c.bonusSession=v.bonusSession==null?null:safeId(v.bonusSession);out.children[cid]=c;}return out;}
return{catalog,ids,plans,key,initial,child,get,day,count,counts,allowed,reveal,attempt,phraseAttempt,phraseReveal,sentenceAttempt,sentenceReveal,earn,bonus,remainingDaily,purchase,consume,refund,encode,decode,snapshot,restore,verifySnapshot,validate};
});

