
'use strict';
class ForestFreezer extends WQGame{
 constructor(a){super(a);this.flavors=['香草','草莓','朱古力','抹茶'];this.cols=['#efe1b3','#dfa59a','#a58b75','#9eaf82'];this.tops=['小花','彩糖','藍莓'];this.orders=[];this.counter=0;this.selected=0;this.served=0;this.lost=0;this.nextOrder=3;this.resetCup();this.addOrder();this.addOrder();this.toolbar();this.hint('看客人的訂單，依次加雪糕、選配料、攪拌，再交給客人。');}
 resetCup(){this.cup={scoops:[],top:0,mixed:false,quality:0};this.mixing=false;this.mix=0;}
 addOrder(){if(this.orders.length>=3)return;const n=2+(this.d===2?1:0);this.orders.push({id:++this.counter,recipe:Array.from({length:n},()=>Math.floor(this.r()*(this.d===0?3:4))),top:Math.floor(this.r()*3),left:[100,72,52][this.d],total:[100,72,52][this.d],animal:['rabbit','fox','owl'][this.counter%3]});}
 toolbar(){this.tools([...this.flavors.map((f,i)=>({id:'s'+i,label:f+'球'})),...this.tops.map((f,i)=>({id:'t'+i,label:f,active:this.cup.top===i})),{id:'mix',label:this.mixing?'停止攪拌':'開始攪拌'},{id:'serve',label:'交給客人'},{id:'clear',label:'重做這杯'}]);}
 tool(k){if(/^s[0-3]$/.test(k)){if(this.mixing){this.say('先停止攪拌。');return;}if(this.cup.scoops.length<4){this.cup.scoops.push(Number(k[1]));this.cup.mixed=false;this.sound(400+Number(k[1])*100,.08);}else this.say('這杯已經夠高了，可重做這杯。');}if(/^t[0-2]$/.test(k))this.cup.top=Number(k[1]);if(k==='mix'){if(!this.cup.scoops.length){this.say('先加入雪糕。');return;}if(this.mixing){this.cup.quality=WQCore.clamp(1-Math.abs(this.mix-.55)/.55,0,1);this.cup.mixed=true;this.mixing=false;this.say(this.cup.quality>.7?'攪拌得很均勻！':'攪拌完成；越接近綠色中間越好。');}else{this.mixing=true;this.mixStart=this.t;this.cup.mixed=false;}}if(k==='clear')this.resetCup();if(k==='serve')this.serve();this.toolbar();}
 act(k){if(k==='action')this.tool('mix');}
 serve(){const o=this.orders[this.selected];if(!o){this.say('等下一位客人到來。');return;}if(this.mixing){this.say('先停止攪拌，再交杯。');return;}if(!this.cup.mixed){this.say('先把雪糕攪拌好。');return;}if(this.cup.scoops.length!==o.recipe.length||this.cup.scoops.some((v,i)=>v!==o.recipe[i])||this.cup.top!==o.top){this.say('和訂單還有不同，對照口味、次序和配料。');return;}const score=100+Math.round(this.cup.quality*50);this.score+=score;this.served++;this.orders.splice(this.selected,1);this.selected=0;this.resetCup();this.sound(750,.16);this.say(`客人收到雪糕！+${score} 分`);if(this.served>=5+this.d)this.end(`完成 ${this.served} 杯雪糕，得到 ${this.score} 分。`,'雪糕店打烊了');else this.nextOrder=Math.min(this.nextOrder,2);}
 pointer(type,p){if(type==='down'&&p.y<235){const i=Math.floor((p.x-68)/225);if(i>=0&&i<this.orders.length){this.selected=i;this.say(`選了第 ${i+1} 位客人。`);}}}
 update(dt){if(this.mixing){const phase=((this.t-this.mixStart)*[.65,.85,1.1][this.d])%2;this.mix=phase<=1?phase:2-phase;}this.nextOrder-=dt;if(this.nextOrder<=0){this.addOrder();this.nextOrder=[18,14,11][this.d];}for(const o of this.orders)o.left-=dt;const before=this.orders.length;this.orders=this.orders.filter(o=>o.left>0);if(before>this.orders.length){this.lost+=before-this.orders.length;this.selected=Math.min(this.selected,Math.max(0,this.orders.length-1));this.say('一位客人先離開了，繼續照顧下一位。');}this.stat=`已完成 ${this.served} / ${5+this.d} 杯`;}
 draw(){const c=this.c;D.bg(c,'rose');D.round(c,0,0,800,43,0,'#7c9e83');for(let i=0;i<16;i++)D.round(c,i*50,0,27,44,0,'#b2c3a0');this.orders.forEach((o,i)=>{const x=68+i*225;D.round(c,x,69,211,174,16,i===this.selected?'#fffbea':'#f5eedf',i===this.selected?'#769267':'#d6d6bd');D.animal(c,x+42,130,.47,o.animal);D.text(c,`客人 ${o.id}`,x+130,91,13,'#6e815b');o.recipe.forEach((f,j)=>{D.circle(c,x+106+j*31,128,13,this.cols[f]);D.text(c,f+1,x+106+j*31,128,12,'#5d644a');});D.text(c,'配料：'+this.tops[o.top],x+127,166,12,'#6e815b');D.text(c,o.recipe.map(i=>this.flavors[i]).join(' → '),x+106,192,11,'#738062');D.round(c,x+15,220,180,7,3,'#e4dec9');D.round(c,x+15,220,180*Math.max(0,o.left/o.total),7,3,'#a3b585');});D.round(c,64,422,672,110,18,'#d3b690');D.round(c,54,412,692,27,10,'#f3e4c6');D.cup(c,400,340,117,105,0);this.cup.scoops.forEach((f,i)=>D.circle(c,400+(i%2?13:-13),345-i*31,29,this.cols[f],'#f9eddb'));if(this.cup.scoops.length){const y=322-(this.cup.scoops.length-1)*31;if(this.cup.top===0)D.star(c,400,y,12,'#efce80');if(this.cup.top===1)for(let i=0;i<7;i++)D.line(c,[{x:377+i*7,y:y+(i%2)*6},{x:380+i*7,y:y+5+(i%2)*6}],D.palette[i%6],3);if(this.cup.top===2)for(let i=0;i<3;i++)D.circle(c,386+i*14,y,7,'#798da2');}D.animal(c,660,370,.72,'cat','#8cab8a');D.text(c,'攪拌指針到綠色中間時，按停止',270,468,13,'#6c7958');D.round(c,111,492,317,17,8,'#e8dfc0');D.round(c,111+317*.4,492,317*.3,17,5,'#94b281');D.round(c,109+this.mix*317,484,5,31,2,'#466b54');if(!this.cup.scoops.length)D.text(c,'先按下方口味按鈕',405,313,16,'#9b9d77');this.noticeDraw();}
}
registerGame({id:'forest-freezer',name:'森林雪糕店',en:'FOREST FREEZER',category:'創作',desc:'接單、做雪糕，照顧每位小客人。',tag:'店舖經營',guide:'先看上方已選客人的訂單，依次按口味加球，再選配料。按「開始攪拌」，指針到綠色區域時按停止，最後交給客人。點其他客人的訂單可切换服務對象。',design:'實際訂單比對、多客排隊、等待時間、攪拌品質與完整結算。',keys:[]},ForestFreezer);

class ForestBand extends WQGame{
 constructor(a){super(a);this.names=['大鼓','手拍','沙鈴','低音','旋律'];this.bpm=[90,112,132][this.d];this.patterns=Array.from({length:5},()=>Array(16).fill(false));this.active=Array(5).fill(true);this.edit=0;this.playing=false;this.stepIndex=0;this.nextAudio=0;this.lastStep=-1;this.bars=0;this.preset(0);const saved=this.api.getData?.('band');if(this.valid(saved)){this.patterns=saved.patterns.map(r=>r.slice());this.bpm=saved.bpm;this.active=saved.active.slice();}this.toolbar();this.hint('按播放，開關每一拍；先選樂器，再點下方 1–16 拍。作品可保存及匯出。');}
 valid(v){return v&&Number.isFinite(v.bpm)&&v.bpm>=65&&v.bpm<=155&&Array.isArray(v.patterns)&&v.patterns.length===5&&v.patterns.every(r=>Array.isArray(r)&&r.length===16&&r.every(b=>typeof b==='boolean'))&&Array.isArray(v.active)&&v.active.length===5&&v.active.every(b=>typeof b==='boolean');}
 preset(n){this.patterns=Array.from({length:5},()=>Array(16).fill(false));const seqs=[[[0,8],[4,12],[0,2,4,6,8,10,12,14],[0,6,8,14],[2,7,10,15]],[[0,6,10],[4,12],[2,6,10,14],[0,4,8,12],[0,3,6,8,11,14]],[[0,3,8,11],[4,12],[0,2,4,6,8,10,12,14],[0,7,8,15],[1,4,7,10,13,15]]][n%3];seqs.forEach((row,i)=>row.forEach(j=>this.patterns[i][j]=true));this.active=Array(5).fill(true);}
 toolbar(){this.tools([{id:'play',label:this.playing?'停止合奏':'播放合奏'},{id:'slower',label:'慢一點'},{id:'faster',label:'快一點'},{id:'preset',label:'換個節奏'},{id:'save',label:'保存作品'},{id:'export',label:'匯出作品 JSON'},{id:'import',label:'匯入作品'},...this.names.map((n,i)=>({id:'track'+i,label:n,active:this.edit===i})),...Array.from({length:16},(_,i)=>({id:'step'+i,label:String(i+1),active:this.patterns[this.edit][i],ariaLabel:`${this.names[this.edit]}第 ${i+1} 拍${this.patterns[this.edit][i]?'開啟':'關閉'}`}))]);}
 snapshot(){return{version:1,title:'我的森林節奏',bpm:this.bpm,patterns:this.patterns.map(r=>r.slice()),active:this.active.slice()};}
 tool(k){if(k==='play'){this.playing=!this.playing;this.nextAudio=0;this.stepIndex=0;this.lastStep=-1;}if(k==='slower'){this.bpm=Math.max(65,this.bpm-5);this.nextAudio=0;}if(k==='faster'){this.bpm=Math.min(155,this.bpm+5);this.nextAudio=0;}if(k==='preset'){this.presetN=(this.presetN||0)+1;this.preset(this.presetN);}if(k.startsWith('track'))this.edit=Number(k.slice(5));if(k.startsWith('step')){const i=Number(k.slice(4));this.patterns[this.edit][i]=!this.patterns[this.edit][i];}if(k==='save'){const ok=this.api.putData?.('band',this.snapshot());this.say(ok===false?'瀏覽器未能保存，請改用匯出作品。':'作品已保存在本機。');}if(k==='export'){this.api.downloadJSON?.('WordQuest_My_Rhythm.json',this.snapshot());this.say('已匯出節奏資料；可用匯入作品重新開啟。');}if(k==='import')this.api.importJSON?.(v=>{if(!this.valid(v)){this.say('作品格式不正確，沒有改動現有作品。');return;}this.patterns=v.patterns.map(r=>r.slice());this.active=v.active.slice();this.bpm=v.bpm;this.nextAudio=0;this.toolbar();this.say('作品已匯入。');});this.toolbar();}
 act(k){if(k==='action')this.tool('play');}
 pointer(type,p){if(type!=='down')return;const row=Math.floor((p.y-278)/43),col=Math.floor((p.x-210)/31);if(row>=0&&row<5){if(p.x<188){this.active[row]=!this.active[row];this.edit=row;}else if(col>=0&&col<16){this.patterns[row][col]=!this.patterns[row][col];this.edit=row;}this.toolbar();}}
 onResume(){this.nextAudio=0;}
 update(){if(this.playing){const now=this.api.clock();if(!this.nextAudio||this.nextAudio<now-.2)this.nextAudio=now+.035;let safety=0;while(this.nextAudio<now+.075&&safety++<4){const i=this.stepIndex;for(let track=0;track<5;track++)if(this.active[track]&&this.patterns[track][i])this.api.instrument(track,i,this.nextAudio);this.lastStep=i;this.stepIndex=(i+1)%16;if(this.stepIndex===0){this.bars++;this.score=this.bars;}this.nextAudio+=60/this.bpm/4;}}this.stat=`${this.bpm} BPM · ${this.playing?'合奏中':'編曲中'}`;}
 draw(){const c=this.c;D.bg(c,'cream');D.round(c,63,182,674,57,16,'#c4d0ad');for(let i=0;i<5;i++){const x=130+i*134,on=this.active[i],pulse=this.playing&&this.lastStep>=0&&this.patterns[i][this.lastStep];c.globalAlpha=on?1:.4;D.animal(c,x,153,pulse?.83:.78,['rabbit','fox','cat','owl','rabbit'][i],D.palette[i]);D.round(c,x-36,200,72,28,9,on?'#fff3d2':'#d6d9c5');D.text(c,this.names[i],x,214,14,'#586f52');c.globalAlpha=1;}D.badge(c,`森林節奏社 · ${this.bpm} BPM`,400,32);for(let row=0;row<5;row++){D.round(c,90,278+row*43,100,34,9,this.edit===row?'#d1dfb2':'#f1ead7');D.text(c,this.names[row],140,295+row*43,14,'#5b7d5a');for(let col=0;col<16;col++){const on=this.patterns[row][col],x=210+col*31,y=278+row*43;D.round(c,x,y,27,34,6,on?D.palette[row]:(col%4===0?'#dedcc3':'#e9e6d5'),this.lastStep===col&&this.playing?'#4d7657':null);if(col%4===0)D.circle(c,x+13,y+17,2,on?'#ffffffaa':'#b3b996');}}D.text(c,`正在編輯：${this.names[this.edit]}　·　樂句 ${this.bars}`,400,521,14,'#73865e');this.noticeDraw();}
}
registerGame({id:'forest-band',name:'森林節奏社',en:'FOREST BAND',category:'創作',desc:'替五位動物編曲，合奏自己的節奏。',tag:'音樂創作',guide:'按「播放合奏」。每一列是一件樂器，每一格是一拍。點格子開關聲音，或選樂器後用下方 1–16 拍按鈕編曲。可調速度、保存作品，匯出或匯入 JSON 節奏檔。',design:'五聲部 16 步 sequencer、實際合成音訊與音訊時鐘排程。計數是樂句，不評藝術分數。',scoreLabel:'已奏樂句',keys:[['action','播放／停止']]},ForestBand);

class StarRhythm extends WQGame{
 constructor(a){super(a);this.period=60/[90,112,136][this.d];this.window=[.2,.145,.105][this.d];this.total=32;this.index=0;this.hits=0;this.perfect=0;this.combo=0;this.maxCombo=0;this.nextDue=this.period*5;this.hitCurrent=false;this.cue=this.period;this.mark='先聽四拍';this.markTime=2;this.points=Array.from({length:36},(_,i)=>({x:i*88,y:Math.sin(i*.85)*68+Math.cos(i*.45)*25}));this.tools([]);this.hint('先聽 4 拍預備。金球轉到下一個光圈時，按一下空白鍵／拍子。');}
 act(k){if(k!=='action'||this.done)return;const offset=(this.api.latency||0)/1000,err=this.t-this.nextDue-offset;if(this.hitCurrent)return;if(Math.abs(err)>this.window){this.combo=0;this.mark=err<0?'再等一點':'跟下一拍';this.markTime=.45;return;}const grade=WQCore.rhythmGrade(err,this.window);this.hitCurrent=true;this.hits++;this.combo++;this.maxCombo=Math.max(this.maxCombo,this.combo);if(grade==='perfect'){this.perfect++;this.score+=100+Math.min(this.combo,20)*2;this.mark='準拍！';}else{this.score+=65;this.mark='跟上了';}this.sound(grade==='perfect'?880:660,.08,'triangle',.07);this.markTime=.55;}
 pointer(type){if(type==='down')this.act('action');}
 update(dt){this.markTime=Math.max(0,this.markTime-dt);while(this.t>=this.cue){this.sound(this.cue<this.period*4.5?470:330,.045,'sine',.07);this.cue+=this.period;}if((this.hitCurrent&&this.t>=this.nextDue+(this.api.latency||0)/1000)||this.t>this.nextDue+(this.api.latency||0)/1000+this.window){if(!this.hitCurrent){this.combo=0;this.mark='下一拍再來';this.markTime=.5;}this.index++;this.hitCurrent=false;this.nextDue+=this.period;if(this.index>=this.total){this.end(`跟上 ${this.hits} / ${this.total} 拍，其中 ${this.perfect} 拍準拍；最長連續 ${this.maxCombo} 拍。`,'這段旋律完成');return;}}this.stat=`第 ${this.index+1} / ${this.total} 拍 · 連續 ${this.combo}`;}
 draw(){const c=this.c;D.bg(c,'night');for(let i=0;i<38;i++)D.circle(c,(i*137)%800,(i*79)%540,1.4,'#dfebc044');const pivot=this.points[this.index],map=p=>({x:345+p.x-pivot.x,y:288+p.y-pivot.y});const pts=this.points.slice(Math.max(0,this.index-5),this.index+7).map(map);D.line(c,pts,'#92b7a133',5);for(let i=Math.max(0,this.index-4);i<Math.min(this.points.length,this.index+6);i++){const p=map(this.points[i]);D.circle(c,p.x,p.y,14,i<=this.index?'#8cad98':'#355951','#789e86');}const next=map(this.points[this.index+1]),center=map(pivot),dx=next.x-center.x,dy=next.y-center.y,r=Math.hypot(dx,dy),targetA=Math.atan2(dy,dx),phase=(this.t-this.nextDue)/this.period,angle=targetA+phase*Math.PI*2;const orb={x:center.x+Math.cos(angle)*r,y:center.y+Math.sin(angle)*r};D.circle(c,center.x,center.y,r,null,'#a3c1a431');D.line(c,[center,orb],'#e2c07d55',3);D.circle(c,center.x,center.y,18,'#a5c3a1');D.circle(c,orb.x,orb.y,16,'#edc881');D.circle(c,orb.x-4,orb.y-5,5,'#fff4bf');const remaining=this.nextDue-this.t;if(remaining<this.period&&remaining>0)D.circle(c,next.x,next.y,16+remaining/this.period*40,null,'#f3d291');D.badge(c,this.t<this.period*4.2?'跟着預備拍，準備出發':'把光圈，接成一段旋律',400,45,'#f5efdce0');if(this.markTime>0)D.text(c,this.mark,400,435,26,'#f1d599');for(let i=0;i<this.total;i++)D.round(c,105+i*18.5,493,13,9,4,i<this.index?'#abc193':'#48665d');D.text(c,`${this.hits} / ${this.total} 拍`,400,533,14,'#b9cba6');}
}
registerGame({id:'star-rhythm',name:'星軌節拍',en:'STAR RHYTHM',category:'創作',desc:'跟光圈、聽節拍，沿星軌前進。',tag:'一鍵節奏',guide:'先聽四拍預備。金球沿圓軌轉動，當它到下一個光圈時按一下。越接近正拍得分越高；漏拍不會出現傷害動畫。共 32 拍，有三種速度。',design:'實際時間差判分、準拍／一般／漏拍、連續拍數及本機延遲微調。',keys:[['action','拍子']]},StarRhythm);

