'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert').strict;
const {ROOT,sandbox:B,create}=require('./engine_harness.cjs');const {runner,cloud,stairs}=require('./bots.cjs');
const S=B.WQArcadeSnapshot28,C=B.WQArcade28,R=B.WQRewards,ids=Array.from(B.WQR2.ids);const cases=[];
function test(name,fn,group='ENGINE'){let detail=null,pass=true;try{detail=fn()??null}catch(e){pass=false;detail=e.stack}cases.push({id:'CORE-'+String(cases.length+1).padStart(3,'0'),group,name,pass,detail});}
const eq=(a,b)=>assert.equal(JSON.stringify(a),JSON.stringify(b));
const shotInputs=(g,n)=>{if(n%47===0){g.keys.delete('left');g.keys.delete('right');g.key(n%94===0?'left':'right',true)}if(n%101===0)g.key('up',true);if(n%101===28)g.key('up',false);if(n%151===0)g.key('action',true);if(n%151===2)g.key('action',false);if(n%211===0)g.key('down',true);if(n%211===11)g.key('down',false);if(n%311===0)g.key('x',true);};
for(const id of ids)for(let d=0;d<3;d++)for(const seed of [1,12,456,9876,654321]){
 test(`${id} d${d} seed${seed}: bounded snapshots throughout simulated run`,()=>{const g=create(id,d,seed);let ticks=0;for(;ticks<18000&&!g.done;ticks++){shotInputs(g,ticks);g.tick(1/60);if(ticks%30===0)S.capture(g);}S.capture(g);return {ticks,seconds:g.t,done:g.done,won:g.won,health:g.health};});
 test(`${id} d${d} seed${seed}: checkpoint RNG replay`,()=>{const a=create(id,d,seed);for(let n=0;n<75;n++){shotInputs(a,n);a.tick(1/60)}a.keys.clear();const b=create(id,d,22);S.restore(b,S.capture(a));for(let n=75;n<155;n++){shotInputs(a,n);shotInputs(b,n);a.tick(1/60);b.tick(1/60);}eq(S.capture(a),S.capture(b));});
}
for(const id of ids){test(id+': draw is read-only',()=>{const g=create(id);for(let n=0;n<80;n++)g.tick(1/60);const before=S.capture(g);for(let n=0;n<30;n++)g.draw();eq(before,S.capture(g));});
 for(const mode of ['missing','bad-health','huge-array','prototype','unknown-method'])test(id+': reject '+mode,()=>{const s=S.capture(create(id)),st=R.decode(s.state);if(mode==='missing')delete st.engineVersion;if(mode==='bad-health')st.health=-1;if(mode==='huge-array')st.fx=Array(10001).fill(0);if(mode==='prototype')Object.defineProperty(st,'__proto__',{value:{x:1},enumerable:true});if(mode==='unknown-method')st.update='evil';assert.throws(()=>{s.state=R.encode(st);S.verify(s)});},'VALIDATION');
}
// Old engines and stable identifiers are preserved, not converted into R2 scores.
const legacy=C.ids.slice(0,21);test('Catalogue contains 26 unique IDs, with original 21 in original order',()=>{assert.equal(new Set(C.ids).size,26);eq(Array.from(C.ids.slice(21)),ids);assert.equal(C.ids[0],'sky-rescue');assert.equal(C.ids[20],'sweet-studio');},'COMPATIBILITY');
for(const id of legacy)for(let d=0;d<3;d++)test(`${id} d${d}: original snapshot constructor roundtrip`,()=>{const a=create(id,d,69),s=S.capture(a),b=create(id,d,12);S.restore(b,s);eq(s,S.capture(b));},'COMPATIBILITY');
for(let d=0;d<3;d++)for(const seed of [12,456]){
 test(`runner lane changes alone cannot finish d${d} seed${seed}`,()=>{const g=create(ids[0],d,seed);for(let n=0;n<6000&&!g.done;n++){if(n%31===0)g.act(n%62===0?'left':'right');g.tick(1/60);}assert(g.done&&!g.won);assert.equal(g.actions.jump,0);assert.equal(g.actions.slide,0);return {metres:g.distance};},'GAMEPLAY');
 test(`runner jump-slide route completes d${d} seed${seed}`,()=>{const g=create(ids[0],d,seed);for(let n=0;n<6000&&!g.done;n++){runner(g,n);g.tick(1/60);}assert(g.won);assert(g.actions.jump>2&&g.actions.slide>2);S.capture(g);return {seconds:g.t,health:g.health};},'GAMEPLAY');
 test(`cloud controlled jumps complete three islands d${d} seed${seed}`,()=>{const g=create(ids[1],d,seed);for(let n=0;n<18000&&!g.done;n++){cloud(g,n);g.tick(1/60);}assert(g.won);S.capture(g);return {seconds:g.t,health:g.health};},'GAMEPLAY');
}
for(let d=0;d<3;d++)test(`well 60-floor controlled route d${d}, seed456`,()=>{const g=create(ids[3],d,456);for(let n=0;n<20000&&!g.done;n++){stairs(g,n);g.tick(1/60);if(n%60===0)S.capture(g);}assert(g.won);return {seconds:g.t,health:g.health,floor:g.floor};},'GAMEPLAY');
for(const id of ['cloud-island','lighthouse-well'])test(id+': repeated fall during invulnerability returns to safe position without extra damage',()=>{const g=create(id);g.inv=1.5;const hp=g.health;for(let i=0;i<4;i++){g.p.y=(g.camera||0)+900;g.tick(1/60);assert.equal(g.health,hp);assert(g.p.y-(g.camera||0)<600);S.capture(g);}assert(g.inv<1.5);},'REGRESSION');
test('cloud initial damage produces safe checkpoint and 2.2 seconds protection',()=>{const g=create(ids[1]);g.damage('fixture');assert.equal(g.health,2);for(let i=0;i<100;i++)g.tick(1/60);assert.equal(g.health,2);assert(Math.abs(g.p.y-438)<1);S.capture(g);},'REGRESSION');
test('cloud releasing one jump key retains the other held key',()=>{const g=create(ids[1]);g.key('up',true);g.key('action',true);g.key('action',false);assert(g.jumpHeld);g.key('up',false);assert(!g.jumpHeld);},'REGRESSION');
test('cloud reject dangerous checkpoint height',()=>{const s=S.capture(create(ids[1]));const st=R.decode(s.state);st.checkpoint.y=620;s.state=R.encode(st);assert.throws(()=>S.verify(s));},'VALIDATION');
test('cloud island change preserves lost lives and varies platform layout',()=>{const g=create(ids[1]);const original=g.platforms.map(p=>[p.x,p.kind]);g.health=2;g.level=2;g.build();assert.equal(g.health,2);assert.notEqual(JSON.stringify(original),JSON.stringify(g.platforms.map(p=>[p.x,p.kind])));},'GAMEPLAY');
test('shooter power-up changes projectile damage',()=>{const a=create(ids[2]),b=create(ids[2]);b.power=3;a.tick(1/60);b.tick(1/60);assert(b.shots[0].power>a.shots[0].power);},'GAMEPLAY');
test('shooter diagonal velocity is not faster',()=>{const a=create(ids[2]),b=create(ids[2]);a.keys.add('right');b.keys.add('right');b.keys.add('up');a.tick(.05);b.tick(.05);assert(Math.abs(a.p.x-400-Math.hypot(b.p.x-400,b.p.y-452))<.00001);},'GAMEPLAY');
test('shooter precise movement slower than normal',()=>{const a=create(ids[2]),b=create(ids[2]);a.keys.add('right');b.keys.add('right');b.keys.add('hold');a.tick(.05);b.tick(.05);assert(b.p.x<a.p.x);},'GAMEPLAY');
test('shooter shield clears bullets and has cooldown',()=>{const g=create(ids[2]);g.orbs.push({x:400,y:452,vx:0,vy:10});g.act('action');assert.equal(g.orbs.length,0);g.tick(.05);assert.equal(g.health,3);const n=g.shieldCD;g.act('action');assert.equal(g.shieldCD,n);S.capture(g);},'GAMEPLAY');
test('shooter half-health boss changes fan from five to seven',()=>{for(const [hp,count] of [[160,5],[70,7]]){const g=create(ids[2]);g.wave=6;g.waveClock=20;g.boss={x:400,y:115,hp,max:160,age:0,fire:0};g.tick(1/60);assert.equal(g.orbs.length,count);S.capture(g);}},'GAMEPLAY');
test('shooter each boss advances and third completes without restoring health',()=>{const g=create(ids[2]);g.health=2;for(let i=0;i<3;i++){g.boss={x:400,y:115,hp:0,max:150,age:0,fire:10};g.tick(1/60);assert.equal(g.health,2);S.capture(g);}assert(g.won&&g.done&&g.bosses===3);},'GAMEPLAY');
test('volleyball fourth touch awards one point; terminal state remains valid',()=>{const g=create(ids[4]);g.points=[0,4];g.touches=[3,0];g.servePause=0;g.ball={x:g.p.x,y:g.p.y-30,vx:0,vy:10};g.strike(g.p,0);assert(g.done&&!g.won&&g.points[1]===5);S.capture(g);},'REGRESSION');
test('volleyball deuce needs two-point lead, capped at seven',()=>{const g=create(ids[4]);g.points=[4,4];g.point(0,'fixture');assert(!g.done);g.point(1,'fixture');assert(!g.done);g.point(0,'fixture');assert(!g.done);g.point(1,'fixture');assert(!g.done);g.point(0,'fixture');assert(g.done&&g.won);assert.equal(g.points[0],7);S.capture(g);},'GAMEPLAY');
test('volleyball lob, short and airborne spike produce different trajectories',()=>{const vs=[];for(const mode of ['lob','short','spike']){const g=create(ids[4]);g.servePause=0;g.p.x=300;g.p.y=mode==='spike'?300:453;g.ball={x:310,y:g.p.y-30,vx:0,vy:50};if(mode==='short')g.keys.add('down');g.strike(g.p,0,mode!=='lob');vs.push([g.ball.vx,g.ball.vy]);}assert.equal(new Set(vs.map(JSON.stringify)).size,3);assert(vs[2][1]>0);},'GAMEPLAY');
test('volleyball swept net blocks fast low shot',()=>{const g=create(ids[4]);g.servePause=0;g.ball={x:382,y:360,vx:600,vy:0};g.tick(1/60);assert(g.ball.x<400&&g.ball.vx<0);},'GAMEPLAY');
// Wallet invariants, using explicitly synthetic balances and metadata.
test('R1 balance migration remains idempotent',()=>{const db={children:[{id:'a',stars:19}]};C.migrate(db,100);const once=JSON.stringify(db);C.migrate(db,200);assert.equal(JSON.stringify(db),once);assert.equal(db.children[0].stars,19);},'WALLET');
for(const id of ids)test(id+': one coin, pause/resume no charge, no duplicate receipt',()=>{const c=C.child();let bal=C.purchase(c,10,{id:'admit',game:id,qualified:99,seed:123,now:100});assert.equal(bal,9);assert.throws(()=>C.purchase(c,bal,{id:'admit',game:id,qualified:99,now:110}));C.start(c);C.pause(c);C.start(c);assert.equal(c.ledger.filter(x=>x.kind==='spend').length,1);assert.throws(()=>C.refund(c,bal,'admit',120));},'WALLET');
test('untouched admission refundable once only',()=>{const c=C.child();let bal=C.purchase(c,2,{id:'admit',game:ids[0],qualified:99,now:100});bal=C.refund(c,bal,'admit',110);assert.equal(bal,2);assert.equal(c.batch.used,0);assert.throws(()=>C.refund(c,bal,'admit',120));},'WALLET');
test('sixth admission blocked at batch five, no negative balance',()=>{const c=C.child();let bal=8;for(let i=0;i<5;i++){bal=C.purchase(c,bal,{id:'r'+i,game:ids[i],qualified:99,now:100+i});C.close(c);}assert.equal(bal,3);assert.throws(()=>C.purchase(c,bal,{id:'r6',game:ids[0],qualified:99,now:110}));assert.equal(c.batch.used,5);},'WALLET');
test('all 78 best-score slots validated and old values kept',()=>{const root=C.initial([{id:'a'}]);for(const id of C.ids)for(let d=0;d<3;d++)root.children.a.bests[id+'|'+d]=777;const out=C.validate(root,[{id:'a'}],S.verify);assert.equal(Object.keys(out.children.a.bests).length,78);assert.equal(out.children.a.bests['forest-dash|1'],777);},'WALLET');
test('damaged new snapshot isolated without deleting other records',()=>{const root=C.initial([{id:'a'}]),c=root.children.a;C.purchase(c,5,{id:'r1',game:ids[0],qualified:99,now:100});c.bests['forest-dash|1']=987;c.run.snapshot=S.capture(create(ids[0],1));const st=R.decode(c.run.snapshot.state);st.health=-5;c.run.snapshot.state=R.encode(st);const out=C.validate(root,[{id:'a'}],S.verify);assert.equal(out.children.a.run.phase,'error');assert.equal(out.children.a.bests['forest-dash|1'],987);},'WALLET');
test('unknown V33 game ID is rejected rather than guessed',()=>{const s=S.capture(create(ids[0]));s.id='unknown-v33-game';assert.throws(()=>S.verify(s));},'COMPATIBILITY');
fs.writeFileSync(path.join(ROOT,'arcade_evidence/core_results.json'),JSON.stringify(cases,null,2));const fail=cases.filter(c=>!c.pass);console.log('TOTAL',cases.length,'PASS',cases.length-fail.length,'FAIL',fail.length);for(const f of fail)console.log(f.name,f.detail);process.exitCode=fail.length?1:0;
