/* Standalone native-only device check. This file NEVER touches application accounts,
 * family databases, game saves, or credentials. It uses its own namespace exclusively.
 * No polyfills/adapters: unavailable APIs produce BLOCKED, never a simulated PASS. */
(function(){'use strict';
 const PREFIX='wq-r32-device-check:',KEY=PREFIX+'probe',RESULT=PREFIX+'result',DB='wq-r32-device-check-db',STORE='probes',LOCK=PREFIX+'exclusive';
 const $=s=>document.querySelector(s);let current={format:'wordquest-native-device-check',version:'3.2.0',startedAt:new Date().toISOString(),results:[],manual:[],limits:['API probe only: not a complete application migration/restore or commercial-readiness certification.']},busy=false;
 const err=e=>String(e?.message||e).slice(0,500);
 function show(){const out=$('#results');out.replaceChildren();for(const r of current.results){const row=document.createElement('tr');for(const v of [r.name,{pass:'通過',fail:'失敗',blocked:'未能執行',pending:'等待驗證'}[r.status]||r.status,r.detail||'']){const td=document.createElement('td');td.textContent=v;row.append(td);}out.append(row);}$('#summary').textContent=`${current.results.filter(x=>x.status==='pass').length} 項通過；${current.results.filter(x=>x.status==='fail').length} 項失敗；${current.results.filter(x=>x.status==='blocked').length} 項未能執行。未執行的項目不算通過。`;}
 function row(id,name,status,detail=''){current.results=current.results.filter(r=>r.id!==id);current.results.push({id,name,status,detail,at:new Date().toISOString()});show();try{localStorage.setItem(RESULT,JSON.stringify(current));}catch(_){} }
 async function test(id,name,fn){try{const info=await fn();row(id,name,'pass',String(info||''));return true;}catch(e){row(id,name,e?.name==='NotSupportedError'||e?.name==='SecurityError'?'blocked':'fail',err(e));return false;}}
 const unsupported=s=>{throw new DOMException(s,'NotSupportedError');};
 async function sha(text){if(!isSecureContext||!crypto.subtle)unsupported('需要 HTTPS 或本機啟動網址，以及原生 WebCrypto。');return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
 async function db(){if(!indexedDB)unsupported('此瀏覽器沒有原生 IndexedDB。');return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('本機驗收資料庫被其他分頁佔用。'));r.onsuccess=()=>{r.result.onversionchange=()=>r.result.close();resolve(r.result);};});}
 async function tx(mode,key,value){const d=await db();try{return await new Promise((resolve,reject)=>{const t=d.transaction(STORE,mode==='put'?'readwrite':'readonly'),s=t.objectStore(STORE);const r=mode==='put'?s.put(value,key):s.get(key);let result;r.onsuccess=()=>result=r.result;t.oncomplete=()=>resolve(result);t.onabort=()=>reject(t.error||Error('IndexedDB transaction aborted'));t.onerror=()=>{};});}finally{d.close();}}
 async function begin(){if(busy)return;busy=true;$('#start').disabled=true;
 try{current={...current,startedAt:new Date().toISOString(),results:[],manual:[],environment:{userAgent:navigator.userAgent,origin:location.origin,secureContext:isSecureContext}};
  const ok=await test('crypto','原生 SHA-256',async()=>{if(await sha('abc')!=='ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad')throw Error('SHA-256結果不符');return '標準向量相符；沒有使用替身。';});
  let probe;if(ok){const values=crypto.getRandomValues(new Uint32Array(4));const token=[...values].map(n=>n.toString(16).padStart(8,'0')).join('');probe={token,createdAt:new Date().toISOString(),text:'WordQuest 測試記號，不含學員資料',digest:await sha(token),initialSession:token};}
  await test('local','原生 localStorage 寫入及讀回',()=>{if(!probe)unsupported('未能產生原生校驗測試記號。');const text=JSON.stringify(probe);localStorage.setItem(KEY,text);if(localStorage.getItem(KEY)!==text)throw Error('寫入後讀回不一致');sessionStorage.setItem(PREFIX+'session',probe.token);return '僅寫入專用測試記號，沒有讀取學員資料。';});
  await test('idb','原生 IndexedDB Blob 交易',async()=>{if(!probe)unsupported('沒有測試記號。');await tx('put','checkpoint',{token:probe.token,blob:new Blob([probe.text],{type:'text/plain'})});const read=await tx('get','checkpoint');if(read?.token!==probe.token||!(read.blob instanceof Blob)||await read.blob.text()!==probe.text)throw Error('Blob交易讀回不一致');return '完成交易後才核對讀回；沒有使用記憶體替身。';});
  await test('locks','原生 Web Locks 互斥及釋放',async()=>{if(!navigator.locks||!isSecureContext)unsupported('需要支援 Web Locks 的安全網址環境。');let denied=false;await navigator.locks.request(LOCK,{ifAvailable:true},async lock=>{if(!lock)throw Error('另一驗收分頁已佔用此測試鎖');await navigator.locks.request(LOCK,{ifAvailable:true},second=>{denied=second===null;});});if(!denied)throw Error('互斥測試不符');let reacquired=false;await navigator.locks.request(LOCK,{ifAvailable:true},lock=>{reacquired=!!lock;});if(!reacquired)throw Error('釋放後不能再次取得鎖');return '同頁互斥已核對；真正雙分頁測試另列，不混為一項。';});
  row('reload','重新載入後資料核對','pending','完成後按「重新載入驗證」，不等於完整關閉瀏覽器。');
  row('reopen','關閉瀏覽器後資料核對','pending','先保留本頁網址，關閉整個瀏覽器，再開啟同一網址及按「核對上次記號」。是否完全關閉屬使用者確認。');
  $('#notice').textContent=current.results.some(x=>x.id==='local'&&x.status==='pass')?'測試記號已準備。下面會分開記錄 API、重新載入、跨分頁，以及你確認的關閉重開。':'尚未成功建立測試記號；請使用本機啟動網址或 HTTPS，不會將缺少 API 算作通過。';
 }finally{busy=false;$('#start').disabled=false;}}
 async function verify(){if(busy)return;busy=true;try{const raw=localStorage.getItem(KEY);if(!raw)throw Error('找不到測試記號。可能尚未開始、網址不同、使用私人視窗或資料已被清除。');const v=JSON.parse(raw);
  const verified=await test('persistent-read','上次原生儲存記號完整性',async()=>{if(await sha(v.token)!==v.digest)throw Error('localStorage校驗不符');const old=await tx('get','checkpoint');if(old?.token!==v.token||await old.blob.text()!==v.text)throw Error('IndexedDB與localStorage記號不一致');return '兩個原生儲存的上次記號均相符。';});
  if(!verified){current.results=current.results.filter(x=>!['reload','reopen'].includes(x.id));row('reload','重新載入後資料核對','pending','最新完整性核對未通過，之前的重新載入／人工重開結果已失效。');}
  const nav=performance.getEntriesByType('navigation')[0];if(verified&&nav?.type==='reload')row('reload','重新載入後資料核對','pass','瀏覽器導覽類型為reload，且上次兩種記號相符。這不是完全關閉重開證據。');
  const lostSession=sessionStorage.getItem(PREFIX+'session')!==v.token;$('#session-note').textContent=lostSession?'這個分頁沒有最初的session記號；可能是新分頁或新工作階段，不能單憑此推斷整個瀏覽器曾關閉。':'仍有最初的session記號；部分瀏覽器還原視窗亦可能保留它，不能據此推斷未關閉。';
 }catch(e){current.results=current.results.filter(x=>!['reload','reopen'].includes(x.id));row('persistent-read','上次原生儲存記號完整性',e.name==='SecurityError'?'blocked':'fail',err(e));}finally{busy=false;}}
 async function compete(){if(busy)return;if(!navigator.locks||!window.BroadcastChannel||!crypto.randomUUID||!isSecureContext){row('two-tabs','原生雙分頁互斥','blocked','缺少安全網址、原生Web Locks、BroadcastChannel或randomUUID。');return;}
  const nonce=crypto.randomUUID(),name=PREFIX+'channel:'+nonce,bc=new BroadcastChannel(name);let child,release,timer;busy=true;
  try{await new Promise((resolve,reject)=>{timer=setTimeout(()=>reject(Error('未收到第二分頁結果；請允許本機頁面開啟分頁，再重試。')),18000);
   navigator.locks.request(LOCK,{ifAvailable:true},async lock=>{if(!lock){reject(Error('測試鎖已被其他驗收佔用'));return;}
    let resolveHold;const hold=new Promise(r=>resolveHold=r);release=resolveHold;
    bc.onmessage=e=>{if(e.data?.nonce!==nonce)return;if(e.data.type==='compete-result'){if(e.data.denied){row('two-tabs','原生雙分頁互斥','pass','第二分頁以ifAvailable請求同一測試鎖，確實被拒絕。');resolve();}else reject(Object.assign(Error('第二分頁意外取得獨佔鎖'),{verificationFailed:true}));resolveHold();}};
    const u=new URL(location.href);u.hash='';u.search='?peer='+encodeURIComponent(nonce);child=window.open(u.href,'_blank');if(!child){reject(Error('瀏覽器封鎖新分頁'));resolveHold();}await hold;
   }).catch(reject);
  });}catch(e){row('two-tabs','原生雙分頁互斥',e.verificationFailed?'fail':'blocked',err(e));}finally{clearTimeout(timer);release?.();bc.close();busy=false;}}
 async function peer(nonce){document.body.classList.add('peer');$('#notice').textContent='第二分頁只請求專用測試鎖；不接觸任何家庭資料。';if(!/^[a-f0-9-]{36}$/.test(nonce)||!navigator.locks||!window.BroadcastChannel){$('#notice').textContent='分頁驗收參數或原生API不可用。';return;}const bc=new BroadcastChannel(PREFIX+'channel:'+nonce);await navigator.locks.request(LOCK,{ifAvailable:true},lock=>{bc.postMessage({nonce,type:'compete-result',denied:lock===null});$('#notice').textContent=lock===null?'已確認另一驗收分頁持有測試鎖，這一頁不能同時取得。可以關閉此頁。':'這一頁取得了鎖；第一分頁可能未持有，請重新測試。';});setTimeout(()=>bc.close(),300);}
 $('#start').onclick=begin;$('#verify').onclick=verify;$('#reload').onclick=()=>{try{if(!localStorage.getItem(KEY))throw Error('先建立測試記號。');location.reload();}catch(e){$('#notice').textContent=err(e);}};
 $('#compete').onclick=compete;
 $('#confirm-reopen').onclick=()=>{if(!$('#closed-browser').checked){$('#notice').textContent='請先完成關閉、重開及核對，再作人工確認。';return;}if(!current.results.some(x=>x.id==='persistent-read'&&x.status==='pass')){$('#notice').textContent='先按「核對上次記號」，確認資料仍在。';return;}current.manual.push({type:'user-attested-browser-close-and-reopen',at:new Date().toISOString()});row('reopen','關閉瀏覽器後資料核對','pass','使用者確認曾完全關閉再開；本程式核對記號仍在。這項含人工確認，並非自動證明瀏覽器程序已終止。');};
 $('#download').onclick=()=>{const b=new Blob([JSON.stringify(current,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='WordQuest_Native_Device_R32.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);};
 $('#clear').onclick=async()=>{if(busy)return;try{localStorage.removeItem(KEY);localStorage.removeItem(RESULT);sessionStorage.removeItem(PREFIX+'session');await new Promise((resolve,reject)=>{const r=indexedDB.deleteDatabase(DB);r.onsuccess=resolve;r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('請先關閉第二驗收分頁'));});current.results=[];current.manual=[];show();$('#notice').textContent='只清除了驗收測試記號，沒有讀取或刪除學員紀錄。';}catch(e){$('#notice').textContent=err(e);}};
 try{const prior=localStorage.getItem(RESULT);if(prior){const parsed=JSON.parse(prior);if(parsed?.format===current.format&&Array.isArray(parsed.results)&&parsed.results.length<30)current=parsed;}}catch(_){}
 show();const nonce=new URL(location.href).searchParams.get('peer');if(nonce)peer(nonce);else if(performance.getEntriesByType('navigation')[0]?.type==='reload')verify();
})();
