/** Handler/unit tests. No socket, Azure key, billable request, real voice or live provider is used. */
import {makeServer,speechBody} from '../server/local_server.mjs';import {Readable} from 'node:stream';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),rows=[];
async function test(name,fn){try{await fn();rows.push({name,pass:true});}catch(e){rows.push({name,pass:false,error:e.stack});}}
const good={text:'三角形 < 直角 & "參考"。',lang:'yue-HK',voice:'zh-HK-HiuMaanNeural',slow:false};
for(const [name,v] of [['empty',{}],['empty text',{...good,text:''}],['long',{...good,text:'x'.repeat(1201)}],['voice injection',{...good,voice:'"/><script>'}],['language mismatch',{...good,lang:'en-GB'}],['rate type',{...good,slow:0}],['unknown language',{...good,lang:'zz'}]])await test('reject '+name,()=>assert.throws(()=>speechBody(v)));
await test('SSML escapes text not markup',()=>{const s=speechBody(good);assert(s.includes('&lt;'));assert(s.includes('&amp;'));assert(!s.includes('< 直角'));});
await test('English selected voice and language',()=>assert(speechBody({...good,voice:'en-GB-SoniaNeural',lang:'en-GB'}).includes('xml:lang="en-GB"')));
await test('Slow option becomes controlled prosody not arbitrary SSML',()=>assert(speechBody({...good,slow:true}).includes('rate="-20%"')));
const temp=await fs.mkdtemp(path.join(os.tmpdir(),'wordquest-server-'));await fs.writeFile(path.join(temp,'index.html'),'<p>static fixture</p>');await fs.writeFile(path.join(temp,'core.wasm'),Buffer.from([0,97,115,109]));
let calls=[];const fetcher=async(url,opts)=>{calls.push({url,opts});return {ok:true,arrayBuffer:async()=>new Uint8Array([1,2,3]).buffer};};
const server=makeServer({key:'SYNTHETIC-NOT-A-REAL-KEY',region:'eastasia',fetcher,app:temp});
async function request(s,opts={}){return new Promise((resolve,reject)=>{const data=opts.raw??Buffer.from(JSON.stringify(opts.body??good));const input=opts.chunks??[data];const req=Readable.from(input);req.url=opts.url??'/api/speech';req.method=opts.method??'POST';req.socket={localPort:8765};req.headers={host:'127.0.0.1:8765',origin:'http://127.0.0.1:8765','x-wordquest-speech':'1','content-type':'application/json',...opts.headers};const res={headersSent:false,writeHead(code,headers){this.code=code;this.headers=headers;this.headersSent=true;},end(body){resolve({code:this.code,headers:this.headers,body:body??''});}};Promise.resolve(s.listeners('request')[0](req,res)).catch(reject);});}
for(const [name,opts,code]of[['unconfigured',{},503],['invalid host',{headers:{host:'evil.example'}},403],['cross origin',{headers:{origin:'https://evil.example'}},403],['missing request header',{headers:{'x-wordquest-speech':undefined}},403],['wrong content type',{headers:{'content-type':'text/plain'}},403],['wrong method',{method:'GET'},405]])await test('API '+name,async()=>{const srv=name==='unconfigured'?makeServer({app:temp}):server;const r=await request(srv,opts);assert.equal(r.code,code);assert(!String(r.body).includes('SYNTHETIC-NOT-A-REAL-KEY'));});
await test('Malformed JSON returns 400',async()=>assert.equal((await request(server,{raw:Buffer.from('{')})).code,400));
await test('Oversized request bounded to 10KB',async()=>assert.equal((await request(server,{raw:Buffer.alloc(10001,120)})).code,413));
await test('UTF8 multi-byte characters split across chunks remain intact',async()=>{const bytes=Buffer.from(JSON.stringify(good)),chunks=[...bytes].map(x=>Buffer.from([x]));const r=await request(server,{chunks});assert.equal(r.code,200);assert.equal(calls.at(-1).opts.body,speechBody(good));});
await test('Provider hostname built from validated region and HTTPS',async()=>{await request(server);assert.equal(calls.at(-1).url,'https://eastasia.tts.speech.microsoft.com/cognitiveservices/v1');assert.equal(calls.at(-1).opts.headers['Ocp-Apim-Subscription-Key'],'SYNTHETIC-NOT-A-REAL-KEY');});
await test('Audio response is no-store; provider key is not echoed',async()=>{const r=await request(server);assert.equal(r.headers['Cache-Control'],'no-store');assert.equal(r.headers['Content-Type'],'audio/mpeg');assert.equal(r.body.length,3);});
for(const [name,provider]of[['failure',async()=>({ok:false})],['exception',async()=>{throw Error('SYNTHETIC-NOT-A-REAL-KEY');}],['empty audio',async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(0)})],['large audio',async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(6000001)})]])await test('Provider '+name+' returns sanitized error',async()=>{const r=await request(makeServer({key:'fixture',region:'eastasia',app:temp,fetcher:provider}));assert.equal(r.code,502);assert(!String(r.body).includes('SYNTHETIC-NOT-A-REAL-KEY'));});
await test('Bad region cannot choose arbitrary provider URL',async()=>assert.equal((await request(makeServer({key:'fixture',region:'bad/x',fetcher,app:temp}))).code,503));
for(const[uri,status]of[['/',200],['/index.html',200],['/unknown',404],['/%2e%2e%2fserver/local_server.mjs',403],['/%00',403],['/%5csecret',403],['/.env',403],['/%GG',400]])await test('Static route '+uri,async()=>{const r=await request(server,{url:uri,method:'GET'});assert.equal(r.code,status);});
await test('WASM proper content type and HEAD no body',async()=>{const r=await request(server,{url:'/core.wasm',method:'HEAD'});assert.equal(r.code,200);assert.equal(r.headers['Content-Type'],'application/wasm');assert.equal(r.body,'');});
const outside=path.join(os.tmpdir(),'wq-outside-'+process.pid);await fs.writeFile(outside,'private fixture');await fs.symlink(outside,path.join(temp,'symlink.txt'));await test('Symlink cannot serve outside application directory',async()=>assert.equal((await request(server,{url:'/symlink.txt',method:'GET'})).code,403));await fs.unlink(outside);
await test('Rate limit denies 61st local speech request',async()=>{const srv=makeServer({key:'fixture',region:'eastasia',fetcher,app:temp});for(let i=0;i<60;i++)assert.equal((await request(srv)).code,200);assert.equal((await request(srv)).code,429);});
await fs.rm(temp,{recursive:true,force:true});await fs.writeFile(path.join(ROOT,'r3_evidence/server_contracts.json'),JSON.stringify({scope:'real request handler + real filesystem; mocked upstream speech/no network/no real audio',tests:rows},null,2));console.log('TOTAL',rows.length,'PASS',rows.filter(x=>x.pass).length);for(const r of rows.filter(x=>!x.pass))console.log(r.name,r.error);process.exitCode=rows.some(x=>!x.pass)?1:0;
