/** Optional local-only server. Node 20+ built-ins; key remains in server environment.
 * Not a public multi-tenant production service. Never bind to 0.0.0.0 unchanged.
 */
import http from 'node:http';import zlib from 'node:zlib';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
const APP=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../app');
const VOICES={'zh-HK-HiuMaanNeural':'zh-HK','zh-HK-WanLungNeural':'zh-HK','zh-HK-HiuGaaiNeural':'zh-HK','en-GB-SoniaNeural':'en-GB','zh-CN-XiaoxiaoNeural':'zh-CN'};
const xml=s=>s.replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
export function speechBody(v){if(!v||typeof v.text!=='string'||!v.text.trim()||v.text.length>1200||!VOICES[v.voice]||!['yue-HK','zh-HK','en-GB','zh-CN'].includes(v.lang)||typeof v.slow!=='boolean')throw Error('Invalid speech request');const lang=VOICES[v.voice];if((v.lang==='yue-HK'?'zh-HK':v.lang)!==lang)throw Error('Voice language mismatch');return `<speak version="1.0" xml:lang="${lang}"><voice name="${v.voice}"><prosody rate="${v.slow?'-20%':'-10%'}">${xml(v.text)}</prosody></voice></speak>`;}
// R3.3 p30: bounded body reader. Resolves a Buffer; rejects {status:413|408|499}. Keeps draining after a reject.
function readBody(req,limit,ms){return new Promise((resolve,reject)=>{const chunks=[];let bytes=0,done=false;const fin=(err,val)=>{if(done)return;done=true;clearTimeout(timer);req.off('data',onData);req.off('end',onEnd);req.off('close',onClose);req.off('error',onErr);err?reject(err):resolve(val);};
 const onData=part=>{bytes+=part.length;if(bytes>limit)return fin(Object.assign(Error('Body too large'),{status:413}));chunks.push(Buffer.from(part));};const onEnd=()=>fin(null,Buffer.concat(chunks));const onClose=()=>fin(Object.assign(Error('Request closed'),{status:499}));const onErr=e=>fin(Object.assign(e||Error('Request error'),{status:499}));
 const timer=setTimeout(()=>fin(Object.assign(Error('Body timeout'),{status:408})),ms);req.on('data',onData);req.on('end',onEnd);req.on('close',onClose);req.on('error',onErr);});}
// R3.3 p30: static-file compression helpers.
const ZTYPES=/^(text\/html|text\/javascript|application\/json|image\/svg\+xml|application\/manifest\+json)\b/,ZMIN=1024,ZMAXFILE=67108864,ZCAP=100663296;
function pickEncoding(header,type,size){if(!header||size<ZMIN||size>ZMAXFILE||!ZTYPES.test(type))return '';const q=new Map();for(const part of String(header).split(',')){const [name,...ps]=part.trim().toLowerCase().split(';');const n=name.trim();if(!n)continue;let v=1;for(const p of ps){const m=/^\s*q\s*=\s*([0-9.]+)\s*$/.exec(p);if(m)v=Number(m[1]);}q.set(n,Number.isFinite(v)?v:0);}const get=e=>q.has(e)?q.get(e):(q.has('*')?q.get('*'):0),b=get('br'),g=get('gzip');if(b<=0&&g<=0)return '';return b>=g?'br':'gzip';}
function etagMatches(header,etag){if(!header)return false;return String(header).split(',').some(t=>{t=t.trim();return t==='*'||t.replace(/^W\//,'')===etag;});}
export function makeServer({key=process.env.AZURE_SPEECH_KEY,region=process.env.AZURE_SPEECH_REGION,fetcher=fetch,app=APP,bodyTimeoutMs=10000,prewarm=false}={}){let active=0,hits=[],zc=new Map(),zbytes=0;
 const sigOf=st=>st.size.toString(36)+'-'+Math.floor(st.mtimeMs).toString(36)+'-'+Math.floor(st.ctimeMs).toString(36);
 const zget=(real,sig,enc)=>{const k=real+'\0'+enc,old=zc.get(k);if(old&&old.sig===sig)return old.p;if(old){zc.delete(k);zbytes-=old.size;}const ent={sig,size:0,p:null};ent.p=(async()=>{const raw=await fs.readFile(real);const out=await new Promise((ok,bad)=>{const cb=(e,b)=>e?bad(e):ok(b);if(enc==='br')zlib.brotliCompress(raw,{params:{[zlib.constants.BROTLI_PARAM_QUALITY]:6,[zlib.constants.BROTLI_PARAM_SIZE_HINT]:raw.length}},cb);else zlib.gzip(raw,{level:6},cb);});if(zc.get(k)===ent){ent.size=out.length;zbytes+=out.length;for(const [k2,e2] of zc){if(zbytes<=ZCAP)break;if(k2!==k&&e2.size){zc.delete(k2);zbytes-=e2.size;}}}return out;})();ent.p.catch(()=>{if(zc.get(k)===ent)zc.delete(k);});zc.set(k,ent);return ent.p;};
 const send=(res,code,data,type='application/json',extra={})=>{res.writeHead(code,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer',...extra});res.end(type==='application/json'?JSON.stringify(data):data);};
 const server=http.createServer(async(req,res)=>{try{const port=req.socket.localPort,allowed=new Set(['127.0.0.1:'+port,'localhost:'+port]);if(!allowed.has(req.headers.host))return send(res,403,{error:'Invalid local host'});const u=new URL(req.url,'http://'+req.headers.host);
 if(u.pathname==='/api/speech'){if(req.method!=='POST')return send(res,405,{error:'POST required'});if(req.headers.origin!=='http://'+req.headers.host||req.headers['x-wordquest-speech']!=='1'||req.headers['content-type']?.split(';')[0]!=='application/json')return send(res,403,{error:'Same-origin JSON request required'});if(!key||!region||!/^[a-z0-9-]{3,30}$/.test(region))return send(res,503,{error:'Speech service not configured'});const now=Date.now();hits=hits.filter(t=>t>now-600000);if(hits.length>=60||active>=2)return send(res,429,{error:'Local speech limit reached'});
 // R3.3 p30: claim the slot synchronously (no await since the check), before any body byte is read.
 active++;hits.push(now);let freed=false,refunded=false;const free=()=>{if(!freed){freed=true;active--;}},refund=()=>{if(!refunded){refunded=true;const i=hits.indexOf(now);if(i>=0)hits.splice(i,1);}};const ac=new AbortController();if(typeof res.on==='function')res.on('close',()=>ac.abort());
 try{let raw;try{raw=await readBody(req,10000,bodyTimeoutMs);}catch(e){refund();if(e&&e.status===413)return send(res,413,{error:'Body too large'},undefined,{Connection:'close'});if(e&&e.status===408)return send(res,408,{error:'Request body timeout'},undefined,{Connection:'close'});return;}
 let ssml;try{ssml=speechBody(JSON.parse(raw.toString('utf8')));}catch(_){refund();return send(res,400,{error:'Invalid speech request'});}
 const timer=setTimeout(()=>ac.abort(),18000);try{const upstream=await fetcher('https://'+region+'.tts.speech.microsoft.com/cognitiveservices/v1',{method:'POST',headers:{'Ocp-Apim-Subscription-Key':key,'Content-Type':'application/ssml+xml','X-Microsoft-OutputFormat':'audio-24khz-48kbitrate-mono-mp3','User-Agent':'WordQuest-R3'},body:ssml,signal:ac.signal});if(!upstream.ok)return send(res,502,{error:'Speech provider failed'});const b=Buffer.from(await upstream.arrayBuffer());if(!b.length||b.length>6000000)return send(res,502,{error:'Invalid speech response size'});return send(res,200,b,'audio/mpeg');}catch(_){return send(res,502,{error:'Speech provider unavailable'});}finally{clearTimeout(timer);}}finally{free();}}
 if(!['GET','HEAD'].includes(req.method))return send(res,405,{error:'Method not allowed'});let rel;try{rel=decodeURIComponent(u.pathname);}catch(_){return send(res,400,{error:'Invalid path'});}if(rel.includes('\0')||rel.includes('\\')||rel.split('/').some(p=>p.startsWith('.')))return send(res,403,{error:'Path refused'});if(rel==='/app'||rel==='/app/')rel='/index.html';else if(rel.startsWith('/app/'))rel=rel.slice(4);const target=path.resolve(app,'.'+(rel==='/'?'/index.html':rel));if(!target.startsWith(app+path.sep))return send(res,403,{error:'Path refused'});let real;try{real=await fs.realpath(target);}catch(_){return send(res,404,{error:'File not found'});}if(!real.startsWith(app+path.sep))return send(res,403,{error:'Path refused'});const stat=await fs.stat(real);if(!stat.isFile())return send(res,404,{error:'File not found'});const type={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.webmanifest':'application/manifest+json','.wasm':'application/wasm','.gz':'application/gzip','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml'}[path.extname(real)]||'application/octet-stream';
 // R3.3 p30: ETag + If-None-Match + br/gzip for compressible types (cached in memory per file signature).
 const sig=sigOf(stat),enc=pickEncoding(req.headers['accept-encoding'],type,stat.size),etag='"'+sig+(enc?'-'+enc:'')+'"',vary=ZTYPES.test(type)?{'Vary':'Accept-Encoding'}:{};
 if(etagMatches(req.headers['if-none-match'],etag)){res.writeHead(304,{'ETag':etag,'Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY',...vary});return res.end();}
 let body,len=stat.size;if(enc){body=await zget(real,sig,enc);len=body.length;}else if(req.method!=='HEAD'){body=await fs.readFile(real);len=body.length;}
 res.writeHead(200,{'Content-Type':type,'Content-Length':len,'Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','ETag':etag,...vary,...(enc?{'Content-Encoding':enc}:{})});res.end(req.method==='HEAD'?undefined:body);
 }catch(_){if(!res.headersSent)send(res,500,{error:'Local request failed'});else res.end();}});
 if(prewarm)server.once('listening',()=>{void(async()=>{try{const real=await fs.realpath(path.join(app,'index.html')),sig=sigOf(await fs.stat(real));await zget(real,sig,'br');await zget(real,sig,'gzip');}catch(_){}})();});
 return server;
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const port=Number(process.env.WORDQUEST_PORT||8765);if(!Number.isInteger(port)||port<1024||port>65535)throw Error('Port must be 1024–65535');makeServer({prewarm:true}).listen(port,'127.0.0.1',()=>console.log('WordQuest local app: http://127.0.0.1:'+port+'/app/index.html\nClose this terminal to stop. Speech API key is never printed.'));}
