/* Host-closure audio adapter. A gesture unlocks the context BEFORE play is committed.
 * Both buses honour the global mute. Zero volume means no scheduled nodes.
 * No wall-clock sequencer: game simulation schedules music, so pause is immediate.
 */
const pgAudio={ctx:null,nodes:new Set(),master:null,musicMaster:null,epoch:0,lastError:'',sample:false,
 async unlock(){const request=++this.epoch;try{if(!this.ctx||this.ctx.state==='closed'){const AC=window.AudioContext||window.webkitAudioContext;if(!AC){this.lastError='此瀏覽器沒有 Web Audio';return false;}this.ctx=new AC();this.master=this.ctx.createGain();this.musicMaster=this.ctx.createGain();this.master.connect(this.ctx.destination);this.musicMaster.connect(this.ctx.destination);}this.mute();if(this.ctx.state==='suspended')await this.ctx.resume();if(request!==this.epoch)return false;this.lastError='';return this.ctx.state==='running';}catch(e){this.lastError=String(e.message||e);toast('未能啟動音效；可無聲遊玩，或按「試音」重試。');return false;}},
 volume(kind){const key=kind==='music'?'arcadeMusicVolume':'arcadeSfxVolume',n=db?.settings?.[key];return Math.max(0,Math.min(100,Number.isFinite(n)?n:kind==='music'?35:60))/100;},
 tone(f=600,d=.1,wave='sine',vol=.1,at=null,kind='sfx'){if(!this.ctx||this.ctx.state!=='running'||!sfxEnabled()||!pgPlaying&&!this.sample||this.volume(kind)===0||this.nodes.size>=64)return;const t=Math.max(this.ctx.currentTime+.001,at??this.ctx.currentTime+.003),duration=Math.max(.025,Math.min(.5,Number.isFinite(d)?d:.1));const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=['sine','triangle','square','sawtooth'].includes(wave)?wave:'sine';o.frequency.value=Math.max(30,Math.min(6000,Number.isFinite(f)?f:600));g.gain.setValueAtTime(.00001,t);g.gain.exponentialRampToValueAtTime(Math.max(.00002,Math.min(.22,Number.isFinite(vol)?vol:.1)),t+.007);g.gain.exponentialRampToValueAtTime(.00001,t+duration);o.connect(g);g.connect(kind==='music'?this.musicMaster:this.master);o.start(t);o.stop(t+duration+.025);this.nodes.add(o);o.onended=()=>{this.nodes.delete(o);try{o.disconnect();g.disconnect();}catch{}};},
 drum(kind,at){this.tone(kind===0?95:kind===1?230:1150,kind===0?.18:.045,kind===0?'sine':'triangle',kind===0?.15:.06,at);},
 instrument(track,step,at){if(track<3)this.drum(track,at);else this.tone((track===3?[130.81,146.83,164.81,174.61]:[523.25,587.33,659.25,783.99])[step%4],.22,'triangle',.07,at);},
 pause(){this.epoch++;this.sample=false;for(const n of this.nodes)try{n.stop();}catch{}this.nodes.clear();if(this.ctx?.state==='running')this.ctx.suspend().catch(()=>{});},
 clock(){return this.ctx?this.ctx.currentTime:performance.now()/1000;},
 mute(){if(!this.ctx)return;const enabled=sfxEnabled(),t=this.ctx.currentTime;for(const[k,b]of [['sfx',this.master],['music',this.musicMaster]])if(b){b.gain.cancelScheduledValues(0);b.gain.value=enabled?this.volume(k)*.8:0;}},
 async test(){if(!sfxEnabled()){toast('目前總聲效已關閉，先按頁首聲效開關。');return;}if(!await this.unlock())return;const epoch=this.epoch;this.sample=true;this.tone(523.25,.14,'triangle',.1);this.tone(659.25,.14,'triangle',.1,this.ctx.currentTime+.15);setTimeout(()=>{if(epoch!==this.epoch)return;this.sample=false;if(!pgPlaying)this.pause();},420);}
};
