/* R2 host UI. No mutable database or game engine is exported to public callers. */
function r2AudioPanel(){return `<details class="r2-audio"><summary>音量與試音</summary><div><label>街機音效 <input type="range" min="0" max="100" step="5" data-r2-volume="arcadeSfxVolume" value="${Math.round(pgAudio.volume('sfx')*100)}" aria-label="街機音效音量"></label><label>新街機配樂 <input type="range" min="0" max="100" step="5" data-r2-volume="arcadeMusicVolume" value="${Math.round(pgAudio.volume('music')*100)}" aria-label="新街機配樂音量"></label>${a28Btn('試音','r2-test-audio','','soft')}</div><p class="small muted">所有街機沿用頁首聲效開關。靜音仍可遊玩；音量設為0會完全靜音。</p></details>`;}
function r2Records(){const c=a28Child(),rows=Object.entries(c.bests).sort((a,b)=>a[0].localeCompare(b[0]));return `<details class="r2-records"><summary>我的街機紀錄 · 原有21款紀錄繼續保留</summary><p>舊遊戲沿用原本紀錄識別碼；五款新遊戲獨立記分，不把舊分數換算成新成績。</p>${rows.length?`<div class="r2-score-list">${rows.map(([k,v])=>{const[id,d]=k.split('|');return `<div><span>${esc(a28Meta(id)?.name||id)} · ${['入門','標準','挑戰'][Number(d)]||''}</span><strong>${v} 分</strong></div>`;}).join('')}</div>`:'<p>目前未有最高分紀錄。</p>'}<p class="small muted">這是本機紀錄，不會從其他瀏覽器自動搬入。V33 原件未取回，未知 V33 存檔格式不會猜測轉換。</p></details>`;}
let r2Immersive=null,r2FitToken=0;
function r2Fit(){cancelAnimationFrame(r2FitToken);r2FitToken=requestAnimationFrame(()=>{const v=$('.a28-viewport'),cv=$('#pg-canvas');if(!v||!cv)return;const w=v.clientWidth,h=v.clientHeight,scale=Math.min(w/800,h/560);if(scale>0){cv.style.width=(800*scale)+'px';cv.style.height=(560*scale)+'px';} });}
function r2ExitFullscreen(){if(r2Immersive){r2Immersive.classList.remove('r2-immersive');r2Immersive=null;document.body.classList.remove('r2-fullscreen');}if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});r2Fit();}
async function r2Fullscreen(){const el=$('.a28-play');if(!el)return;if(r2Immersive||document.fullscreenElement){r2ExitFullscreen();return;}r2Immersive=el;el.classList.add('r2-immersive');document.body.classList.add('r2-fullscreen');r2Fit();try{if(el.requestFullscreen)await el.requestFullscreen();}catch{toast('瀏覽器未提供全螢幕，已使用頁內放大模式。');}r2Fit();}
window.addEventListener('resize',r2Fit);window.visualViewport?.addEventListener('resize',r2Fit);
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&r2Immersive){r2Immersive.classList.remove('r2-immersive');r2Immersive=null;document.body.classList.remove('r2-fullscreen');}r2Fit();});
const r2OldToggleSfx=toggleSfx;toggleSfx=function(){r2OldToggleSfx();pgAudio.mute();};
const r2OldAttach=pgAttach;pgAttach=function(){r2OldAttach();r2Fit();};
const r2OldLobby=gameView;gameView=function(){return r2OldLobby()+r2Records();};
const r2OldRender=render;render=function(){if(r2Immersive)r2ExitFullscreen();r2OldRender();const badge=$('#v25-build-badge');if(badge)badge.textContent=WQ_TEST_MODE?'R2 獨立測試':'英文＋數學＋街機 R2';};
const r2OldOverlay=pgOverlay;pgOverlay=function(){const active=document.activeElement;r2OldOverlay();if(!pgPlaying&&active?.id==='pg-canvas')queueMicrotask(()=>$('#pg-overlay button')?.focus({preventScroll:true}));};
document.addEventListener('click',e=>{const b=e.target.closest('[data-a28]');if(!b||b.disabled)return;if(b.dataset.a28==='r2-full')r2Fullscreen();if(b.dataset.a28==='r2-test-audio')pgAudio.test();});
document.addEventListener('input',e=>{const key=e.target.dataset?.r2Volume;if(!['arcadeSfxVolume','arcadeMusicVolume'].includes(key))return;const n=Number(e.target.value);if(!Number.isInteger(n)||n<0||n>100)return;db.settings[key]=n;pgAudio.mute();});
document.addEventListener('change',e=>{const key=e.target.dataset?.r2Volume;if(!['arcadeSfxVolume','arcadeMusicVolume'].includes(key))return;if(isLoggedIn()){if(!a28CanWrite()||!save())toast('音量只在目前分頁生效，未能儲存。','bad');}});
window.WQR2Runtime=Object.freeze({status(){return Object.freeze({version:'R2.0.0',catalogue:COIN28.catalog.length,newGames:WQR2.ids.length,audioContext:pgAudio.ctx?.state||'not-created',audioError:pgAudio.lastError,globalMute:!sfxEnabled(),sfxVolume:pgAudio.volume('sfx'),musicVolume:pgAudio.volume('music'),liveAudioNodes:pgAudio.nodes.size});}});

const r2OldHUD=a28HUD;a28HUD=function(){r2OldHUD();if(pgMeta?.id==='harbor-volley'&&pgGame&&$('#pg-clock'))$('#pg-clock').textContent=pgGame.points[0]+' : '+pgGame.points[1];};
