/* Accessible local UI; all lesson content comes from curriculum.json. */
(function(root){'use strict';
 const C=root.WQMathCore,S=root.WQMathStorage,L=C.library(root.WQMathData);
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const btn=(text,action,cls='',extra='')=>`<button type="button" data-action="${esc(action)}" class="${cls}" ${extra}>${text}</button>`;
 const tag=t=>`<span class="tag">${esc(t)}</span>`;
 const ref=q=>({template:q.templateId,seed:q.seed});
 const question=r=>C.generate(L,r.template,r.seed);
 const toolLabels={tenframe:'十格框',blocks:'數粒積木',numberline:'數線',fraction:'分數條',place:'數位表',array:'數陣',money:'港幣',bar:'線段圖',segments:'線段枚舉',table:'列表'};
 const stageNames=['情境引入','動手探索','概念講解','一起做','自己做','小結'];
 const towerNames=['先挑戰','試細一步','發現策略','變式練習','一題多解','回想方法'];
 function fraction(v){const a=String(v).split('/');return a.length===2?`<span class="fraction-display" aria-label="${esc(a[0])} 除以 ${esc(a[1])}"><span>${esc(a[0])}</span><span>${esc(a[1])}</span></span>`:esc(v);}
 function df(ms){return Math.max(0,Math.round(ms/60000));}
 let bridge=root.WQM_INTEGRATED?S.createHostBridge():S.standalone(),store,view='home',app,shadow,dialog,launch,toastTimer,audio=null,activeSince=Date.now(),continuous=0,awaitingBreak=false,initialFocus;
 const ui={grade:3,tools:null,freeTool:'tenframe',toolOpen:false,tab:'normal',busy:false,error:'',lastRead:'',lastFast:0,selectedStrategy:'',forceRemedy:false};
 function defaultTool(kind='tenframe',q=null){const p=q?.params||{};return {kind,cells:Array.from({length:20},(_,i)=>i<(Number(p.n)||0)),h:Math.floor(Number(p.a||p.n||52)/100)%10,t:Math.floor(Number(p.a||p.n||52)/10)%10,o:Number(p.a||p.n||52)%10,digits:[0,0,0,0,0],position:0,den:Number(p.den)||4,num:0,den2:Number(p.b)||6,rows:3,cols:4,money:[],front:3,back:4,points:Number(p.points)||4,pairs:[],first:null,tens:1,ones:0,entries:[],changed:0};}
 function current(){return store.state.current;}
 function skill(){return current()?.skill?L.skills.get(current().skill):null;}
 function currentQ(){const s=current();const arr=s?.queues?.[s.stage];return arr?.[s.index]?question(arr[s.index]):null;}
 function active(){return !document.hidden && (!root.WQM_INTEGRATED||dialog?.open);}
 function toast(t){clearTimeout(toastTimer);let e=shadow.getElementById('toast');if(e)e.remove();e=document.createElement('div');e.id='toast';e.className='toast';e.setAttribute('role','status');e.textContent=t;shadow.append(e);toastTimer=setTimeout(()=>e.remove(),6500);}
 function fail(e){ui.error=e.message||String(e);toast(ui.error);}
 function save(fn){return store.change(fn);}
 function initStore(){store=new S.Store(bridge,L);ui.grade=store.profile.grade;ui.error=store.error||'';ui.tools=defaultTool();view=store.state.current?(store.state.current.completed?'lesson':'resume'):'home';}
 function status(s){const m=C.mastery(store.state,s);return C.isMastered(m)?'✓ 已掌握':m.last?'◐ 練習中':'○ 未開始';}
 function mastered(track){return [...L.skills.values()].filter(s=>s.track===track&&C.isMastered(C.mastery(store.state,s))).length;}
 function statCard(n,t){return `<div class="stat"><strong>${n}</strong><span>${esc(t)}</span></div>`;}
 function canStudy(){if(store.readOnly)throw Error(store.error);if((store.state.usage[C.hkDay()]||0)>=store.state.settings.limit*60000)throw Error('今天的數學時間已用完，明天再來。家長可在設定調整時限。');if(awaitingBreak)throw Error('先讓眼睛休息，再繼續。');store.check();}
 function nav(){return `<nav class="nav" aria-label="數學功能">${[['home','學習主頁'],['normal','數學群島'],['olympiad','思維之塔'],['tools','教具工房'],['parent','家長與進度']].map(([id,n])=>btn(n,'nav:'+id,view===id?'active':'')).join('')}</nav>`;}
 function header(){const p=store.profile;return `<header class="topbar"><div class="brand"><div class="brandmark" aria-hidden="true">W</div><div>WordQuest<small>數學群島 · 思維之塔</small></div></div><div class="row"><span class="small name">${esc(p.name)} · 小${p.grade}</span><span class="wallet">◉ <strong id="balance">${store.balance()}</strong> 金幣</span>${root.WQM_INTEGRATED?btn('返回英文','close','quiet'):btn(p.persistent?'切換學員':'家長設定','nav:profiles','quiet')}</div></header>${nav()}`;}
 function home(){const state=store.state,days=Object.keys(state.usage).filter(d=>state.usage[d]>0&&d>=C.plusDay(C.hkDay(),-6)),due=C.dueSkills(state,L).length;return `
 <section class="hero"><div><div class="eyebrow">A little discovery, every day</div><h1>今日，<br>發現數學新方法。</h1><p>先動手，再想通。每日一小步，<br>學懂的不只是答案。</p><div class="row">${btn('開始今日練習　→','daily:normal','primary')}${btn('揀一課來學','nav:normal','quiet')}</div></div><div class="hero-art" aria-hidden="true"><div class="artgrid"><span>3</span><span>+</span><span>5</span><span>½</span><span>×</span><span>8</span><span>÷</span><span>10</span><span>?</span></div><div class="artnote">一個問題，可以有不只一種方法。</div></div></section>
 <div class="stats">${statCard(days.length,'本週學習日數')}${statCard(mastered('normal'),'普通數學已掌握技能')}${statCard(due,'等你重溫的技能')}</div>
 <div class="section-head"><h2>今天想去哪裡？</h2><span class="small muted">同一個學習檔案，兩條獨立路線</span></div><div class="cards">
 <article class="card track-card"><span class="symbol">＋ ÷</span><h3>數學群島</h3><p>跟着學校進度，練熟數感、加減乘除和分數。</p>${btn('前往數字島　→','nav:normal','primary')}</article>
 <article class="card track-card dark"><span class="symbol">◇</span><h3>思維之塔</h3><p>解開陌生謎題，收集你用過的思考方法。不影響校內數學進度。</p>${btn('挑戰一個謎題　→','nav:olympiad','',state.settings.olympiad?'':'disabled')}</article>
 <article class="card track-card"><span class="symbol">▦</span><h3>教具工房</h3><p>拆十條、跳數線、比較分數。慢慢試，這裡不計分。</p>${btn('動手試一試　→','nav:tools','secondary')}</article></div>
 ${!store.profile.persistent?`<div class="notice"><strong>你正在訪客試玩。</strong> 關閉後不保留進度，也不派金幣。${root.WQM_INTEGRATED?'請返回英文登入原有家庭帳戶。':btn('由家長建立本機學習檔案','nav:profiles','tiny-link')}</div>`:''}
 <div class="section-head"><h2>每次，只專心一件事</h2></div><div class="grid2"><div class="card"><h3>學校教到哪裡？</h3><p class="muted">家長揀好正在學的單元，每日練習便會優先安排。</p>${btn('設定學校進度','nav:parent','quiet')}</div><div class="card"><h3>第一次來？</h3><p class="muted">用 15 題看看「數」範疇從哪裡開始。這不是全科能力評級。</p>${btn('數範疇起步測試','diagnostic:normal','quiet')}</div></div>`;}
 function catalog(){const list=L.data.units.filter(u=>u.grade===ui.grade);return `<div class="section-head"><div><div class="eyebrow">The mathematics islands</div><h1>數學群島</h1></div><div class="row grade-selector" aria-label="選擇年級">${[1,2,3,4,5,6].map(g=>btn('小'+g,'grade:'+g,ui.grade===g?'selected':'')).join('')}</div></div>
 <div class="islands">${[['N','數字島'],['M','量度工坊'],['S','圖形森林'],['D','數據市集'],['A','代數城堡']].map(([st,n])=>`<span class="tag ${st==='N'?'selected':''}">${esc(n)}${st==='N'?'':' · 待開發'}</span>`).join('')}</div>
 <div class="note">目前開放小一至小三「數」範疇的 <strong>23 個入門技能</strong>，不是 15 個單元的完整課程。其他單元只保留課程索引，未有課堂或題庫。</div>
 <section class="catalog">${list.map(u=>`<div class="unit-head"><span class="unit-id">${u.id}</span><h2>${u.name}</h2>${u.skills.length?tag('入門選段'):tag('待開發')}</div>${u.skills.length?`<div class="cards">${u.skills.map(id=>{const sk=L.skills.get(id),m=C.mastery(store.state,sk),open=C.accessible(store.state,sk,L,store.profile.grade);return `<article class="card lesson-card"><span class="small muted">${id} · 約 ${sk.lesson.minutes} 分鐘</span><h3>${esc(sk.name_zh)}</h3><p>${esc(sk.name_en)}</p><div>${tag(status(sk))}${m.next?` <span class="small muted">重溫 ${esc(m.next)}</span>`:''}</div><div class="row">${btn(open?'學這一課':'先練基礎','lesson:'+id,'primary',open?'':'disabled')}${btn('5 題練習','practice:'+id,'quiet',open?'':'disabled')}</div>${!open?`<span class="small">先備：${sk.prerequisites.map(i=>L.skills.get(i).name_zh).map(esc).join('、')}</span>`:''}</article>`;}).join('')}</div>`:`<div class="small muted" style="padding:0 0 17px">課程位置已預留；這裡不會用其他題目冒充本單元。</div>`}`).join('')}</section>`;}
 function olympiad(){if(!store.state.settings.olympiad)return `<div class="card"><h1>思維之塔暫未開啟</h1><p>由家長決定是否加入這條選修路線。</p>${btn('前往家長設定','nav:parent','primary')}</div>`;return `<section class="tower"><div class="eyebrow">The tower of thinking · Level 01</div><h1>先想一想，<br>再找另一條路。</h1><p>這裡不比誰最快。畫圖、列表、找規律——每一道門，都有方法打開。</p><div class="row">${btn('10 題思維起步測試','diagnostic:olympiad','secondary')}${btn('我的策略卡','nav:cards')}</div></section>
 <div class="section-head"><h2>啟蒙層 · 五個思維房間</h2><span class="small muted">自由探索，不按學校年級鎖定</span></div><div class="cards">${L.data.skills.filter(s=>s.track==='olympiad').map((sk,i)=>`<article class="card lesson-card"><div class="eyebrow">ROOM 0${i+1} · ${esc(L.data.cards.find(c=>c.id===sk.strategy).name)}</div><h3>${esc(sk.name_zh)}</h3><p>${esc(sk.lesson.scene)}</p><div>${tag(status(sk))}</div>${btn('推開這道門　→','lesson:'+sk.id,'primary')}</article>`).join('')}</div><p class="note" style="margin-top:25px">本版只有啟蒙選題。基礎、進階、競賽衝刺、比賽日曆和正式模擬卷尚未開發；不顯示虛構排名或能力認證。</p>`;}
 function cards(){return `<div class="section-head"><div><div class="eyebrow">Your collection of methods</div><h1>策略卡收集冊</h1></div>${tag(store.state.cards.length+' / 5')}</div><p class="muted">同一主題至少兩題不用提示完成，並在小結選對方法，便會取得入門策略卡。這是本版的完成條件，不代表已全面掌握策略。</p><div class="cards">${L.data.cards.map(c=>`<article class="card badge-card ${store.state.cards.includes(c.id)?'':'locked'}"><span class="tag">${store.state.cards.includes(c.id)?'✓ 已收集':'○ 未收集 · 可先閱讀'}</span><h2 style="margin-top:20px">${esc(c.name)}</h2><p>${esc(c.description)}</p><div class="note">${esc(c.example)}</div></article>`).join('')}</div>`;}
 function setTool(kind,q=null){ui.tools=defaultTool(kind,q);ui.freeTool=kind;}
 function ten(n,interactive=false){return [0,1].map(row=>`<div class="tenframe" aria-label="十格框 ${row+1}">${Array.from({length:10},(_,i)=>{const j=row*10+i,on=interactive?ui.tools.cells[j]:j<n;return interactive?btn('',`tool:cell:${j}`,'cell '+(on?'filled':''),`aria-label="第 ${j+1} 格${on?'，有數粒':'，空白'}" aria-pressed="${on}"`):`<span class="cell ${on?'filled':''}" aria-hidden="true"></span>`;}).join('')}</div>`).join('');}
 function strip(den,num,interactive=false){return `<div class="strips" aria-label="${den} 等份，已選 ${num} 份">${Array.from({length:den},(_,i)=>interactive?btn(i<num?'✓':'',`tool:part:${i}`,(i<num?'filled':''),`aria-label="第 ${i+1} 份" aria-pressed="${i<num}"`):`<span class="${i<num?'filled':''}" aria-hidden="true">${i<num?'✓':''}</span>`).join('')}</div>`;}
 function dots(rows,cols){return rows&&cols?`<div class="dots" style="grid-template-columns:repeat(${cols},minmax(8px,22px))" aria-label="${rows} 行、${cols} 列的數陣">${Array.from({length:rows*cols},()=>'<span class="dot"></span>').join('')}</div>`:'<p>其中一組數量是 0，沒有數粒。</p>';}
 function illustration(q){const p=q.params; if(q.skill==='1N1.1')return `<div class="mini-board" aria-label="供點數的數粒">${ten(Number(p.n))}</div>`;
  if(q.skill==='3N5.1')return `<div class="mini-board">${strip(Number(p.den),Number(p.num))}</div>`;
  if(q.skill==='3N5.3')return `<div class="mini-board"><span>${p.num}/${p.a}</span>${strip(Number(p.a),Number(p.num))}<span>${p.num}/${p.b}</span>${strip(Number(p.b),Number(p.num))}</div>`;
  if(q.skill==='2N3.3'&&q.difficulty===1)return `<div class="mini-board">${dots(Number(p.b),Number(p.a))}</div>`;
  if(q.skill==='O-GEO-segments'){const n=Number(p.points);return `<svg class="svgboard" viewBox="0 0 600 75" role="img" aria-label="一條直線上有 ${n} 個已標示的點"><path d="M30 34H570" stroke="#78906d" stroke-width="3"/>${Array.from({length:n},(_,i)=>`<circle cx="${30+i*540/(n-1)}" cy="34" r="7" fill="#335547"/><text x="${30+i*540/(n-1)}" y="65" text-anchor="middle" font-size="18">${String.fromCharCode(65+i)}</text>`).join('')}</svg>`;}
  return '';
 }
 function toolsHTML(kind=ui.tools.kind){const t=ui.tools;let body='';
  if(kind==='tenframe')body=`${ten(0,true)}<div class="tool-value">${t.cells.filter(Boolean).length} 粒</div><div class="row">${btn('放多一粒','tool:more')}${btn('拿走一粒','tool:less')}${btn('清空','tool:clear','quiet')}</div><p class="small muted">點格子放入／拿走數粒；鍵盤可用 Tab 和空白鍵。</p>`;
  if(kind==='blocks')body=`<div class="blocks-grid">${[['h',t.h,'block-hundred'],['t',t.t,'block-ten'],['o',t.o,'block-one']].map(([k,n,cl])=>`<div><span class="small">${{h:'百板',t:'十條',o:'數粒'}[k]}：${n}</span><div class="blockgroup">${Array.from({length:Math.min(n,25)},()=>`<span class="${cl}"></span>`).join('')}${n>25?'…':''}</div></div>`).join('')}</div><div class="tool-value">總量 ${t.h*100+t.t*10+t.o}</div><div class="row">${btn('＋1','tool:one')}${btn('＋10','tool:ten')}${btn('＋100','tool:hundred')}${btn('拆一個十','tool:split', '',t.t?'':'disabled')}${btn('10 個一換一個十','tool:merge','',t.o>=10?'':'disabled')}${btn('拆一個百','tool:splith','',t.h?'':'disabled')}${btn('清空','tool:clear','quiet')}</div><p class="small muted">交換不會改變總量。用不同分法看清退位和進位。</p>`;
  if(kind==='numberline')body=`<svg class="svgboard" viewBox="0 0 680 135" role="img" aria-label="數線，現在位於 ${t.position}"><path d="M30 80H650" stroke="#56734f" stroke-width="3"/>${Array.from({length:21},(_,i)=>`<path d="M${30+i*31} 71v18" stroke="#657d5b"/><text x="${30+i*31}" y="112" font-size="15" text-anchor="middle">${i}</text>`).join('')}<circle cx="${30+t.position*31}" cy="48" r="18" fill="#ba8139"/><text x="${30+t.position*31}" y="55" text-anchor="middle" font-size="19" fill="#fff">${t.position}</text></svg><div class="row">${[-5,-1,1,5].map(n=>btn((n>0?'＋':'')+n,'tool:jump:'+n)).join('')}${btn('回到 0','tool:clear','quiet')}</div><p class="small muted">向右是加，向左是減。本數線原型範圍 0–20。</p>`;
  if(kind==='fraction')body=`<div class="row"><label>第一條分成 <select id="tool-den" aria-label="分數條等份">${Array.from({length:11},(_,i)=>`<option value="${i+2}" ${t.den===i+2?'selected':''}>${i+2}</option>`).join('')}</select> 份</label>${btn('清空著色','tool:clear','quiet')}</div>${strip(t.den,t.num,true)}<div class="tool-value">已選 ${fraction(t.num+'/'+t.den)}</div><label>第二條分成 <select id="tool-den2" aria-label="比較分數條等份">${Array.from({length:11},(_,i)=>`<option value="${i+2}" ${t.den2===i+2?'selected':''}>${i+2}</option>`).join('')}</select> 份</label>${strip(t.den2,1)}<p class="small muted">兩條總長相同。點上方的等份，試試不同分母的每一份有多大。</p>`;
  if(kind==='place')body=`<div class="placeboard">${['萬','千','百','十','一'].map((n,i)=>`<div>${n}${btn('＋',`tool:digit:${i}:1`,'quiet',`aria-label="增加${n}位"`)}<strong>${t.digits[i]}</strong>${btn('−',`tool:digit:${i}:-1`,'quiet',`aria-label="減少${n}位"`)}</div>`).join('')}</div><div class="tool-value">${t.digits.reduce((n,d,i)=>n+d*10**(4-i),0)}</div><p class="small muted">改變一個數位，再看看整個數怎樣改變。</p>`;
  if(kind==='array')body=`<div class="row"><label>行 <select id="tool-rows">${Array.from({length:11},(_,n)=>`<option ${n===t.rows?'selected':''}>${n}</option>`).join('')}</select></label><label>列 <select id="tool-cols">${Array.from({length:11},(_,n)=>`<option ${n===t.cols?'selected':''}>${n}</option>`).join('')}</select></label></div>${dots(t.rows,t.cols)}<div class="tool-value">${t.rows} × ${t.cols} = ${t.rows*t.cols}</div>`;
  if(kind==='money')body=`<div class="chiprow">${[1,2,5,10,20,50].map(n=>btn('$'+n,'tool:coin:'+n,'coin '+(n>=20?'note-coin':''),`aria-label="加入 ${n} 元"`)).join('')}</div><div class="tool-value">已砌金額：$${t.money.reduce((a,b)=>a+b,0)}</div><div class="chiprow">${t.money.map((n,i)=>btn('$'+n,'tool:remove-coin:'+i,'tag',`aria-label="移除一個 ${n} 元"`)).join('')}</div>${btn('清空','tool:clear','quiet')}<p class="small muted">簡化港幣教具，不是真鈔圖樣。只用整元；小店找贖定位在小二或以上。</p>`;
  if(kind==='bar')body=`<div class="row">${btn('前方 ＋1','tool:front:1')}${btn('前方 −1','tool:front:-1')}${btn('後方 ＋1','tool:back:1')}${btn('後方 −1','tool:back:-1')}</div><svg class="svgboard" viewBox="0 0 640 120" role="img" aria-label="前方 ${t.front} 人，自己一人，後方 ${t.back} 人"><rect x="10" y="25" width="${t.front*22}" height="42" rx="6" fill="#86a179"/><rect x="${20+t.front*22}" y="25" width="22" height="42" rx="6" fill="#c18a43"/><rect x="${52+t.front*22}" y="25" width="${t.back*22}" height="42" rx="6" fill="#708da2"/><text x="10" y="100" font-size="20">前方 ${t.front} ＋ 自己 1 ＋ 後方 ${t.back} ＝ ${t.front+t.back+1}</text></svg>`;
  if(kind==='segments')body=`<label>標示點的數量 <select id="tool-points">${[3,4,5,6,7,8].map(n=>`<option ${n===t.points?'selected':''}>${n}</option>`).join('')}</select></label><div class="chiprow" style="margin:18px 0">${Array.from({length:t.points},(_,i)=>btn(String.fromCharCode(65+i),'tool:point:'+i,t.first===i?'primary':'')).join('')}</div><p class="small">先選一個端點，再選另一個。AB 和 BA 只記一次。</p><div class="chiprow">${t.pairs.map(p=>tag(String.fromCharCode(65+p[0])+String.fromCharCode(65+p[1]))).join('')}</div><div class="tool-value">已找到 ${t.pairs.length} 條</div>${btn('重新列出','tool:clear','quiet')}`;
  if(kind==='table')body=`<div class="row"><label>十位 <select id="tool-tens">${Array.from({length:9},(_,i)=>`<option ${t.tens===i+1?'selected':''}>${i+1}</option>`).join('')}</select></label><label>個位 <select id="tool-ones">${Array.from({length:10},(_,i)=>`<option ${t.ones===i?'selected':''}>${i}</option>`).join('')}</select></label>${btn('加入列表','tool:entry')}</div><div class="scrolltable"><table><thead><tr><th>兩位數</th><th>十位＋個位</th></tr></thead><tbody>${t.entries.map(n=>`<tr><td>${n}</td><td>${Math.floor(n/10)} ＋ ${n%10} ＝ ${Math.floor(n/10)+n%10}</td></tr>`).join('')}</tbody></table></div><div class="tool-value">已列 ${t.entries.length} 個不同的數</div>${btn('清空','tool:clear','quiet')}`;
  return `<div class="toolbox"><h3>${toolLabels[kind]}</h3>${body}</div>`;
 }
 function toolsPage(){return `<div class="section-head"><div><div class="eyebrow">Learn by doing</div><h1>教具工房</h1></div>${tag('自由探索 · 不計入掌握度')}</div><div class="tool-tabs">${Object.entries(toolLabels).map(([k,n])=>btn(n,'selecttool:'+k,ui.tools.kind===k?'picked':'')).join('')}</div><div id="tool-region">${toolsHTML()}</div><div class="section-head"><h2>把數學放進玩法</h2></div><div class="grid2"><div class="card"><h3>數線跳跳</h3><p>在 0–20 的數線跳出答案，完成 5 道加減題。不是做完題目才准玩的街機。</p>${btn('開始數線任務','game:numberline','primary')}</div><div class="card"><h3>港式小店</h3><p>按錢幣砌找贖，再交給客人。定位小二以上，會用同一題目引擎記錄。</p>${btn('開舖試一試','game:money','primary')}</div></div><p class="small muted">這兩款是數學操作原型，未達你之前要求的街機遊戲完成度；沒有改動原英文程式的街機。</p>`;}
 function makeSession(skId,mode='lesson',game=null){canStudy();const sk=L.skills.get(skId);if(!sk)throw Error('技能不存在');if(sk.track==='olympiad'&&!store.state.settings.olympiad)throw Error('家長尚未開啟奧數');if(!C.accessible(store.state,sk,L,store.profile.grade))throw Error('先完成列出的先備技能');
  save(n=>{const oly=sk.track==='olympiad';const s={id:S.uid(),skill:sk.id,track:sk.track,mode,game,stage:mode==='lesson'?0:4,index:0,queues:{},example:null,startedAt:Date.now(),questionAt:Date.now(),activeMs:0,hint:0,feedback:null,results:[],replacements:[],completed:false,rewardDone:false,fast:0,draft:'',picked:'',reflection:null};
   s.example=ref(C.nextQuestion(n,L,sk.id,1));
   if(mode==='lesson'&&oly){s.queues[0]=[ref(C.nextQuestion(n,L,sk.id,2))];s.queues[3]=Array.from({length:3},(_,i)=>ref(C.nextQuestion(n,L,sk.id,i===2?3:2)));}
   else {if(mode==='lesson')s.queues[3]=Array.from({length:3},(_,i)=>ref(C.nextQuestion(n,L,sk.id,i?2:1)));s.queues[4]=Array.from({length:5},(_,i)=>ref(C.nextQuestion(n,L,sk.id,game?2:i===4?3:2)));}
   n.current=s;});ui.toolOpen=false;setTool(game||sk.tool);view='lesson';render();readAuto();
 }
 function makePlan(mode,track){canStudy();if(track==='olympiad'&&!store.state.settings.olympiad)throw Error('家長尚未開啟奧數');save(n=>{
  const all=L.data.skills.filter(s=>s.track===track&&C.accessible(n,s,L,store.profile.grade));let ids;
  if(mode==='daily')ids=C.planDaily(n,L,{grade:store.profile.grade,track});
  else{const near=all.filter(s=>s.grade===Math.min(store.profile.grade,3));const pool=near.length?near:all;ids=Array.from({length:track==='normal'?15:10},(_,i)=>(i%3===0?all[i%all.length]:pool[i%pool.length]).id);}
  const s={id:S.uid(),skill:null,track,mode,game:null,stage:4,index:0,queues:{4:ids.map((id,i)=>ref(C.nextQuestion(n,L,id,mode==='daily'?2:i<5?1:i<10?2:3)))},example:null,startedAt:Date.now(),questionAt:Date.now(),activeMs:0,hint:0,feedback:null,results:[],replacements:[],completed:false,rewardDone:false,fast:0,draft:'',picked:'',reflection:null};n.current=s;
 });view='lesson';ui.toolOpen=false;render();readAuto();}
 function questionView(q){const s=current(),sk=L.skills.get(q.skill),setting=store.state.settings,language=setting.language;const idx=s.index+1,total=s.queues[s.stage].length;
  let input='';
  if(s.game){if(ui.tools.kind!==s.game)setTool(s.game);input=`<div id="tool-region">${toolsHTML(s.game)}</div>${s.game==='money'?'<p class="small">用錢幣砌好找贖，按下面「交給客人」。遊戲記錄的是金額，不評算式過程。</p>':''}`;}
  else if(q.type==='choice')input=`<div class="choices" role="group" aria-label="選擇答案">${q.choices.map((c,i)=>btn(fraction(c.value),'choice:'+i,'choice '+(s.picked===c.value?'picked':''),`${s.feedback?'disabled':''} aria-pressed="${s.picked===c.value}"`)).join('')}</div>`;
  else if(q.type==='word')input=`<div class="word-fields"><div class="field"><label for="expression">① 算式（一步算式，不用等號）</label><input id="expression" placeholder="例如：50 − 8 × 3" value="${esc(s.feedback?.answer?.expression??s.draftExpression??'')}" ${s.feedback?'disabled':''} maxlength="120"></div><div class="field"><label for="answer">② 數值答案</label><input id="answer" inputmode="decimal" placeholder="填寫答案" value="${esc(s.feedback?.answer?.value||s.draft||'')}" ${s.feedback?'disabled':''} maxlength="60"></div><div class="field"><label for="unit">③ 單位</label><select id="unit" ${s.feedback?'disabled':''}><option value="">請選擇</option><option value="元" ${(s.feedback?.answer?.unit??s.draftUnit)==='元'?'selected':''}>元 dollars</option><option value="個">個 objects</option><option value="分鐘">分鐘 minutes</option></select></div><div class="field"><label>④ 答句（句式支架）</label><div class="answer-sentence" id="sentence">應找回＿＿元。</div></div></div><p class="small muted">答句由數值和單位組成，並非 AI 自動批改自由文字。分數：數值 2、算式 1、單位 1。</p>`;
  else input=`<div class="row"><div class="field"><label for="answer">${q.type==='remainder'?'商':'你的答案'}</label><input id="answer" class="answer-input" inputmode="decimal" maxlength="60" placeholder="${q.type==='fraction'?'例如 1/2':'填寫數字'}" value="${esc(s.feedback?.answer?.value??s.draft??'')}" ${s.feedback?'disabled':''}></div>${q.type==='remainder'?`<div class="field"><label for="remainder">餘數（沒有餘數填 0）</label><input id="remainder" class="answer-input" inputmode="numeric" maxlength="8" placeholder="0" value="${esc(s.feedback?.answer?.remainder??s.draftRemainder??'')}" ${s.feedback?'disabled':''}></div>`:''}</div>${q.type==='fraction'&&!s.feedback?`<div class="keypad">${['1','2','3','4','5','6','7','8','9','0','/','⌫'].map(k=>btn(k,'key:'+k,'',`aria-label="${k==='/'?'分數線':k}"`)).join('')}</div>`:''}`;
  const challenge=s.track==='olympiad'&&s.mode==='lesson'&&s.stage===0;
  const progress=(idx-1)/total*100;
  return `<section class="question-wrap motion"><div class="row between"><span class="small muted">${esc(sk.name_zh)} · ${idx} / ${total}</span><div class="row">${tag(['','入門','練熟','挑戰'][q.difficulty])}${btn('🔊 讀題','speak','quiet',`aria-label="讀出題目"`)}</div></div><div class="progress"><i style="width:${progress}%"></i></div><div class="question-stem" id="stem">${language!=='en'?esc(q.stem_zh):''}${language!=='zh'?`<div class="${language==='bi'?'en':''}">${esc(q.stem_en)}</div>`:''}</div>${illustration(q)}${input}
   ${s.hint&&!s.feedback?`<aside class="hint"><strong>提示 ${s.hint}/5 · 慢慢想</strong><ol>${q.hints.slice(0,Math.min(4,s.hint)).map(h=>`<li>${esc(h)}</li>`).join('')}${s.hint===5?`<li><strong>完整解答：${fraction(q.answer)}${q.remainder!==null?' 餘 '+esc(q.remainder):''}</strong><p>${esc(q.explanation)}</p>下一步必須做一條不同數字的新題。</li>`:''}</ol></aside>`:''}
   ${ui.toolOpen&&!s.game?`<div id="tool-region">${toolsHTML()}</div>`:''}
   ${s.feedback?feedbackHTML(s.feedback,q):''}${s.fastPause?`<div class="notice" role="alert">先停一停，讀清楚題目。${btn('我會慢慢讀題','unpause-fast','secondary')}</div>`:''}
   <div class="actions"><div class="row">${!s.feedback&&!challenge?btn(s.hint<5?'給我一點提示':'已看完整解答','hint','secondary',s.hint<5?'':'disabled'):''}${challenge&&!s.feedback?btn('先用細例子試','nextstage','quiet'):''}</div>${s.feedback?btn('下一步　→','nextq','primary',s.fastPause?'disabled':''):btn(s.game==='money'?'交給客人':s.game?'在這裡落腳':'檢查答案','submit','primary')}</div>
   ${challenge?'<p class="small muted">先獨立試一試；這道開場題不計入掌握度。</p>':''}<div style="margin-top:20px">${btn('這題可能有問題','report-item','tiny-link')}</div></section>`;
 }
 function feedbackHTML(f,q){const mis=L.data.misconceptions[f.code];return `<div class="feedback ${f.correct?'':'partial'}" role="status"><strong>${f.correct?'✓':'↗'} ${esc(f.message)}</strong>${!f.correct&&mis?`<p>${esc(mis.remedy)}</p>`:''}${!f.correct?`<p><strong>訂正：</strong>${fraction(q.answer)}${q.remainder!==null?' 餘 '+esc(q.remainder):''} ${esc(q.unit)}</p><p>${esc(q.explanation)}</p><p class="small">原來作答會保留作學習資料；下一題會換數字，不靠背答案。</p>`:''}${f.parts?`<p class="small">${Object.entries(f.parts).map(([k,v])=>esc(({value:'數值',expression:'算式',unit:'單位',quotient:'商',remainder:'餘數'})[k])+` ${v?'✓':'待調整'}`).join('　')}</p>`:''}</div>`;}
 function lesson(){const s=current();if(!s)return home();const sk=skill(),oly=s.track==='olympiad',title=sk?.name_zh||({daily:'今日 10 題練習',diagnostic:oly?'思維起步測試':'數範疇起步測試'}[s.mode]||'練習');
  const names=oly?towerNames:stageNames;const head=`<div class="lesson-panel"><div class="lesson-title"><div><div class="eyebrow">${s.mode==='lesson'?'One lesson, one discovery':s.mode==='diagnostic'?'Find your starting point':'Practice a little, remember more'}</div><h1>${esc(title)}</h1></div>${btn('稍後繼續','pause','quiet')}</div>${s.mode==='lesson'?`<div class="steps">${names.map((n,i)=>`<span class="step ${i===s.stage?'current':i<s.stage?'done':''}" ${i===s.stage?'aria-current="step"':''}>${i+1} ${n}</span>`).join('')}</div>`:''}`;
  if(s.completed)return head+summaryHTML(s)+'</div>';
  const q=currentQ();if(q)return head+questionView(q)+'</div>';
  let body='';const ex=question(s.example);
  if(!oly&&s.stage===0)body=`<div class="scene">${esc(sk.lesson.scene)}</div><p>這課只練：<strong>${esc(sk.name_zh)}</strong></p><p class="muted">先試教具，再一起做，最後自己完成 5 題。沒有倒數壓力。</p>${btn('開始動手探索　→','nextstage','primary')}`;
  if(s.stage===1){if(ui.tools.kind!==sk.tool)setTool(sk.tool,ex);body=`<h2>${ui.forceRemedy?'換個方法再試':'先動手，看看會怎樣。'}</h2><p>${esc(ui.forceRemedy?sk.lesson.remedy:sk.lesson.explore)}</p><div id="tool-region">${toolsHTML()}</div>${btn('我試過了，看看原理　→','nextstage','primary')}`;}
  if(s.stage===2)body=`<h2>${oly?'你剛才用的方法':'把圖像變成算式'}</h2><div class="scene">${esc(sk.lesson.concept)}</div><div class="mini-board"><strong>${esc(ex.stem_zh)}</strong>${illustration(ex)}<p>答案：${fraction(ex.answer)}${ex.remainder!==null?' 餘 '+ex.remainder:''}</p><p>${esc(ex.explanation)}</p></div>${oly?`<div class="note">策略卡：${esc(L.data.cards.find(c=>c.id===sk.strategy).name)}。閱讀不會自動獲得卡片；下一步試着自己運用。</div>`:''}<div class="actions">${btn(oly?'用這個方法試新題　→':'一起做三題　→','nextstage','primary')}</div>`;
  if(oly&&s.stage===4)body=`<h2>同一題，可以換一條路。</h2><div class="scene">${esc(sk.lesson.concept)}</div><div class="note">${esc(sk.lesson.alternative)}</div><div class="actions">${btn('回想剛才的方法　→','nextstage','primary')}</div>`;
  if(s.stage===5){body=oly?`<h2>下次見到類似題目，你會先做甚麼？</h2><p class="muted">選擇本課真正用到的方法，不是最快按答案。</p><div class="stack">${[sk.lesson.reflection,'先亂估一個數，再不停按答案。','只把所有數字加起來，不看它們的關係。'].map((t,i)=>btn(esc(t),'reflect:'+i,i===s.reflection?'primary':'',`style="display:block;width:100%;text-align:left"`)).join('')}</div><div class="actions">${btn('完成這次探索','finish','primary',s.reflection!==null?'':'disabled')}</div>`:`<h2>今天的一個重點</h2><div class="scene">${esc(sk.lesson.concept)}</div><p>現在的感覺怎樣？</p><div class="row">${btn('明白了','self:good','primary')}${btn('有啲唔明','self:unsure','secondary')}${btn('好難，想換個方法','self:hard')}</div>`;}
  return head+`<section class="question-wrap motion">${body}</section></div>`;
 }
 function summaryHTML(s){const r=s.results.filter(r=>r.mode!=='guided'&&r.mode!=='challenge-demo'),count=r.length,good=r.filter(r=>r.correct).length,stars=good/count>=.8?3:good/count>=.5?2:1;const isDiagnostic=s.mode==='diagnostic',sk=skill();return `<div class="question-wrap"><div class="eyebrow">${isDiagnostic?'A starting point, not a label':'You kept thinking'}</div><h2>${isDiagnostic?'知道下一步怎樣開始了。':'完成一輪，有新發現。'}</h2>${!isDiagnostic?`<div class="summary-score" aria-label="${stars} 顆星">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div>`:''}<p>${isDiagnostic?'起步測試不會顯示總分，也不是全科或比賽能力評級。':`你完成了 ${count} 次獨立練習作答。需要訂正的題目，會用新數字再練。`}</p>${store.profile.grade>=4&&store.state.settings.showScore&&!isDiagnostic?`<p>本輪正確：${good}/${count}</p>`:''}<div class="notice">${!store.profile.persistent?'訪客模式沒有派金幣；建立學習檔案後才會保存。':isDiagnostic?'起步測試不派獎勵。':s.award?`◉ 本輪獲得 ${s.award} 金幣。`:'這輪沒有額外金幣：可能已完成相同任務、達每日上限，或仍需要多做幾題。'}${s.rewardError?`<br>${esc(s.rewardError)}；記錄已保留，家長頁可重試。`:''}</div>
 ${sk?.strategy&&store.state.cards.includes(sk.strategy)?`<div class="card badge-card"><h3>✓ 已收集策略卡</h3><p>${esc(L.data.cards.find(c=>c.id===sk.strategy).name)}</p></div>`:''}
 ${s.self==='hard'||s.self==='unsure'?`<div class="note"><strong>下次換個方法：</strong>${esc(sk?.lesson.remedy||'先用教具，再試一小步。')}${sk?btn('現在換個方法教','remedy:'+sk.id,'tiny-link'):''}</div>`:''}
 <h3 style="margin-top:23px">下一步</h3>${[...new Set(r.filter(a=>!a.correct).map(a=>a.skill))].slice(0,3).map(id=>`<div class="report-row"><span>${esc(L.skills.get(id).name_zh)}</span>${btn('換個方法再學','remedy:'+id,'quiet')}</div>`).join('')||'<p>過一段時間再試新題，看看方法是否記得。</p>'}<div class="actions">${btn('返回學習主頁','completed-home','primary')}${btn('查看學習進度','completed-parent','quiet')}</div></div>`;}
 function parent(){const state=store.state,today=C.hkDay(),from=C.plusDay(today,-6),a=state.attempts.filter(a=>C.hkDay(a.at)>=from&&a.mode!=='guided'&&a.mode!=='challenge-demo'),normal=a.filter(x=>x.track==='normal'),oly=a.filter(x=>x.track==='olympiad'),minutes=Object.entries(state.usage).filter(([d])=>d>=from).reduce((a,[_,b])=>a+b,0),days=Object.keys(state.usage).filter(d=>d>=from&&state.usage[d]>0).length;
  const weak=[...new Set(normal.filter(a=>!a.correct).map(a=>a.skill))];return `<div class="section-head"><div><div class="eyebrow">A clear picture, not a comparison</div><h1>${esc(store.profile.name)}的學習週報</h1><span class="small muted">${from} 至 ${today} · 香港日期</span></div>${btn('匯出數學備份','export','secondary')}</div><div class="stats">${statCard(days,'有學數學的日數')}${statCard(df(minutes),'數學使用分鐘')}${statCard(L.data.skills.filter(s=>s.track==='normal'&&C.mastery(state,s).achieved>=Date.parse(from+'T00:00:00+08:00')).length,'本週新達標技能')}</div>
 <div class="grid2"><section class="card"><h2>普通數學</h2><p class="muted">${normal.length} 次獨立練習紀錄 · 已掌握 ${mastered('normal')} 個入門技能</p>${weak.length?weak.slice(0,5).map(id=>{const m=Object.values(state.mistakes).find(m=>m.skill===id),mi=m?L.data.misconceptions[m.code]:null;return `<div class="report-row"><div><strong>${esc(L.skills.get(id).name_zh)}</strong><p>${esc(mi?.name||'需要再練一次')} · ${esc(mi?.remedy||L.skills.get(id).lesson.remedy)}</p></div>${btn('下一步','remedy:'+id,'quiet')}</div>`;}).join(''):'<p>尚未找到本週需要留意的弱項。沒有紀錄不代表已掌握。</p>'}</section><section class="card"><h2>奧數 · 獨立紀錄</h2><p>${oly.length} 次獨立練習紀錄</p><p>已收集 ${state.cards.length} 張入門策略卡。</p><div class="note">奧數做錯，不會扣普通數學的掌握度。策略卡不等於比賽能力或認證。</div>${btn('查看策略卡','nav:cards','quiet')}</section></div>
 <div class="section-head"><h2>錯題本 · 用新題再試</h2></div><div class="card">${Object.values(state.mistakes).filter(m=>!m.cleared).map(m=>`<div class="report-row"><div><strong>${esc(L.skills.get(m.skill)?.name_zh||m.skill)}</strong> ${tag(m.track==='normal'?'普通數學':'奧數')}<p>${esc(L.data.misconceptions[m.code]?.name||'再看一次')} · 下次 ${esc(m.due[0]||today)}</p></div>${btn('做兩題新題','mistake:'+m.skill,'quiet')}</div>`).join('')||'<p>暫時沒有待重溫的錯題技能。</p>'}</div>
 <div class="section-head"><h2>安排與控制</h2>${tag('本機家長頁 · 無身份驗證')}</div><section class="card"><div class="grid2"><div class="field"><label for="school">學校正在教的單元</label><select id="school"><option value="">按技能進度安排</option>${L.data.units.filter(u=>u.skills.length).map(u=>`<option value="${u.id}" ${state.settings.schoolUnit===u.id?'selected':''}>小${u.grade} · ${u.id} ${u.name}</option>`).join('')}</select></div><div class="field"><label for="limit">每天數學使用時限</label><select id="limit">${[5,10,15,20,30,45,60,90].map(n=>`<option value="${n}" ${state.settings.limit===n?'selected':''}>${n} 分鐘</option>`).join('')}</select></div><div class="field"><label for="language">題目文字</label><select id="language">${[['zh','繁體中文'],['en','English'],['bi','中英雙語']].map(([v,t])=>`<option value="${v}" ${state.settings.language===v?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label for="voice">讀題聲線（需裝置支援）</label><select id="voice">${[['yue-HK','粵語'],['zh-CN','普通話'],['en-GB','英式英文']].map(([v,t])=>`<option value="${v}" ${state.settings.voice===v?'selected':''}>${t}</option>`).join('')}</select></div></div>
 ${[['olympiad','開啟思維之塔（奧數選修）'],['sound','播放答題音效'],['slow','慢速模式：停用快速亂估提示；所有練習本來都不計時'],['showScore','高小顯示數值成績（小一至小三仍不顯示百分比）']].map(([k,t])=>`<label class="switch"><input type="checkbox" id="setting-${k}" ${state.settings[k]?'checked':''}><span>${esc(t)}</span></label>`).join('')}<div class="row">${btn('儲存安排','save-settings','primary')}${btn('試聽讀題','sample-speech','quiet')}</div><p class="small muted">本版時限和週報只統計數學模組，未把英文使用時間合併。沒有排行榜、通知或廣告推送；本機家長頁不是安全的防繞過鎖。</p></section>
 <div class="section-head"><h2>資料與可靠性</h2></div><div class="card"><p>所有資料只存在這部裝置的瀏覽器。清除瀏覽資料、換網址、換瀏覽器或更改本機檔案位置，都可能看不到原有進度。先保留備份。</p><div class="row">${btn('匯出目前孩子的數學資料','export','secondary')}${btn('匯入同一孩子的備份','import')}${btn('重試待結算獎勵','flush')}${btn('清除目前孩子的數學進度','clear-maths','danger')}</div><input type="file" id="import-file" accept="application/json,.json" hidden><p class="small muted">數學資料使用獨立旁存，避免被英文舊版驗證器刪掉；原英文「匯出」不會包含此資料，請兩份都備份。清除數學進度不會撤回已發的英文金幣。</p>${state.reports.length?`<p>有 ${state.reports.length} 條題目報錯紀錄，已包含在數學備份中；尚未傳送到伺服器。</p>`:''}</div><div class="section-head"><h2>中英數學詞彙</h2></div><div class="grid2">${L.data.glossary.map(g=>`<div class="card"><h3>${esc(g.zh)} · ${esc(g.en)}</h3><p class="small muted">${esc(g.note)}</p>${btn('聽英文','term:'+g.en,'quiet')}</div>`).join('')}</div>`;}
 function profiles(){if(root.WQM_INTEGRATED)return '<div class="card">請返回英文程式，使用原有的孩子切換功能。</div>';return `<div class="section-head"><div><div class="eyebrow">Local family profiles</div><h1>一人一份學習紀錄</h1></div></div><div class="notice">這是本機試用版，不是雲端帳戶。沒有收集電郵、真名、學校或密碼，也沒有把資料傳到網上。</div><div class="grid2"><div class="card"><h2>選擇學員</h2>${bridge.children().map(c=>`<div class="report-row"><span>${esc(c.name)} · 小${c.grade}</span>${btn('使用此檔案','switch:'+c.id,'quiet')}</div>`).join('')||'<p>尚未建立學習檔案。</p>'}${btn('不用儲存，訪客試玩','guest','quiet')}${store.profile.persistent?btn('刪除目前學員本機資料','delete-profile','danger'):''}</div><div class="card"><h2>由家長建立學習檔案</h2><div class="field" style="margin-top:18px"><label for="nickname">暱稱（毋須真名）</label><input id="nickname" maxlength="24" placeholder="例如：樂樂"></div><div class="field" style="margin-top:15px"><label for="new-grade">年級</label><select id="new-grade">${[1,2,3,4,5,6].map(n=>`<option value="${n}" ${n===3?'selected':''}>小${n}</option>`).join('')}</select></div><label class="switch"><input type="checkbox" id="consent"><span>我是家長／照顧者，同意在這個瀏覽器保存孩子的暱稱、年級和學習資料。</span></label>${btn('建立本機學習檔案','create-profile','primary')}</div></div>`;}
 function render(){if(!store)return;const s=current();let content;
  if(view==='resume')content=`<div class="hero"><div><div class="eyebrow">Welcome back</div><h1>上次學到這裡。</h1><p>已提交的答案有保存。繼續上次一課，或結束這輪再重新選擇。</p><div class="row">${btn('繼續上次學習','resume','primary')}${btn('結束這輪','abandon','quiet')}</div></div></div>`;
  else content=({home,normal:catalog,olympiad,cards,tools:toolsPage,parent,profiles,lesson})[view]?.()||home();
  if(awaitingBreak)content=`<div class="hero"><div><div class="eyebrow">A moment away from the screen</div><h1>先休息一下。</h1><p>已連續使用約 20 分鐘。放低裝置，望一望遠處，活動一下。</p>${btn('休息後繼續','rested','primary')}</div></div>`;
  app.innerHTML=`<div class="wqm ${store.profile.grade>=5?'older':''}"><div class="shell">${header()}${ui.error?`<div class="notice" role="alert">${esc(ui.error)}</div>`:''}${content}<footer class="foot">WordQuest Maths 0.1.0 · 本機功能試用版<br>2017 課程框架／2026 建模修訂另作版本記錄 · 課程及粵語語音仍待獨立教師與真人試用審核。<br>23 個普通數學入門技能 ＋ 5 個奧數主題；其餘課程未完成。離線答案可被檢視，不適合正式比賽判分。</footer></div></div>`;
  app.querySelectorAll('input,select').forEach(e=>e.addEventListener('change',changeHandler));
  const ans=app.querySelector('#answer');if(ans)ans.addEventListener('input',()=>{const sent=app.querySelector('#sentence');if(sent)sent.textContent='應找回 '+ans.value+' '+(app.querySelector('#unit')?.value||'＿＿')+'。';});
 }
 function redrawTool(){const el=app.querySelector('#tool-region');if(el){el.innerHTML=toolsHTML();el.querySelectorAll('select').forEach(e=>e.addEventListener('change',changeHandler));}}
 function changeHandler(e){if(e.target.id.startsWith('tool-')){try{canStudy();}catch(err){fail(err);return;}}const id=e.target.id,v=Number(e.target.value),t=ui.tools;if(id==='tool-den'){t.den=v;t.num=Math.min(t.num,v);}else if(id==='tool-den2')t.den2=v;else if(id==='tool-rows')t.rows=v;else if(id==='tool-cols')t.cols=v;else if(id==='tool-points'){t.points=v;t.pairs=[];t.first=null;}else if(id==='tool-tens')t.tens=v;else if(id==='tool-ones')t.ones=v;else if(id==='unit'){const a=app.querySelector('#answer');const sent=app.querySelector('#sentence');if(sent)sent.textContent='應找回 '+(a?.value||'＿＿')+' '+(e.target.value||'＿＿')+'。';return;}else return;t.changed++;redrawTool();}
 function toolAction(parts){canStudy();const t=ui.tools,k=parts[1],n=Number(parts[2]);t.changed++;
  if(k==='cell')t.cells[n]=!t.cells[n];if(k==='more'){const i=t.cells.indexOf(false);if(i>=0)t.cells[i]=true;}if(k==='less'){const i=t.cells.lastIndexOf(true);if(i>=0)t.cells[i]=false;}
  if(k==='clear'){const kind=t.kind;ui.tools=defaultTool(kind);if(kind==='blocks'){ui.tools.h=ui.tools.t=ui.tools.o=0;}if(kind==='tenframe')ui.tools.cells.fill(false);}
  if(k==='one'&&t.o<99)t.o++;if(k==='ten'&&t.t<99)t.t++;if(k==='hundred'&&t.h<9)t.h++;
  if(k==='split'&&t.t&&t.o<=89){t.t--;t.o+=10;}if(k==='merge'&&t.o>=10&&t.t<99){t.t++;t.o-=10;}if(k==='splith'&&t.h&&t.t<=89){t.h--;t.t+=10;}
  if(k==='jump')t.position=Math.max(0,Math.min(20,t.position+n));if(k==='part')t.num=t.num===n+1?n:n+1;
  if(k==='digit'){const delta=Number(parts[3]);t.digits[n]=Math.max(0,Math.min(9,t.digits[n]+delta));}
  if(k==='coin'){if(t.money.length<50)t.money.push(n);else toast('先把部分金額換成較大的錢幣。');}if(k==='remove-coin')t.money.splice(n,1);
  if(k==='front'||k==='back')t[k]=Math.max(0,Math.min(10,t[k]+n));
  if(k==='point'){if(t.first===null)t.first=n;else{if(t.first!==n){const pair=[t.first,n].sort((a,b)=>a-b);if(!t.pairs.some(p=>p[0]===pair[0]&&p[1]===pair[1]))t.pairs.push(pair);}t.first=null;}}
  if(k==='entry'){const x=t.tens*10+t.ones;if(!t.entries.includes(x))t.entries.push(x);}
  redrawTool();
 }
 async function submit(){canStudy();const s=current(),q=currentQ();if(!s||!q||s.feedback)return;let input;
  if(s.game==='numberline')input={value:String(ui.tools.position)};
  else if(s.game==='money'){const sum=ui.tools.money.reduce((a,b)=>a+b,0);input={value:String(sum)};}
  else if(q.type==='choice'){if(!s.picked){toast('先選一個答案。');return;}input={value:s.picked};}
  else input={value:app.querySelector('#answer')?.value||'',expression:app.querySelector('#expression')?.value||'',unit:app.querySelector('#unit')?.value||'',remainder:app.querySelector('#remainder')?.value||''};
  // Cash game evaluates amount only: no fabricated expression/process credit.
  const scoredQ=s.game==='money'?{...q,type:'number',unit:''}:q;
  const result=C.mark(scoredQ,input);if(!result.valid){toast(result.message);return;}
  const mode=s.mode==='lesson'&&s.stage===3&&s.track==='normal'?'guided':s.mode==='lesson'&&s.stage===0&&s.track==='olympiad'?'challenge-demo':s.mode;
  const time=Math.min(3600000,Math.max(0,Date.now()-s.questionAt));let fastPause=false;
  save(n=>{const ss=n.current;const r=C.record(n,L,scoredQ,input,{id:ss.id+':'+ss.stage+':'+ss.index,at:Date.now(),hint:ss.hint,time_ms:time,independent:mode!=='guided'&&mode!=='challenge-demo',mode});
   if(r.duplicate)return;ss.feedback={...r,answer:input};ss.results.push({skill:q.skill,correct:r.correct,credit:r.credit,hint:ss.hint,mode,time_ms:time,at:Date.now()});
   if(q.type==='choice'&&time<2000&&!n.settings.slow)ss.fast++;else ss.fast=0;if(ss.fast>=3){fastPause=true;ss.fastPause=true;ss.fast=0;}
  });sound(result.correct);render();if(fastPause)toast('慢慢諗。你已連續快速選了三次；下一題先讀清楚，再作答。');
 }
 function nextQ(){const s=current();if(!s?.feedback||s.fastPause)return;save(n=>{const ss=n.current,q=question(ss.queues[ss.stage][ss.index]);
   if(ss.hint===5&&!ss.replacements.includes(ss.stage+':'+ss.index)){const newRef=ref(C.nextQuestion(n,L,q.skill,q.difficulty,q));ss.queues[ss.stage].splice(ss.index+1,0,newRef);ss.replacements.push(ss.stage+':'+ss.index);}
   ss.index++;ss.feedback=null;ss.hint=0;ss.draft='';ss.draftExpression='';ss.draftUnit='';ss.draftRemainder='';ss.picked='';ss.questionAt=Date.now();
   if(ss.index>=ss.queues[ss.stage].length){if(ss.mode!=='lesson'){ss.stage=5;}else{ss.stage++;ss.index=0;}if(ss.mode==='lesson'&&ss.track==='normal'&&ss.stage===3)ss.hint=2;}
  });ui.toolOpen=false;const ss=current();if(ss.game)setTool(ss.game);
  if(ss.mode!=='lesson'&&ss.stage===5)finishSession();else{render();readAuto();}
 }
 function nextStage(){save(n=>{const s=n.current;s.stage++;s.index=0;s.feedback=null;s.hint=s.stage===3&&s.track==='normal'?2:0;s.picked='';s.draft='';s.draftExpression='';s.draftUnit='';s.draftRemainder='';s.questionAt=Date.now();});ui.toolOpen=false;const sk=skill();setTool(sk.tool,currentQ());render();readAuto();}
 function finishSession(){const existing=current();if(!existing||existing.completed)return;if(existing.track==='olympiad'&&existing.mode==='lesson'&&existing.reflection!==0){toast('再看看本課真正用到的方法。');return;}
  save(n=>{const s=n.current;if(s.completed)return;s.completed=true;s.finishedAt=Date.now();const r=s.results.filter(r=>r.mode!=='guided'&&r.mode!=='challenge-demo'&&r.hint<5),needed=s.track==='olympiad'&&s.mode==='lesson'?3:5;
   const valid=s.mode!=='diagnostic'&&r.length>=needed&&r.filter(r=>r.correct).length>=Math.ceil(needed*.6);
   const sk=L.skills.get(s.skill);
   if(sk){n.lessons[sk.id]={at:s.finishedAt,self:s.self||'',completed:true};if(sk.strategy&&s.reflection===0&&r.filter(r=>r.correct&&r.hint===0).length>=2&&!n.cards.includes(sk.strategy))n.cards.push(sk.strategy);}
   n.sessions.push({id:s.id,skill:s.skill,track:s.track,mode:s.mode,at:s.finishedAt,attempts:r.length,correct:r.filter(r=>r.correct).length});n.sessions=n.sessions.slice(-300);
   // One activity key per skill/day, shared across learning and practice appearances.
   const key=(s.track==='normal'?'normal':'olympiad')+':'+(s.skill||'daily');
   n.outbox=n.outbox.filter(e=>!e.settled||e.day>=C.plusDay(C.hkDay(),-30));
   if(store.profile.persistent&&valid)C.enqueueReward(n,{key,startedAt:s.startedAt,completedAt:s.finishedAt,valid:true});
  });let reward=0,error='';try{reward=store.flush();}catch(e){error=e.message;}
  save(n=>{n.current.award=reward;n.current.rewardError=error;});render();
 }
 function sound(ok){if(!store.state.settings.sound)return;try{audio=audio||new (root.AudioContext||root.webkitAudioContext)();audio.resume();const t=audio.currentTime;[ok?523:330,ok?659:294].forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.0001,t+i*.12);g.gain.exponentialRampToValueAtTime(.045,t+i*.12+.02);g.gain.exponentialRampToValueAtTime(.0001,t+i*.12+.18);o.connect(g);g.connect(audio.destination);o.start(t+i*.12);o.stop(t+i*.12+.2);});}catch(_){toast('裝置暫時未能播放音效；不影響作答。');}}
 function speech(text,lang){if(!('speechSynthesis'in root)){toast('這個瀏覽器沒有讀題功能。');return;}const voices=root.speechSynthesis.getVoices();const match=lang==='yue-HK'?v=>/^(yue|zh[-_]HK)/i.test(v.lang):v=>v.lang.toLowerCase()===lang.toLowerCase();const v=voices.find(match);if(!v){toast(`裝置沒有可用的${lang==='yue-HK'?'粵語':lang==='en-GB'?'英式英文':'普通話'}聲線。文字仍可使用；本版沒有內置真人錄音。`);return;}
  root.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.voice=v;u.rate=store.state.settings.slow?.8:.9;u.onerror=()=>toast('讀題未能完成，請再按一次。');root.speechSynthesis.speak(u);
 }
 function speakQ(){const q=currentQ();if(!q)return;const lang=store.state.settings.voice;speech(lang==='en-GB'?q.stem_en:q.stem_zh,lang);}
 function readAuto(){const q=currentQ();if(q&&store.profile.grade<=2&&!current().feedback){setTimeout(()=>{if(currentQ()?.id===q.id&&active())speakQ();},180);}}
 function download(name,value,type='application/json'){const blob=new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
 async function action(e){const el=e.target.closest?.('[data-action]');if(!el)return;e.preventDefault();const a=el.dataset.action,parts=a.split(':');if(ui.busy)return;tickUsage();ui.busy=true;
  try{
   if(parts[0]==='tool'){toolAction(parts);return;}
   if(parts[0]==='nav'){if(current()&&!current().completed&&view==='lesson'){view='resume';render();return;}view=parts[1];if(view==='tools')setTool(ui.freeTool);render();return;}
   if(parts[0]==='grade'){ui.grade=Number(parts[1]);render();return;}
   if(parts[0]==='lesson'||parts[0]==='practice'||parts[0]==='remedy'||parts[0]==='mistake'){
    if(current()&&!current().completed&&!confirm('結束尚未完成的一輪？已提交答案會保留。'))return;
    ui.forceRemedy=parts[0]==='remedy';makeSession(parts[1],parts[0]==='practice'||parts[0]==='mistake'?'practice':'lesson');
    if(parts[0]==='mistake'){save(n=>n.current.queues[4]=n.current.queues[4].slice(0,2));render();}
    if(parts[0]==='remedy'){save(n=>n.current.stage=1);render();}return;
   }
   if(parts[0]==='daily'||parts[0]==='diagnostic'){if(current()&&!current().completed&&!confirm('結束上一輪？已提交答案會保留。'))return;makePlan(parts[0],parts[1]);return;}
   if(parts[0]==='selecttool'){canStudy();setTool(parts[1]);render();return;}
   if(parts[0]==='game'){const id=parts[1]==='money'?'2N5.3':'1N2.2';makeSession(id,'practice',parts[1]);return;}
   if(parts[0]==='choice'){if(current().feedback)return;save(n=>n.current.picked=currentQ().choices[Number(parts[1])].value);render();return;}
   if(parts[0]==='key'){const f=app.querySelector('#answer');if(!f)return;f.value=parts[1]==='⌫'?f.value.slice(0,-1):(f.value+parts[1]).slice(0,60);f.focus();return;}
   if(parts[0]==='reflect'){save(n=>n.current.reflection=Number(parts[1]));render();return;}
   if(parts[0]==='self'){save(n=>n.current.self=parts[1]);finishSession();return;}
   if(parts[0]==='switch'){bridge.switch(parts[1]);initStore();render();return;}
   if(parts[0]==='term'){speech(parts.slice(1).join(':'),'en-GB');return;}
   switch(a){
    case 'submit':await submit();break;
    case 'nextq':nextQ();break;
    case 'nextstage':nextStage();break;
    case 'finish':finishSession();break;
    case 'hint':{if(current().feedback)return;canStudy();const q=currentQ();save(n=>{n.current.draft=app.querySelector('#answer')?.value||'';n.current.draftExpression=app.querySelector('#expression')?.value||'';n.current.draftUnit=app.querySelector('#unit')?.value||'';n.current.draftRemainder=app.querySelector('#remainder')?.value||'';n.current.hint=Math.min(5,n.current.hint+1);});if(current().hint>=3){setTool(L.skills.get(q.skill).tool,q);ui.toolOpen=true;}render();break;}
    case 'unpause-fast':save(n=>n.current.fastPause=false);render();break;
    case 'speak':speakQ();break;
    case 'pause':view='resume';root.speechSynthesis?.cancel();render();break;
    case 'resume':view='lesson';render();readAuto();break;
    case 'abandon':if(confirm('結束這輪？已提交的作答紀錄會保留。')){save(n=>n.current=null);view='home';render();}break;
    case 'completed-home':case 'completed-parent':save(n=>n.current=null);view=a==='completed-home'?'home':'parent';render();break;
    case 'close':close();break;
    case 'rested':awaitingBreak=false;continuous=0;activeSince=Date.now();render();break;
    case 'create-profile':bridge.add(app.querySelector('#nickname').value,Number(app.querySelector('#new-grade').value),app.querySelector('#consent').checked);initStore();view='home';render();break;
    case 'guest':bridge.guest();initStore();view='home';render();break;
    case 'delete-profile':if(confirm('永久刪除目前學員的本機數學資料？請先匯出備份。')){bridge.remove();initStore();view='profiles';render();}break;
    case 'save-settings':save(n=>{const st=n.settings;st.schoolUnit=app.querySelector('#school').value;st.limit=Number(app.querySelector('#limit').value);st.language=app.querySelector('#language').value;st.voice=app.querySelector('#voice').value;for(const k of ['sound','slow','olympiad','showScore'])st[k]=app.querySelector('#setting-'+k).checked;});toast('安排已儲存。');break;
    case 'sample-speech':{const v=app.querySelector('#voice').value;speech(v==='en-GB'?'Let us try a new way to solve the problem.':'我哋試下用另一個方法去諗。',v);break;}
    case 'export':if(store.readOnly){download('WordQuest_Maths_unreadable_raw.txt',localStorage.getItem(store.key)||'', 'text/plain');toast('已匯出原始資料，沒有覆蓋或自動修復。');}else download('WordQuest_Maths_'+store.profile.id+'.json',store.export());break;
    case 'import':app.querySelector('#import-file').click();app.querySelector('#import-file').onchange=async ev=>{try{const f=ev.target.files[0];if(!f)return;if(f.size>2500000)throw Error('備份大於 2.5 MB');const v=JSON.parse(await f.text());if(confirm('取代目前孩子的數學資料？原英文資料不會改動。')){store.import(v);view='parent';render();toast('數學資料已還原；沒有重新派金幣。');}}catch(err){fail(err);}};break;
    case 'flush':{const n=store.flush();render();toast(n?'已結算 '+n+' 金幣。':'沒有未結算的新增金幣。');break;}
    case 'clear-maths':if(confirm('只清除目前孩子的數學進度？英文內容及英文錢包不變。')){const old=store.state;save(n=>{const b=C.blank();b.wallet=old.wallet;b.settings=old.settings;b.revision=n.revision;Object.assign(n,b);n.current=null;});view='home';render();}break;
    case 'report-item':{const q=currentQ();save(n=>{n.reports.push({template:q.templateId,seed:q.seed,skill:q.skill,at:Date.now()});n.reports=n.reports.slice(-100);});toast('已記低模板和題目種子，會包含在數學備份中；尚未傳送到網上。');break;}
   }
  }catch(err){fail(err);}finally{ui.busy=false;}
 }
 function close(){tickUsage();root.speechSynthesis?.cancel();if(dialog?.open){dialog.close();bridge.afterClose?.();launch?.focus();}activeSince=Date.now();}
 function tickUsage(wasVisible=false){const now=Date.now(),dt=Math.min(15000,Math.max(0,now-activeSince));activeSince=now;if(!dt||!store||(!wasVisible&&!active())||(root.WQM_INTEGRATED&&!dialog?.open)||awaitingBreak||!['lesson','tools','normal','olympiad','home'].includes(view)||store.readOnly)return;continuous+=dt;
  try{save(n=>{const day=C.hkDay(now);n.usage[day]=Math.min(86400000,(n.usage[day]||0)+dt);for(const d of Object.keys(n.usage))if(d<C.plusDay(day,-180))delete n.usage[d];if(n.current&&!n.current.completed)n.current.activeMs=(n.current.activeMs||0)+dt;});if(continuous>=1200000){awaitingBreak=true;root.speechSynthesis?.cancel();render();}}catch(e){ui.error=e.message;}
 }
 function mount(){const host=document.createElement('div');host.id='wqm-app-host';shadow=host.attachShadow({mode:'open'});const style=document.createElement('style');style.textContent=root.WQMathCSS;shadow.append(style);app=document.createElement('main');app.setAttribute('aria-label','WordQuest 數學學習');shadow.append(app);
  app.addEventListener('click',action);app.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='answer'&&!e.isComposing){e.preventDefault();if(!ui.busy){ui.busy=true;submit().catch(fail).finally(()=>ui.busy=false);}}});
  if(root.WQM_INTEGRATED){
   dialog=document.createElement('dialog');dialog.id='wqm-dialog';dialog.setAttribute('aria-label','WordQuest 數學模組');Object.assign(dialog.style,{border:'0',padding:'0',width:'100vw',maxWidth:'100vw',height:'100dvh',maxHeight:'100dvh',margin:'0',background:'#f7f5ec'});dialog.append(host);document.body.append(dialog);dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
   launch=document.createElement('button');launch.id='wqm-launch';launch.textContent='＋ 數學／奧數';launch.type='button';Object.assign(launch.style,{position:'fixed',bottom:'18px',right:'18px',zIndex:'8000',background:'#24564c',color:'#fff',border:'2px solid #d8e6d3',borderRadius:'20px',padding:'13px 18px',font:'700 16px system-ui',boxShadow:'0 4px 16px #0002',cursor:'pointer'});document.body.append(launch);launch.onclick=()=>{
    if(!bridge){alert('未能識別這個英文版本的帳戶或錢包介面。為免損壞資料，數學插件沒有啟動。請使用獨立試玩版，並提供原 HTML 作完整整合測試。');return;}
    try{bridge.beforeOpen?.();initStore();render();dialog.showModal();activeSince=Date.now();app.querySelector('button')?.focus();}catch(e){alert(e.message);}
   };
  }else{document.body.style.margin='0';document.body.append(host);initStore();render();}
  setInterval(tickUsage,15000);
  document.addEventListener('visibilitychange',()=>{if(document.hidden){tickUsage(true);root.speechSynthesis?.cancel();audio?.suspend();}activeSince=Date.now();});
  root.addEventListener('pagehide',()=>{tickUsage(true);root.speechSynthesis?.cancel();audio?.suspend();});
  // Diagnostics expose the deterministic content engine, never host account credentials.
  root.WQMathApp=Object.freeze({version:'0.1.0',getState:()=>C.clone(store?.state),getView:()=>view,contentStats:()=>({skills:L.skills.size,templates:L.templates.size}),hostConnected:()=>bridge?.mode==='wordquest'});
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})(globalThis);
