/** Optional local-only server. Node 20+ built-ins; key remains in server environment.
 * Not a public multi-tenant production service. Never bind to 0.0.0.0 unchanged.
 */
import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
const APP=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../app');
const VOICES={'zh-HK-HiuMaanNeural':'zh-HK','zh-HK-WanLungNeural':'zh-HK','zh-HK-HiuGaaiNeural':'zh-HK','en-GB-SoniaNeural':'en-GB','zh-CN-XiaoxiaoNeural':'zh-CN'};
const xml=s=>s.replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
export function speechBody(v){if(!v||typeof v.text!=='string'||!v.text.trim()||v.text.length>1200||!VOICES[v.voice]||!['yue-HK','zh-HK','en-GB','zh-CN'].includes(v.lang)||typeof v.slow!=='boolean')throw Error('Invalid speech request');const lang=VOICES[v.voice];if((v.lang==='yue-HK'?'zh-HK':v.lang)!==lang)throw Error('Voice language mismatch');return `<speak version="1.0" xml:lang="${lang}"><voice name="${v.voice}"><prosody rate="${v.slow?'-20%':'-10%'}">${xml(v.text)}</prosody></voice></speak>`;}
export function makeServer({key=process.env.AZURE_SPEECH_KEY,region=process.env.AZURE_SPEECH_REGION,fetcher=fetch,app=APP}={}){let active=0,hits=[];
 const send=(res,code,data,type='application/json')=>{res.writeHead(code,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer'});res.end(type==='application/json'?JSON.stringify(data):data);};
 return http.createServer(async(req,res)=>{try{const port=req.socket.localPort,allowed=new Set(['127.0.0.1:'+port,'localhost:'+port]);if(!allowed.has(req.headers.host))return send(res,403,{error:'Invalid local host'});const u=new URL(req.url,'http://'+req.headers.host);
 if(u.pathname==='/api/speech'){if(req.method!=='POST')return send(res,405,{error:'POST required'});if(req.headers.origin!=='http://'+req.headers.host||req.headers['x-wordquest-speech']!=='1'||req.headers['content-type']?.split(';')[0]!=='application/json')return send(res,403,{error:'Same-origin JSON request required'});if(!key||!region||!/^[a-z0-9-]{3,30}$/.test(region))return send(res,503,{error:'Speech service not configured'});hits=hits.filter(t=>t>Date.now()-600000);if(hits.length>=60||active>=2)return send(res,429,{error:'Local speech limit reached'});const chunks=[];let bytes=0;for await(const part of req){bytes+=part.length;if(bytes>10000)return send(res,413,{error:'Body too large'});chunks.push(Buffer.from(part));}let ssml;try{ssml=speechBody(JSON.parse(Buffer.concat(chunks).toString('utf8')));}catch(_){return send(res,400,{error:'Invalid speech request'});}active++;hits.push(Date.now());try{const upstream=await fetcher('https://'+region+'.tts.speech.microsoft.com/cognitiveservices/v1',{method:'POST',headers:{'Ocp-Apim-Subscription-Key':key,'Content-Type':'application/ssml+xml','X-Microsoft-OutputFormat':'audio-24khz-48kbitrate-mono-mp3','User-Agent':'WordQuest-R3'},body:ssml,signal:AbortSignal.timeout(18000)});if(!upstream.ok)return send(res,502,{error:'Speech provider failed'});const b=Buffer.from(await upstream.arrayBuffer());if(!b.length||b.length>6000000)return send(res,502,{error:'Invalid speech response size'});return send(res,200,b,'audio/mpeg');}catch(_){return send(res,502,{error:'Speech provider unavailable'});}finally{active--;}}
 if(!['GET','HEAD'].includes(req.method))return send(res,405,{error:'Method not allowed'});let rel;try{rel=decodeURIComponent(u.pathname);}catch(_){return send(res,400,{error:'Invalid path'});}if(rel.includes('\0')||rel.includes('\\')||rel.split('/').some(p=>p.startsWith('.')))return send(res,403,{error:'Path refused'});if(rel==='/app'||rel==='/app/')rel='/index.html';else if(rel.startsWith('/app/'))rel=rel.slice(4);const target=path.resolve(app,'.'+(rel==='/'?'/index.html':rel));if(!target.startsWith(app+path.sep))return send(res,403,{error:'Path refused'});let real;try{real=await fs.realpath(target);}catch(_){return send(res,404,{error:'File not found'});}if(!real.startsWith(app+path.sep))return send(res,403,{error:'Path refused'});const stat=await fs.stat(real);if(!stat.isFile())return send(res,404,{error:'File not found'});const type={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.wasm':'application/wasm','.gz':'application/gzip','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml'}[path.extname(real)]||'application/octet-stream';res.writeHead(200,{'Content-Type':type,'Content-Length':stat.size,'Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY'});res.end(req.method==='HEAD'?undefined:await fs.readFile(real));
 }catch(_){if(!res.headersSent)send(res,500,{error:'Local request failed'});else res.end();}});
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const port=Number(process.env.WORDQUEST_PORT||8765);if(!Number.isInteger(port)||port<1024||port>65535)throw Error('Port must be 1024–65535');makeServer().listen(port,'127.0.0.1',()=>console.log('WordQuest local app: http://127.0.0.1:'+port+'/app/index.html\nClose this terminal to stop. Speech API key is never printed.'));}
