/* R3 host integration; inserted INSIDE the existing private English closure.
   No password hashes, account registry, API key or mutable db is exposed. */
const F3=window.WQFamilyCore;
let r3Busy=false,r3SettingsCache=null,r3SettingsRaw=null,r3SettingsOwner='',r3LastTick=performance.now(),r3LastScope='',r3LimitDialog=null,r3LastFamilySave=0;
const r3FamilyKey=(a=accountId())=>'wq-r3-family:'+a;
const r3Marker=(a=accountId())=>'wq-r3-recovery:'+a;
const r3MathKey=(cid,a=accountId())=>'wqm-state-v1:'+a+':'+cid;
const r3Clone=F3.clone;
function r3Settings(){const owner=accountId()||'guest';if(owner!==r3SettingsOwner){r3SettingsOwner=owner;r3SettingsRaw=owner==='guest'?null:localStorage.getItem(r3FamilyKey());r3SettingsCache=r3SettingsRaw?F3.validateSettings(JSON.parse(r3SettingsRaw)):F3.defaults();}return r3SettingsCache;}
function r3ReloadSettings(){r3SettingsOwner='';return r3Settings();}
function r3SaveSettings(next){if(!isLoggedIn())throw Error('請先登入家庭帳戶');if(r3Busy||!v24CanWrite())throw Error('目前沒有寫入權，設定未更改');const key=r3FamilyKey();if(localStorage.getItem(key)!==r3SettingsRaw)throw Error('另一個分頁更新了跨科資料，請重新開啟');next=F3.validateSettings(next);next.revision++;const raw=JSON.stringify(next);localStorage.setItem(key,raw);r3SettingsCache=next;r3SettingsRaw=raw;}
function r3Parent(){if(!isLoggedIn()){go('login');render();throw Error('先登入家庭帳戶');}if(!v24RequireParent(true)||!v23HasLease())throw Error('請先完成家長驗證並取得編輯權');if(r3Busy)throw Error('資料處理尚未完成，暫停其他寫入');}
function r3PauseWork(){if(window.WQMathApp?.close()===false)throw Error('數學草稿未能儲存，未開始資料操作');if(!pgPause())throw Error('街機未能暫停');if(arEngine&&!arEngine.paused)arPause();stopSpeech();fgResetAudio();pcStop();if(!save())throw Error('現有資料未儲存，未開始資料操作');}
async function r3Digest(value){if(!crypto.subtle)throw Error('需要 HTTPS 或 localhost 的原生密碼運算介面；未產生未校驗備份');const bytes=new TextEncoder().encode(typeof value==='string'?value:JSON.stringify(value));return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');}
const r3BlobURL=blob=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error||Error('媒體讀取失敗'));r.readAsDataURL(blob);});
function r3DataBlob(row){const raw=atob(row.data.split(',')[1]),a=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)a[i]=raw.charCodeAt(i);return new Blob([a],{type:row.mime});}
function r3Download(name,data,mime='application/json'){const blob=new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type:mime});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function r3OwnedKeys(a=accountId()){const main=DBKEY_PREFIX+a,mp='wqm-state-v1:'+a+':';return Array.from({length:localStorage.length},(_,i)=>localStorage.key(i)).filter(k=>k===main||k===main+'-before-restore'||k===main+'-v24-protection'||k===r3FamilyKey(a)||k?.startsWith(mp)||k?.startsWith('wordquest-v32-characters:normal:'+a+':')||k?.startsWith('wordquest-v32-characters:sandbox:'+a+':'));}
function r3ReadKV(a=accountId()){return Object.fromEntries(r3OwnedKeys(a).map(k=>[k,localStorage.getItem(k)]));}
// A separate durable IndexedDB journal supports recovery across localStorage and media transactions.
function r3OpenJournal(){return new Promise((resolve,reject)=>{const r=indexedDB.open('wordquest-family-journal-r3',1);r.onupgradeneeded=()=>r.result.createObjectStore('transactions',{keyPath:'owner'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||Error('無法建立復原日誌'));r.onblocked=()=>reject(Error('請關閉其他分頁再重試'));});}
async function r3Journal(mode,row){const d=await r3OpenJournal();try{return await new Promise((resolve,reject)=>{const tx=d.transaction('transactions',mode==='get'?'readonly':'readwrite'),s=tx.objectStore('transactions');const r=mode==='get'?s.get(row):mode==='delete'?s.delete(row):s.put(row);let value;r.onsuccess=()=>value=r.result;tx.oncomplete=()=>resolve(value);tx.onabort=()=>reject(tx.error||Error('復原日誌儲存失敗'));tx.onerror=()=>{};});}finally{d.close();}}
async function r3ReplaceMedia(owner,rows){const d=await openMediaDb();return new Promise((resolve,reject)=>{const tx=d.transaction('assets','readwrite'),s=tx.objectStore('assets'),r=s.index('owner').getAllKeys(owner);r.onsuccess=()=>{for(const key of r.result)s.delete(key);for(const row of rows)s.put({...row,id:recordId(owner,row.key),owner});};tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error||Error('媒體交易失敗'));tx.onerror=()=>{};});}
function r3ReplaceKV(owner,values){for(const k of r3OwnedKeys(owner))if(!Object.hasOwn(values,k))localStorage.removeItem(k);for(const [k,v]of Object.entries(values))if(v===null)localStorage.removeItem(k);else localStorage.setItem(k,v);}
async function r3Transaction(values,media,label){
 r3Parent();r3PauseWork();const owner=accountId(),intent=v23Owner(),beforeDb=r3Clone(db),before=r3ReadKV(owner),inert=document.body.inert;let prepared=false,committed=false,journalWritten=false;r3Busy=true;document.body.inert=true;
 const unchanged=()=>{if(owner!==accountId()||intent!==v23Owner()||!v23ParentAllowed()||!v23HasLease())throw Error('身份或授權已改變');};
 try{const ek=DBKEY_PREFIX+owner;if(values[ek]){const next=JSON.parse(values[ek]);next.writeRevision=(db.writeRevision||0)+1;values[ek]=JSON.stringify(next);}const beforeMedia=await readMediaOwner(owner);unchanged();
  await r3Journal('put',{owner,before,beforeMedia,at:Date.now(),label});journalWritten=true;localStorage.setItem(r3Marker(owner),'prepared');prepared=true;unchanged();r3ReplaceKV(owner,values);await r3ReplaceMedia(owner,media);unchanged();localStorage.setItem(r3Marker(owner),'committed');committed=true;
  await r3Journal('delete',owner);localStorage.removeItem(r3Marker(owner));prepared=false;db=validateDb(JSON.parse(localStorage.getItem(ek)));loadBlocked=false;persistenceIssue='';r3ReloadSettings();stopMediaPlayback();revokeMediaUrls();mediaOwner='';mediaPromise=null;await syncMediaOwner(true);cancelAnimationFrame(arFrame);arEngine=null;pgGame=null;pgPlaying=false;
 }catch(e){if(committed){loadBlocked=true;persistenceIssue='資料已提交，但收尾未完成；請用恢復中斷交易完成處理。';showSaveIssue();throw Error(persistenceIssue);}
  if(prepared){try{const j=await r3Journal('get',owner);if(!j)throw Error('找不到復原日誌');r3ReplaceKV(owner,j.before);await r3ReplaceMedia(owner,j.beforeMedia);localStorage.setItem(r3Marker(owner),'rolled-back');await r3Journal('delete',owner);localStorage.removeItem(r3Marker(owner));db=owner===accountId()?beforeDb:load();r3ReloadSettings();}catch(rollback){loadBlocked=true;persistenceIssue='資料交易中斷，復原日誌已保留。請勿清除瀏覽器資料：'+rollback.message;showSaveIssue();throw Error(persistenceIssue);}}
  else if(journalWritten){try{await r3Journal('delete',owner);}catch(_){} }throw e;
 }finally{r3Busy=false;document.body.inert=inert;}window.dispatchEvent(new Event('wq-r3-data-replaced'));render();
}
async function r3Recover(){
 if(!isLoggedIn()||!localStorage.getItem(r3Marker()))return false;if(!v23ParentAllowed()){v24RequireParent(false);throw Error('請先完成家長驗證，再按恢復中斷交易');}if(!v23HasLease())throw Error('請先取得目前分頁的編輯權');const owner=accountId(),inert=document.body.inert;r3Busy=true;document.body.inert=true;
 try{const marker=localStorage.getItem(r3Marker(owner)),j=await r3Journal('get',owner);if(!['prepared','committed','rolled-back'].includes(marker))throw Error('未知交易狀態，沒有修改資料');if(marker==='prepared'){if(!j)throw Error('復原日誌遺失，不能安全恢復。請保留資料並從家庭備份還原。');r3ReplaceKV(owner,j.before);await r3ReplaceMedia(owner,j.beforeMedia);localStorage.setItem(r3Marker(owner),'rolled-back');}if(j)await r3Journal('delete',owner);localStorage.removeItem(r3Marker(owner));loadBlocked=false;persistenceIssue='';db=load();r3ReloadSettings();await syncMediaOwner(true);window.dispatchEvent(new Event('wq-r3-data-replaced'));toast(marker==='committed'?'已完成已提交交易的收尾。':'已恢復交易前資料。');return true;
 }finally{r3Busy=false;document.body.inert=inert;render();}
}
async function r3Export(){r3Parent();r3PauseWork();const owner=accountId(),intent=v23Owner(),raw=localStorage.getItem(dbKey()),familyRaw=localStorage.getItem(r3FamilyKey()),MC=window.WQMathCore,lib=MC.library(window.WQMathData);const english=validateDb(r3Clone(db));const math=english.children.map(c=>{const a=localStorage.getItem(r3MathKey(c.id)),b=localStorage.getItem(r3MathKey(c.id)+':before-restore');return {childId:c.id,state:a?MC.validateState(JSON.parse(a),lib):null,recovery:b?MC.validateState(JSON.parse(b),lib):null};});const allKeys=r3ReadKV();const rows=await readMediaOwner(owner),media=[];for(const row of rows){const {blob,id,owner:ignored,key,kind,...meta}=row;const entry={key,kind,meta};if(blob instanceof Blob){entry.mime=blob.type;entry.data=await r3BlobURL(blob);}media.push(entry);}if(owner!==accountId()||intent!==v23Owner()||!v23ParentAllowed()||raw!==localStorage.getItem(dbKey())||familyRaw!==localStorage.getItem(r3FamilyKey())||JSON.stringify(allKeys)!==JSON.stringify(r3ReadKV()))throw Error('匯出期間資料有變動，請暫停學習後重試；沒有產生不一致備份');const family=r3Clone(r3Settings());const characterPreferences=[];for(const c of english.children)for(const mode of ['normal','sandbox']){const raw=localStorage.getItem('wordquest-v32-characters:'+mode+':'+owner+':'+c.id);if(raw)characterPreferences.push({childId:c.id,mode,preferences:JSON.parse(raw)});}const payload={sourceOwner:owner,english,math,family,media,characterPreferences};F3.validatePayload(payload,validateDb,MC,lib);const pack={format:'wordquest-family',version:1,createdAt:new Date().toISOString(),appVersion:'R3.0.0',warning:'含學員姓名及學習紀錄，未加密；不含帳戶密碼或API金鑰。',payload,integrity:{algorithm:'SHA-256',digest:await r3Digest(payload)}};r3Download('WordQuest_Family_R3_'+F3.day()+'.json',pack);return pack;}
async function r3ValidatePack(file){if(!file||file.size>140000000)throw Error('家庭備份超過140 MB或未選檔案');const pack=F3.envelope(JSON.parse(await file.text()));if(await r3Digest(pack.payload)!==pack.integrity.digest)throw Error('備份校驗失敗：檔案可能不完整或曾被修改，沒有寫入資料');return F3.validatePayload(pack.payload,validateDb,window.WQMathCore,window.WQMathCore.library(window.WQMathData));}
async function r3Restore(payload){r3Parent();const MC=window.WQMathCore,owner=accountId();const clean=F3.validatePayload(payload,validateDb,MC,MC.library(window.WQMathData));const english=clean.english;
 if(clean.sourceOwner===owner){
  for(const c of english.children){const old=db.children.find(o=>o.id===c.id);if(old)c.stars=old.stars;}
  if(db.arcadeV28&&english.arcadeV28){for(const cid of Object.keys(english.arcadeV28.children||{}))if(db.arcadeV28.children?.[cid])english.arcadeV28.children[cid]=r3Clone(db.arcadeV28.children[cid]);}
  for(const name of ['dailyLedger']){english[name]=english[name]||{};for(const c of english.children)if(db[name]?.[c.id])english[name][c.id]=r3Clone(db[name][c.id]);}
  const current=r3Settings();for(const cid of english.children.map(c=>c.id))for(const [day,row] of Object.entries(current.usage[cid]||{})){const days=clean.family.usage[cid]||(clean.family.usage[cid]={}),prev=days[day]||(days[day]={english:0,math:0,olympiad:0,arcade:0});for(const subject of Object.keys(prev))prev[subject]=Math.max(prev[subject],row[subject]||0);}
  F3.validateSettings(clean.family);validateDb(english);
 }
 english.writeRevision=(db.writeRevision||0)+1;const values={[dbKey()]:JSON.stringify(english),[r3FamilyKey()]:JSON.stringify(clean.family)};for(const m of clean.math){if(m.state)values[r3MathKey(m.childId)]=JSON.stringify(m.state);if(m.recovery)values[r3MathKey(m.childId)+':before-restore']=JSON.stringify(m.recovery);}for(const row of clean.characterPreferences)values['wordquest-v32-characters:'+row.mode+':'+owner+':'+row.childId]=JSON.stringify(row.preferences);const media=clean.media.map(row=>({...row.meta,key:row.key,kind:row.kind,...(row.kind==='note'?{}:{blob:r3DataBlob(row)}),owner,updatedAt:new Date().toISOString()}));await r3Transaction(values,media,'restore-family');toast('家庭備份已還原。所有孩子、數學及媒體均已處理；歷史數學獎勵不重派。');}
resetAll=async function(){try{r3Parent();if(!confirm('清除目前家庭的英文、數學、奧數、街機、跨科使用紀錄、自訂圖片／音訊及所有本機復原副本？其他家庭不受影響。請先匯出家庭完整備份。'))return;const fresh=isTestAdmin()?adminInitialDb():upgradeDb(newUserDb('小朋友'));fresh.writeRevision=(db.writeRevision||0)+1;await r3Transaction({[dbKey()]:JSON.stringify(fresh)},[],'reset-family');clearMiniTimers();miniGame=null;clearImportDraft();r3SettingsOwner='';go('parent');render();toast('目前家庭資料及相關復原副本已清除。');}catch(e){toast(e.message,'bad');}};
const r3PriorSave=save;save=function(){if(r3Busy||isLoggedIn()&&localStorage.getItem(r3Marker())){persistenceIssue='家庭資料處理或恢復未完成，暫停其他儲存。';showSaveIssue();return false;}return r3PriorSave.apply(this,arguments);};
function r3Weekly(){const c=activeChild(),raw=isLoggedIn()?localStorage.getItem(r3MathKey(c.id)):null;let math=null;if(raw)math=window.WQMathCore.validateState(JSON.parse(raw),window.WQMathCore.library(window.WQMathData));return F3.weekly(db,math,c.id);}
function r3ReportHTML(){const r=r3Weekly(),set=r3Settings(),c=activeChild(),labels={english:'英文',normal:'普通數學',olympiad:'奧數'};return `<h2>${esc(c.name)} · 跨科週報</h2><p>${r.from} 至 ${r.to}。只計實際作答，沒有紀錄不作估計。</p><div class="r3-table"><table><thead><tr><th>學科</th><th>作答次數</th><th>全對次數</th><th>曾用提示</th></tr></thead><tbody>${Object.entries(r.rows).map(([k,v])=>`<tr><td>${labels[k]}</td><td>${v.attempts}</td><td>${v.correct}</td><td>${v.assisted}</td></tr>`).join('')}</tbody></table></div><h3>數學重溫優先</h3><p>${r.mathWeak.length?r.mathWeak.map(x=>esc(window.WQMathData.skills.find(s=>s.id===x.skill)?.name_zh||x.skill)+'（'+x.score+'%）').join('、'):'未有低於80%的已作答技能紀錄。'}</p><p>今天全站已用 ${Math.ceil(F3.usageTotal(set,c.id)/60000)}／${set.limitMinutes} 分鐘。跨科計時由R3啟用起記錄，不回填舊版的未知時段。</p><button class="btn secondary" data-r3="download-report">匯出週報</button>`;}
function r3Dialog(title,html){document.getElementById('r3-dialog')?.remove();const d=document.createElement('dialog');d.id='r3-dialog';d.className='r3-dialog';d.innerHTML=`<div class="r3-dialog-head"><h1>${esc(title)}</h1><button class="btn quiet" data-r3="close">關閉</button></div><div id="r3-dialog-body">${html}</div><p id="r3-status" role="status" aria-live="polite"></p>`;document.body.append(d);d.showModal();d.querySelector('button')?.focus();return d;}
function r3Panel(){r3Parent();const s=r3Settings();r3Dialog('家庭備份與跨科安排',`<div class="notice">備份包括全部孩子的英文、普通數學、奧數、街機、跨科設定及自訂媒體。不包含登入密碼；請把檔案當成私人資料保管。</div><div class="r3-grid"><section><h2>一次備份整個家庭</h2><button class="btn primary" data-r3="export-family">匯出家庭完整備份</button><button class="btn secondary" data-r3="choose-family">還原家庭備份</button><input id="r3-family-file" type="file" accept=".json,application/json" hidden><p>還原前先顯示所有孩子及紀錄數，確認後才取代目前家庭資料。</p><button class="btn soft" data-r3="recover">恢復中斷交易</button><button class="btn soft" data-r3="legacy-math">搬入舊數學紀錄</button></section><section><h2>每天的安排</h2><label>全站總時限（包括街機，分鐘）<input id="r3-limit" type="number" min="5" max="180" value="${s.limitMinutes}"></label><label>英文建議分鐘<input id="r3-english" type="number" min="0" max="60" value="${s.englishMinutes}"></label><label>普通數學建議分鐘<input id="r3-math" type="number" min="0" max="60" value="${s.mathMinutes}"></label><label>奧數建議分鐘（0即不安排）<input id="r3-olympiad" type="number" min="0" max="60" value="${s.olympiadMinutes}"></label><button class="btn primary" data-r3="save-plan">儲存安排</button><p>這是同一瀏覽器的家長時限，不是伺服器防作弊或系統級螢幕管理。</p></section></div><section>${r3ReportHTML()}</section><section><h2>讀題聲線</h2><label>模式<select id="r3-voice-mode"><option value="device" ${s.voice.mode==='device'?'selected':''}>裝置聲線（離線可用性按裝置）</option><option value="server" ${s.voice.mode==='server'?'selected':''}>自設語音服務</option></select></label><label>同網站服務路徑<input id="r3-voice-endpoint" value="${esc(s.voice.endpoint||'/api/speech')}" maxlength="240"></label><label>聲線代號<input id="r3-voice-id" value="${esc(s.voice.voice)}" maxlength="32"></label><label><input id="r3-voice-consent" type="checkbox" ${s.voice.consent?'checked':''}>同意把讀題及英文教材文字傳到設定的語音服務（不傳孩子姓名）</label><button class="btn secondary" data-r3="save-voice">儲存聲線設定</button><p>未部署服務或未設定伺服器金鑰時，不會聲稱固定聲線已可用；API金鑰不得貼在此處。</p></section>`);}
function r3Plan(){const s=r3Settings(),c=activeChild(),r=r3Weekly();r3Dialog('今天的跨科學習',`<p>${esc(c.name)}，按以下次序完成今天的小目標。每個入口沿用原有作答及獎勵規則。</p><div class="r3-grid">${[['english','英文',s.englishMinutes,'溫習到期及較弱的英文項目'],['math','普通數學',s.mathMinutes,'先重溫弱項，再按學校單元練習'],['olympiad','奧數思維',s.olympiadMinutes,'自願加入，進度不與普通數學混合']].filter(x=>x[2]>0).map(([key,n,min,description])=>`<section><h2>${n}</h2><p>建議 ${min} 分鐘</p><p>${description}</p><button class="btn primary" data-r3="study-${key}">開始${n}</button></section>`).join('')}</div><p>今天全站已用 ${Math.ceil(F3.usageTotal(s,c.id)/60000)}／${s.limitMinutes} 分鐘。</p>`);}
function r3Decorate(){if(isLoggedIn()&&localStorage.getItem(r3Marker())&&!document.getElementById('r3-recovery-banner')){const b=document.createElement('aside');b.id='r3-recovery-banner';b.className='dangerbox';b.innerHTML='<strong>上次家庭資料交易尚未完成，已暫停寫入。</strong> <button class=\"btn secondary\" data-r3=\"recover\">恢復中斷交易</button>';document.getElementById('app')?.prepend(b);} const route=(location.hash||'#kid').slice(1).split('?')[0];if(route==='kid'&&!document.getElementById('r3-daily')){const box=document.createElement('section');box.id='r3-daily';box.className='card pad';box.innerHTML='<h2>英文、數學與思維，一次安排</h2><p>保留每科的獨立進度，用同一個每日時間安排。</p><button class="btn primary" data-r3="daily">今天的跨科任務</button>';document.getElementById('app')?.prepend(box);}if(['settings','parent','report'].includes(route)&&v23ParentAllowed()&&!document.getElementById('r3-family-entry')){const box=document.createElement('section');box.id='r3-family-entry';box.className='card pad';box.innerHTML='<h2>家庭完整備份與跨科安排</h2><p>一次備份英文、數學、奧數、街機及自訂媒體，也可搬入舊數學學員紀錄。</p><button class="btn primary" data-r3="family">打開家庭管理</button>';document.getElementById('app')?.prepend(box);}const badge=document.getElementById('v25-build-badge');if(badge)badge.textContent='WordQuest R3 · 家庭整合升級';}
const r3Render=render;render=function(){const out=r3Render.apply(this,arguments);r3Decorate();return out;};
let r3PendingRestore=null,r3PendingOwner='';
document.addEventListener('change',async e=>{if(e.target.id!=='r3-family-file')return;try{r3Parent();r3PauseWork();const targetOwner=accountId();r3PendingRestore=await r3ValidatePack(e.target.files[0]);if(targetOwner!==accountId())throw Error('帳戶已改變，請重新選取備份');r3PendingOwner=targetOwner;const p=r3PendingRestore;r3Dialog('確認還原家庭',`<div class="dangerbox">會取代目前家庭的孩子、教材、進度及媒體，不是合併。登入密碼不變。同一家庭還原會保留目前金幣、街機局面及較高使用時間，避免重複免費入場。建議先匯出目前家庭備份。</div><ul>${p.english.children.map(c=>`<li>${esc(c.name)}（小${c.grade}） · 數學 ${(p.math.find(m=>m.childId===c.id)?.state?.attempts||[]).length} 次作答</li>`).join('')}</ul><p>英文 ${p.english.attempts.length} 筆紀錄；自訂媒體 ${p.media.length} 項。</p><label><input id="r3-restore-consent" type="checkbox">我已核對，確定取代目前家庭</label><button class="btn primary" data-r3="confirm-restore">確認還原</button>`);}catch(err){r3Status(err.message,true);}finally{e.target.value='';}});
function r3Status(text,bad=false){const x=document.getElementById('r3-status');if(x){x.textContent=text;x.className=bad?'dangerbox':'notice';}else toast(text,bad?'bad':undefined);}
document.addEventListener('click',async e=>{const b=e.target.closest?.('[data-r3]');if(!b)return;const act=b.dataset.r3;e.preventDefault();try{if(act==='close'){document.getElementById('r3-dialog')?.close();return;}if(act==='family'){r3Panel();return;}if(act==='daily'){r3Plan();return;}if(act.startsWith('study-')){window.WQR3.assertStudy();document.getElementById('r3-dialog')?.close();const sub=act.slice(6);if(sub==='english'){go('kid');render();startDaily();}else{window.WQMathApp.open(sub==='math'?'normal':'olympiad');window.WQMathApp.startDaily?.(sub==='math'?'normal':'olympiad');}return;}
 if(act==='recover'){const done=await r3Recover();r3Status(done?'復原完成。':'沒有待恢復的家庭交易。');return;}r3Parent();b.disabled=true;if(act==='export-family'){await r3Export();r3Status('完整家庭備份已產生，請保留下載檔。');}else if(act==='choose-family')document.getElementById('r3-family-file').click();else if(act==='confirm-restore'){if(!document.getElementById('r3-restore-consent').checked)throw Error('請先核對並勾選取代確認');if(!r3PendingRestore||r3PendingOwner!==accountId())throw Error('帳戶已改變或未選擇備份，請重新選擇');await r3Restore(r3PendingRestore);r3PendingRestore=null;document.getElementById('r3-dialog')?.close();}else if(act==='recover'){const done=await r3Recover();r3Status(done?'復原完成。':'沒有待恢復的家庭交易。');}else if(act==='legacy-math'){document.getElementById('r3-dialog')?.close();window.WQMathApp.open('parent');toast('在數學家長頁按「搬入舊學員紀錄」，核對來源與目前孩子。');}else if(act==='save-plan'){const n=r3Clone(r3Settings());n.limitMinutes=Number(document.getElementById('r3-limit').value);n.englishMinutes=Number(document.getElementById('r3-english').value);n.mathMinutes=Number(document.getElementById('r3-math').value);n.olympiadMinutes=Number(document.getElementById('r3-olympiad').value);r3SaveSettings(n);r3Status('跨科安排已儲存。');}else if(act==='download-report'){r3Download('WordQuest_Weekly_'+F3.day()+'.json',{profile:{name:activeChild().name,grade:activeChild().grade},report:r3Weekly()});}else if(act==='save-voice'){const n=r3Clone(r3Settings());n.voice={mode:document.getElementById('r3-voice-mode').value,endpoint:document.getElementById('r3-voice-endpoint').value,voice:document.getElementById('r3-voice-id').value,consent:document.getElementById('r3-voice-consent').checked};if(n.voice.mode==='server'&&!n.voice.consent)throw Error('未同意傳送題目文字；沒有開啟語音服務');r3SaveSettings(n);r3Status('設定已儲存；須另行部署語音服務才能使用。');}}catch(err){r3Status(err.message,true);}finally{b.disabled=false;}});
function r3CurrentSubject(){if(document.getElementById('wqm-dialog')?.open){const v=window.WQMathApp?.getView();if(['parent','profiles','resume'].includes(v))return null;return window.WQMathApp?.getState()?.current?.track==='olympiad'||v==='olympiad'?'olympiad':'math';}const rt=(location.hash||'#kid').slice(1).split('?')[0];if(pgPlaying||arEngine&&!arEngine.paused||miniGame&&!miniGame.ended)return 'arcade';if(['learn','learning','assembly-learn','family-lesson','phonics-lesson','practice','quiz','test'].includes(rt))return 'english';return null;}
function r3Tick(){const now=performance.now(),dt=Math.min(2500,Math.max(0,now-r3LastTick));r3LastTick=now;const sc=(accountId()||'guest')+':'+activeChild()?.id;if(r3LastScope!==sc){r3LastScope=sc;return;}if(document.hidden||!document.hasFocus()||r3Busy||document.getElementById('r3-dialog')?.open||!isLoggedIn()||!v24CanWrite())return;const subject=r3CurrentSubject();if(!subject)return;try{const n=r3Clone(r3Settings());F3.addUsage(n,activeChild().id,subject,dt);r3SaveSettings(n);if(F3.usageTotal(n,activeChild().id)>=n.limitMinutes*60000)r3Block();}catch(e){persistenceIssue='全站計時未能儲存，已暫停學習：'+e.message;showSaveIssue();r3Block(true);}}
function r3Block(storageFailure=false){pgPause();if(arEngine&&!arEngine.paused)arPause();stopSpeech();window.WQMathApp?.pauseForLimit?.();if(document.getElementById('r3-time-limit')?.open)return;const d=document.createElement('dialog');d.id='r3-time-limit';d.className='r3-dialog';d.innerHTML=`<h1>${storageFailure?'資料暫時未能保存':'今天先到這裏'}</h1><p>${storageFailure?'請保留本頁，檢查儲存或匯出備份。':'已達家庭設定的全站時限。英文、數學與街機共用同一時限，家長可驗證後調整。'}</p><button class="btn primary" id="r3-limit-home">返回主頁</button>`;document.body.append(d);d.showModal();d.addEventListener('cancel',e=>e.preventDefault());d.querySelector('button').onclick=()=>{d.close();d.remove();window.WQMathApp?.close();go('kid');render();};}
window.WQR3=Object.freeze({version:'R3.0.0',dataBusy:()=>r3Busy,assertStudy(){if(r3Busy||isLoggedIn()&&localStorage.getItem(r3Marker()))throw Error('家庭資料交易未完成，請先在家長頁恢復');if(isLoggedIn()){const s=r3Settings();if(F3.usageTotal(s,activeChild().id)>=s.limitMinutes*60000)throw Error('已達今天的全站時限，請休息或由家長調整。');}},voice:()=>r3Clone(r3Settings().voice),canPlay:()=>{try{window.WQR3.assertStudy();return true;}catch(e){toast(e.message,'bad');return false;}},recordMigration(digest,target){const n=r3Clone(r3Settings());if(n.migrationReceipts.some(r=>r.digest===digest&&r.target===target))throw Error('這份舊備份已搬入目前孩子，沒有重複搬入');n.migrationReceipts.push({digest,target,at:Date.now()});n.migrationReceipts=n.migrationReceipts.slice(-300);r3SaveSettings(n);},hasMigration:(digest,target)=>r3Settings().migrationReceipts.some(r=>r.digest===digest&&r.target===target),remaining:()=>Math.max(0,r3Settings().limitMinutes*60000-F3.usageTotal(r3Settings(),activeChild()?.id)),openFamily:()=>r3Panel()});
setInterval(r3Tick,1000);document.addEventListener('visibilitychange',()=>r3LastTick=performance.now());window.addEventListener('blur',()=>r3LastTick=performance.now());window.addEventListener('focus',()=>r3LastTick=performance.now());window.addEventListener('storage',e=>{if(e.key===r3FamilyKey()){r3SettingsOwner='';try{r3Settings();}catch(err){r3Status(err.message,true);}}});

document.addEventListener('click',e=>{if(r3Busy&&!e.target.closest?.('#r3-dialog')){e.preventDefault();e.stopImmediatePropagation();}},true);

// Every effective game entry is guarded BEFORE buying or resuming a ticket.
const r3PriorPgBuy=pgBuy;pgBuy=async function(){if(!WQR3.canPlay())return;return r3PriorPgBuy.apply(this,arguments);};
const r3PriorPgPlay=pgPlay;pgPlay=async function(){if(!WQR3.canPlay())return;return r3PriorPgPlay.apply(this,arguments);};
const r3PriorArPlay=arPlay;arPlay=async function(){if(!WQR3.canPlay())return;return r3PriorArPlay.apply(this,arguments);};
if(isLoggedIn()&&localStorage.getItem(r3Marker())){loadBlocked=true;persistenceIssue='上次家庭交易中斷，請先恢復中斷交易。';}
