/* Optional offline OCR installer and server speech client. No bundled claim is made. */
const r3Base=new URL('./',/^(https?|file):/.test(location.protocol)?location.href:'https://unavailable.invalid/'),r3ConfigCache='wordquest-r3-config',r3Pointer=new URL('ocr-active.json',r3Base).href;
const r3OcrFiles=[
 ['tesseract.min.js','https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js'],
 ['worker.min.js','https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/worker.min.js'],
 ...['tesseract-core','tesseract-core-simd','tesseract-core-lstm','tesseract-core-simd-lstm'].flatMap(n=>[['core/'+n+'.wasm.js','https://cdn.jsdelivr.net/npm/tesseract.js-core@5.1.1/'+n+'.wasm.js'],['core/'+n+'.wasm','https://cdn.jsdelivr.net/npm/tesseract.js-core@5.1.1/'+n+'.wasm']]),
 ['eng.traineddata.gz','https://cdn.jsdelivr.net/npm/@tesseract.js-data/eng/4.0.0_best_int/eng.traineddata.gz']
];
let r3OcrInstalled=false,r3InstallBusy=false,r3ServerSpeech=null,r3SpeechAudio=null,r3SpeechURL=null,r3SpeechSerial=0;
async function r3OcrStatus(){if(!/^https?:$/.test(location.protocol)||!('caches'in window))return false;try{const config=await caches.open(r3ConfigCache),ptr=await config.match(r3Pointer);if(ptr){const p=await ptr.json();if(!p.cacheName?.startsWith('wordquest-r3-ocr-')||p.files?.length!==r3OcrFiles.length)return false;const c=await caches.open(p.cacheName);for(const [f]of r3OcrFiles)if(!await c.match(new URL('vendor/tesseract/'+f,r3Base)))return false;return !!navigator.serviceWorker?.controller;}
 const meta=await fetch(new URL('vendor/tesseract/manifest.json',r3Base),{cache:'no-store'});if(!meta.ok)return false;const m=await meta.json();if(m.version!=='5.1.1'||!r3OcrFiles.every(([f])=>m.files?.some(x=>x.path===f&&/^[a-f0-9]{64}$/.test(x.sha256))))return false;for(const[f]of r3OcrFiles){const r=await fetch(new URL('vendor/tesseract/'+f,r3Base),{method:'HEAD',cache:'no-store'});if(!r.ok)return false;}return true;
 }catch(_){return false;}}
async function r3PrepareOffline(){r3Parent();if(r3InstallBusy)throw Error('離線資料正在準備');if(!window.isSecureContext||!navigator.serviceWorker||!window.caches||!/^https?:$/.test(location.protocol))throw Error('請用 HTTPS 或本機啟動器開啟，直接雙擊HTML不能安裝離線快取');if(!confirm('下載OCR程式及英文模型到這個瀏覽器，可能使用數十至過百MB儲存空間。圖片不會傳到CDN。這不是已完成OCR準確度驗收。'))return;r3InstallBusy=true;const owner=accountId(),stage='wordquest-r3-ocr-'+encodeURIComponent(r3Base.pathname)+'-'+Date.now();let committed=false;
 try{await navigator.serviceWorker.register(new URL('sw.js',r3Base),{scope:r3Base.pathname});await Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>setTimeout(()=>reject(Error('離線服務未能啟動')),20000))]);const c=await caches.open(stage),files=[];let size=0;
 for(const [path,url] of r3OcrFiles){if(owner!==accountId()||!v23ParentAllowed())throw Error('帳戶或家長授權已改變，安裝已取消');r3Status('準備OCR資料 '+(files.length+1)+'／'+r3OcrFiles.length);const r=await fetch(url,{credentials:'omit',signal:AbortSignal.timeout(90000)});if(!r.ok||r.type==='opaque')throw Error('下載失敗：'+path);const buf=await r.arrayBuffer();size+=buf.byteLength;if(!buf.byteLength||buf.byteLength>80000000||size>220000000)throw Error('OCR檔案大小不合理');if(path.endsWith('.wasm')&&new DataView(buf).getUint32(0)!==0x0061736d)throw Error('不是有效WASM檔案：'+path);if(path.endsWith('.gz')&&(new Uint8Array(buf)[0]!==31||new Uint8Array(buf)[1]!==139))throw Error('不是有效英文模型壓縮檔');const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',buf))].map(x=>x.toString(16).padStart(2,'0')).join('');files.push({path,source:url,bytes:buf.byteLength,sha256:digest});await c.put(new URL('vendor/tesseract/'+path,r3Base),new Response(buf,{headers:{'Content-Type':path.endsWith('.wasm')?'application/wasm':path.endsWith('.js')?'text/javascript':'application/gzip'}}));}
 const config=await caches.open(r3ConfigCache);await config.put(r3Pointer,new Response(JSON.stringify({cacheName:stage,files,version:'5.1.1',installedAt:new Date().toISOString()}),{headers:{'Content-Type':'application/json'}}));committed=true;r3OcrInstalled=await r3OcrStatus();r3Status('所有OCR資源已下載及逐檔校驗。請先匯出學習備份，重新開啟本頁後，再斷網辨識一張真實印刷課文驗收。');
 }catch(e){if(!committed)await caches.delete(stage);throw e;}finally{r3InstallBusy=false;}}
window.WQR3OCR=Object.freeze({status:r3OcrStatus,files:r3OcrFiles.map(([path,source])=>({path,source})),async options(){r3OcrInstalled=await r3OcrStatus();return r3OcrInstalled?{workerPath:new URL('vendor/tesseract/worker.min.js',r3Base).href,corePath:new URL('vendor/tesseract/core/',r3Base).href,langPath:new URL('vendor/tesseract/',r3Base).href,workerBlobURL:false}:{};}});
const r3OldLoader=loadTesseract;loadTesseract=async function(){if(window.Tesseract)return;if(await r3OcrStatus()){if(tesseractPromise)return tesseractPromise;tesseractPromise=new Promise((resolve,reject)=>{const s=document.createElement('script'),timer=setTimeout(()=>{s.remove();tesseractPromise=null;reject(Error('本機OCR載入逾時'));},25000);s.src=new URL('vendor/tesseract/tesseract.min.js',r3Base);s.onload=()=>{clearTimeout(timer);resolve();};s.onerror=()=>{clearTimeout(timer);tesseractPromise=null;reject(Error('本機OCR未齊，請重新準備離線資料'));};document.head.append(s);});return tesseractPromise;}return r3OldLoader();};
function r3CancelSpeech(){r3SpeechSerial++;r3ServerSpeech?.abort();r3ServerSpeech=null;if(r3SpeechAudio){r3SpeechAudio.pause();r3SpeechAudio.src='';r3SpeechAudio=null;}if(r3SpeechURL){URL.revokeObjectURL(r3SpeechURL);r3SpeechURL=null;}}
window.WQR3Speech=Object.freeze({cancel:r3CancelSpeech,async speak(text,lang='yue-HK',slow=false){const settings=WQR3.voice();if(settings.mode!=='server')return false;if(!settings.consent)throw Error('未同意把題目文字傳到語音服務');if(!/^https?:$/.test(location.protocol))throw Error('固定聲線需要使用本機語音啟動器或HTTPS網站');if(typeof text!=='string'||!text.trim()||text.length>1200)throw Error('讀題文字長度不合適');r3CancelSpeech();const serial=r3SpeechSerial,controller=new AbortController();r3ServerSpeech=controller;const timer=setTimeout(()=>controller.abort(),20000);try{const voice=lang==='en-GB'?'en-GB-SoniaNeural':lang==='zh-CN'?'zh-CN-XiaoxiaoNeural':settings.voice;const response=await fetch(settings.endpoint||'/api/speech',{method:'POST',headers:{'Content-Type':'application/json','X-WordQuest-Speech':'1'},body:JSON.stringify({text,lang,voice,slow}),credentials:'same-origin',signal:controller.signal});if(!response.ok)throw Error(response.status===503?'語音服務未設定金鑰。可在家長頁改回裝置聲線。':'語音服務失敗（'+response.status+'）');if(!response.headers.get('Content-Type')?.startsWith('audio/'))throw Error('語音服務未傳回音訊');const blob=await response.blob();if(blob.size>6000000||!blob.size)throw Error('語音回應大小不合理');if(serial!==r3SpeechSerial)return true;r3SpeechURL=URL.createObjectURL(blob);r3SpeechAudio=new Audio(r3SpeechURL);r3SpeechAudio.onended=r3CancelSpeech;r3SpeechAudio.onerror=r3CancelSpeech;await r3SpeechAudio.play();return true;}finally{clearTimeout(timer);}}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)r3CancelSpeech();});window.addEventListener('pagehide',r3CancelSpeech);
const r3OfflinePanel=r3Panel;r3Panel=function(){r3OfflinePanel();const body=document.querySelector('#r3-dialog .r3-body')||document.getElementById('r3-dialog');const box=document.createElement('section');box.innerHTML='<h2>離線照片辨識</h2><p>程式包未附完整OCR二進制資源。可在連線時下載到此瀏覽器，完成後由本機辨識印刷英文字；不支援手寫。</p><button class="btn secondary" id="r3-prepare-offline">準備離線OCR</button><button class="btn soft" id="r3-check-offline">檢查離線資源</button>';body.append(box);box.querySelector('#r3-prepare-offline').onclick=async()=>{try{await r3PrepareOffline();}catch(e){r3Status(e.message,true);}};box.querySelector('#r3-check-offline').onclick=async()=>r3Status(await r3OcrStatus()?'OCR資源齊備；仍須實際斷網辨識驗收。':'本機OCR資源未齊或離線服務尚未控制此頁。');};

// Existing English material preparation keeps its verified WAV pipeline and playback flags.
fetchNeural=async function(text,signal){const setting=WQR3.voice();if(!setting.consent)throw Error('請先在家庭頁同意使用語音服務；沒有傳送英文文字');const blob=await getLimited(setting.endpoint||'/api/speech',MAX_AUDIO,{method:'POST',headers:{'Content-Type':'application/json','X-WordQuest-Speech':'1'},credentials:'same-origin',body:JSON.stringify({text,lang:'en-GB',voice:'en-GB-SoniaNeural',slow:false}),signal});const decoded=await decodeClip(blob);return {kind:'audio',key:audioKey(text),text,blob:wavFromBuffer(decoded),duration:decoded.duration,locale:'en-GB',verified:true,source:'Microsoft Azure Speech · en-GB-SoniaNeural',credit:'網站管理員配置的 Microsoft Speech 服務',license:'服務輸出；請依服務條款使用',transform:'converted to 24 kHz mono PCM WAV'};};
