 let r3Migration=null;
 async function chooseMigration(){
  if(bridge.parentAllowed?.()===false)throw Error('請先完成家長驗證');
  const input=app.querySelector('#import-file');input.value='';input.onchange=async ev=>{try{const f=ev.target.files[0];if(!f)return;if(f.size>2500000)throw Error('數學備份超過2.5 MB');const raw=JSON.parse(await f.text()),p=root.WQFamilyCore.portableMath(raw,C,L);if(!root.crypto.subtle)throw Error('需要支援SHA-256的安全瀏覽器環境');const bytes=new TextEncoder().encode(JSON.stringify(p));const hash=[...new Uint8Array(await root.crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('');
   r3Migration={payload:p,hash,scope:store.scope};const box=document.createElement('section');box.id='r3-math-preview';box.className='card';box.innerHTML=`<h2>核對舊學員 → 目前孩子</h2><p>來源：${esc(p.profile.name)}，小${p.profile.grade}，${p.state.attempts.length}次作答。</p><p>目標：${esc(store.profile.name)}，小${store.profile.grade}，已有${store.state.attempts.length}次作答。</p><div class="note">保留現有英文錢包，不派發舊獎勵。已提交數學紀錄合併；相同紀錄去重。已完成的評分不重新計算，掌握度採最後更新的一份。同日數學時間取較大值，不將可能重疊的時段重複相加。未完成的舊課不搬移。</div><label><input id="r3-math-consent" type="checkbox">我確認來源紀錄屬於目前孩子</label>${btn('確認合併舊紀錄','confirm-migrate','primary')}`;
   app.querySelector('#r3-math-preview')?.remove();app.querySelector('.shell').prepend(box);box.scrollIntoView({block:'start'});
  }catch(e){fail(e);}};input.click();
 }
 function confirmMigration(){if(bridge.parentAllowed?.()===false)throw Error('請先完成家長驗證');if(!r3Migration||r3Migration.scope!==store.scope)throw Error('目標孩子已改變，請重新選擇備份');if(!app.querySelector('#r3-math-consent')?.checked)throw Error('請先核對舊學員與目前孩子並勾選確認');const r=store.migrate(r3Migration.payload,r3Migration.hash);r3Migration=null;view='parent';render();toast(`已合併 ${r.addedAttempts} 筆舊紀錄，合共 ${r.totalAttempts} 筆；沒有重複派金幣。`);}
 function makeMock(level){canStudy();if(![1,2,3,4].includes(level))throw Error('試卷層級無效');if(!store.state.settings.olympiad)throw Error('家長已關閉奧數');if(current()&&!current().completed&&!confirm('結束未完成的數學練習並開始模擬卷？已提交答案保留。'))return;
  const pool=L.data.skills.filter(s=>s.track==='olympiad'&&(s.level||1)===level);if(pool.length<5)throw Error('這個層級題庫未齊');save(n=>{const queues={4:[]};for(let i=0;i<10;i++)queues[4].push(ref(C.nextQuestion(n,L,pool[i%pool.length].id,Math.min(3,1+Math.floor(i/4)))));n.current={id:S.uid(),skill:null,track:'olympiad',mode:'diagnostic',game:null,stage:4,index:0,queues,example:null,startedAt:Date.now(),questionAt:Date.now(),activeMs:0,hint:0,feedback:null,results:[],replacements:[],completed:false,rewardDone:false,fast:0,draft:'',picked:'',reflection:null,r3MockLevel:level};});view='lesson';ui.toolOpen=false;render();toast('原創10題模擬卷；不是任何主辦機構的真題、評級或正式競賽成績。');
 }
