'use strict';const fs=require('fs'),path=require('path'),assert=require('assert').strict;
const R=path.resolve(__dirname,'..'),F=require('../r32_src/reliability_core.js'),A=require('../r32_src/afeng_rig.js'),{create,sandbox:B,ctx}=require('../arcade_tests/engine_harness.cjs');const out=[];
function test(name,fn){try{const detail=fn();out.push({name,status:'pass',detail:detail??null});}catch(e){out.push({name,status:'fail',error:e.stack});}}
const owner='family-a',main='wordquest-v10-data-'+owner,valid={owner,before:{[main]:'{"version":12}'},beforeMedia:[],at:Date.now(),label:'test'};
for(const suffix of ['', '-before-restore','-v24-protection'])test('Allow exact family main key '+suffix,()=>assert(F.allowedKey(main+suffix,owner,main)));
for(const k of ['wq-r3-family:family-a','wqm-state-v1:family-a:child','wqm-state-v1:family-a:child:before-restore','wordquest-v32-characters:normal:family-a:child','wordquest-v32-characters:sandbox:family-a:child'])test('Allow owned sidecar '+k,()=>assert(F.allowedKey(k,owner,main)));
for(const k of ['wordquest-v10-accounts',main+'-x','wq-r3-recovery:family-a','wqm-state-v1:family-ab:child','wqm-state-v1:family-b:child','wordquest-v32-characters:normal:family-b:child','arbitrary','__proto__','constructor','prototype'])test('Refuse unknown / foreign journal key '+k,()=>assert.throws(()=>F.validateKV({[k]:'test'},owner,main)));
test('Valid recovery journal accepted',()=>assert.equal(F.validateJournal(valid,owner,main),valid));
for(const [name,edit] of [['owner',x=>x.owner='family-b'],['missing main',x=>x.before={}],['non-string',x=>x.before[main]={}],['missing media',x=>delete x.beforeMedia],['duplicated media',x=>x.beforeMedia=[{owner,key:'a',kind:'note'},{owner,key:'a',kind:'note'}]],['foreign media',x=>x.beforeMedia=[{owner:'family-b',key:'a',kind:'note'}]],['invalid media type',x=>x.beforeMedia=[{owner,key:'a',kind:'script'}]],['invalid date',x=>x.at=NaN],['too many keys',x=>{for(let i=0;i<1001;i++)x.before['wqm-state-v1:family-a:'+i]='{}';}]])test('Reject malformed journal: '+name,()=>{const x=structuredClone(valid);edit(x);assert.throws(()=>F.validateJournal(x,owner,main));});
for(const n of [0,1,139999999,140000000])test('Export size allowed '+n,()=>assert(F.canExport(n)));
for(const n of [-1,1.1,140000001,Infinity,NaN,'123'])test('Export size rejected '+n,()=>assert(!F.canExport(n)));
for(const action of A.states){test('Articulated '+action+' deterministic and finite',()=>{const p=A.pose(action,2.7,-1,false);assert.deepEqual(p,A.pose(action,2.7,-1,false));assert(!JSON.stringify(p).includes('null'));assert.equal(p.face,-1);A.draw(ctx,30,50,.6,p);});test('Articulated '+action+' supports reduced motion',()=>{const p=A.pose(action,1,1,true);assert(p.bob===(action==='land'?3:0));assert(p.tail===0);});}
test('Running animates leg and arm joints independently',()=>{const p=A.pose('run',.1),q=A.pose('run',.3);assert.notEqual(p.legs[0].hip,q.legs[0].hip);assert.notEqual(p.arms[0].shoulder,q.arms[0].shoulder);assert.notEqual(p.legs[0].hip,p.arms[0].shoulder);});
test('Unknown art action safely falls back',()=>assert.equal(A.pose('invalid',NaN,0).action,'idle'));
test('Eight distinct silhouette/state structures',()=>assert.equal(new Set(A.states.map(x=>JSON.stringify(A.pose(x,.3)))).size,8));
test('Facing is retained when horizontal speed returns to zero',()=>{const g={p:{x:0,vx:-100,vy:0},grounded:true,health:3,t:1};A.observe(g,.01);g.p.vx=0;A.observe(g,.01);assert.equal(A.describe(g).face,-1);});
test('Quick reversal faces requested direction during braking and retains it on release',()=>{const g={p:{x:0,vx:100,vy:0},keys:new Set(['left']),grounded:true,health:3,t:1};A.observe(g,.01);assert.equal(A.describe(g).face,-1);g.keys.clear();A.observe(g,.01);assert.equal(A.describe(g).face,-1);});
test('Landing state lasts briefly then returns to idle',()=>{const g={p:{x:0,vx:0,vy:100},grounded:false,health:3,t:1};A.observe(g,.01);g.grounded=true;g.p.vy=0;A.observe(g,.01);assert.equal(A.describe(g).action,'land');A.observe(g,.2);assert.equal(A.describe(g).action,'idle');});
test('Invulnerability does not repeatedly trigger hurt animation',()=>{const g={p:{x:0,vx:0,vy:0},grounded:true,health:3,t:1};A.observe(g,.01);g.health=2;g.inv=2;A.observe(g,.01);assert.equal(A.describe(g).action,'hit');A.observe(g,.3);assert.equal(A.describe(g).action,'idle');});
test('Completed cloud-island state selects victory',()=>{const g=create('cloud-island');g.done=true;g.won=true;assert.equal(B.WQAFeng.describe(g).action,'victory');});
test('Cloud draw leaves serialized physics state byte-identical',()=>{const g=create('cloud-island');g.key('right',true);for(let i=0;i<75;i++)g.tick(1/60);const before=JSON.stringify(B.WQArcadeSnapshot28.capture(g));for(let i=0;i<40;i++)g.draw();assert.equal(JSON.stringify(B.WQArcadeSnapshot28.capture(g)),before);});
test('Observation does not add fields to game save object',()=>{const g=create('cloud-island'),keys=Object.keys(g);B.WQAFeng.observe(g,.1);assert.deepEqual(Object.keys(g),keys);});
fs.writeFileSync(path.join(R,'r32_evidence/new_core_results.json'),JSON.stringify(out,null,2));console.log('new core',out.length,'pass',out.filter(x=>x.status==='pass').length);for(const e of out.filter(x=>x.status==='fail'))console.log(e.name,e.error);process.exitCode=out.some(x=>x.status==='fail')?1:0;
