"""Original focused exercises mapped to all 79 existing EDB2017 unit IDs.
This is baseline coverage, NOT a claim that every official learning outcome is complete.
No real student data is generated. Source answers use rational expressions, independent QA separately.
"""
from pathlib import Path
import json,copy
R=Path(__file__).resolve().parents[1]
base=json.loads((R/'originals/WordQuest_Program_and_Data_20260929/02_Maths_0.1.2/source/curriculum.json').read_text())
new={'skills':[],'templates':[],'cards':[],'coverage':[]}
I=lambda a,b:{'int':[a,b]}
P=lambda xs:{'pick':xs}
E=lambda s:{'expr':s}
D=lambda s,n=1:{'decimal':{'expr':s,'places':n}}
L=lambda key,vals:{'lookup':{'from':key,'values':vals}}
un={u['id']:u for u in base['units']}

def add(unit,name,en,kind,params,zh,eng,answer,concept,explain,tool='numberline',visual='',typ='number',constraints=None,labels=None,level=None,strategy=None,extra=None):
    sid=unit+'.R3' if unit in un else unit
    grade=un[unit]['grade'] if unit in un else min(6,level+1)
    strand=un[unit]['strand'] if unit in un else 'O'
    sk={'id':sid,'unit':unit if unit in un else 'OLY-R3','track':'normal' if unit in un else 'olympiad','strand':strand,'grade':grade,'name_zh':name,'name_en':en,'tool':tool,'prerequisites':[], 'official_focus':unit if unit in un else None,'source_page':None,'status':'baseline-preview','coverage':'原創基礎選段；不是本官方單元的全部學習重點。','strategy':strategy,'level':level or 1,'lesson':{'scene':name+'：先觀察資料或圖像，再決定方法。','concept':concept,'explore':'在教具改變一項數量，觀察其他量如何改變。回到題目，圈出已知和未知。','remedy':concept+' 先用較小數字試一次，再回到原題。','alternative':explain,'reflection':'答案的單位和大小是否合理？可以用相反運算、圖像或逐項列出驗證嗎？','minutes':8 if grade<3 else 10},'r3_review':'not yet independently teacher reviewed'}
    new['skills'].append(sk)
    for diff in (1,2,3):
        ps=copy.deepcopy(params(diff) if callable(params) else params)
        t={'id':sid+'-T'+str(diff),'skill':sid,'difficulty':diff,'type':typ,'params':ps,'constraints':constraints or [],'stem_zh':zh,'stem_en':eng,'speech_yue':zh.replace('多少','幾多').replace('共有','總共有').replace('應該','應該'), 'answer':{'expr':answer},'distractors':[],'hints':[concept,'先寫下題目給出的數量，單位要一致。',explain,'最後按同一方法計算，並檢查有沒有漏掉任何一項。'],'explanation':explain+' 答案是 {r3Answer}。','visual':'r3:'+visual if visual else '', 'verification':{'kind':kind},'difficulty_note':{'basis':'按數字範圍／運算步驟設計，尚未用學生數據校準','level':diff}}
        # Store explicit result only for explanation, not the independent answer checker.
        ps['r3Answer']=E(answer)
        if labels:
            t['choiceLabels']=labels;t['choiceCount']=len(labels);t['type']='choice';ps['r3AnswerLabel']=L('idx',[labels[str(v)]['zh'] for v in [x for x in ps['ans']['lookup']['values']]]) if 'ans' in ps and 'lookup' in ps['ans'] else P([''])
            t['explanation']=explain
        if extra:t.update(extra)
        if kind in ['decimalParts','fractionDecimal','percentToDecimal']:t['answer']['formats']=['decimal','integer']
        if kind=='mixedFraction':t['answer']['formats']=['fraction']
        new['templates'].append(t)
    if unit in un:new['coverage'].append({'unit':unit,'added_skill':sid,'topic':name,'scope':sk['coverage']})

# Number topics: each exercise uses a concrete independent mathematical operation.
add('1N1','倒數與相鄰的數','Count backwards','prev',lambda d:{'a':I(3,6*d)},'由 {a} 倒數一個數，是多少？','Count back one from {a}. What number comes next?','a-1','倒數一個就是少一個，在數線向左走一格。','由 {a} 向左走一格，即 {a} − 1。')
add('1N2','把剩下的數找出來','Find what remains','subtract',lambda d:{'b':I(1,3*d),'c':I(1,3*d),'a':E('b+c')},'有 {a} 粒珠，拿走 {b} 粒，還有多少粒？','There are {a} beads. Remove {b}. How many remain?','a-b','減法把一部分拿走。原有數量減去拿走的數量，就是餘下的。','{a} − {b}，也可用 {b} 加上答案檢查是否得到 {a}。',tool='tenframe')
add('1N3','幾個十與幾個一','Tens and ones','place',lambda d:{'a':I(1,3*d),'b':I(0,9)},'{a} 個十和 {b} 個一合起來是多少？','What number has {a} tens and {b} ones?','a*10+b','每十個一換成一個十。數位決定數字的值。','{a} 個十是 {a} × 10，再加 {b} 個一。',tool='place')
add('1N4','兩位數加法','Add within 100','add',lambda d:{'a':I(10,10+8*d),'b':I(1,9*d)},'{a} + {b} = ？','Calculate {a} + {b}.','a+b','個位對個位，十位對十位；十個一可換成一個十。','把 {b} 分拆，先把 {a} 湊整十，再加餘下部分。',tool='blocks')
add('2N1','百、十、一的數值','Hundreds, tens and ones','hundreds',lambda d:{'a':I(1,3*d),'b':I(0,9),'c':I(0,9)},'{a} 個百、{b} 個十和 {c} 個一是多少？','Write the number with {a} hundreds, {b} tens and {c} ones.','a*100+b*10+c','每一位的值是左邊相鄰數位的十分之一。','計算 {a} × 100 + {b} × 10 + {c}。',tool='place')
add('2N2','三位數減法','Subtract three-digit numbers','subtract',lambda d:{'b':I(100,130*d),'c':I(10,120*d),'a':E('b+c')},'{a} − {b} = ？','Calculate {a} − {b}.','a-b','減法可用加法驗算。需要退位時，拆開一個十或一個百，總值不變。','從 {a} 拿走 {b}；用答案加 {b} 檢查。',tool='blocks')
add('2N3','相同數量的多組','Equal groups','multiply',lambda d:{'a':I(2,3*d),'b':I(2,3*d)},'每盒有 {a} 粒珠，{b} 盒共有多少粒？','Each box holds {a} beads. How many beads are in {b} boxes?','a*b','相同數量相加，可用乘法表示。','把 {a} 加 {b} 次，即 {a} × {b}。',tool='array')
add('2N4','四位數的組成','Compose four-digit numbers','thousands',lambda d:{'a':I(1,3*d),'b':I(0,9),'c':I(0,9),'e':I(0,9)},'{a} 個千、{b} 個百、{c} 個十和 {e} 個一是多少？','Write the number with {a} thousands, {b} hundreds, {c} tens and {e} ones.','a*1000+b*100+c*10+e','沒有某一數位時用0佔位，不可把其他數字左移。','千、百、十、一分別乘1000、100、10、1後相加。',tool='place')
add('2N5','四位數減法驗算','Check four-digit subtraction','subtract',lambda d:{'b':I(1000,1100*d),'c':I(100,900*d),'a':E('b+c')},'{a} − {b} = ？','Calculate {a} − {b}.','a-b','數位對齊後逐位減。需要退位時改寫數的分拆，但總值不變。','算好後把差加 {b}；結果應是 {a}。',tool='place')
add('2N6','平均分配與每份','Share equally','division',lambda d:{'b':I(2,3*d),'c':I(2,3*d),'a':E('b*c')},'{a} 件物件平均分給 {b} 人，每人有多少件？','Share {a} objects equally among {b} people. How many does each person get?','a/b','除法找每份有多少。每人一樣多，分完後沒有剩餘。','找一個數乘 {b} 得 {a}。',tool='array')
add('3N1','五位數中的萬與千','Ten-thousands and thousands','tenThousands',lambda d:{'a':I(1,3*d),'b':I(0,9),'c':I(0,99)},'{a} 個萬、{b} 個千和 {c} 個一是多少？','Write the number with {a} ten-thousands, {b} thousands and {c} ones.','a*10000+b*1000+c','各數位沒有數量時仍需要0佔位。','先組成 {a} × 10000 + {b} × 1000，再加 {c}。',tool='place')
add('3N2','整數乘一位數','Multiply by one digit','multiply',lambda d:{'a':I(12,35*d),'b':I(2,3*d)},'{a} × {b} = ？','Calculate {a} × {b}.','a*b','把被乘數按數位分拆，每部分乘同一個數，再相加。','可先算整十的部分，再算個位部分，最後相加。',tool='array')
add('3N3','有餘數的平均分','Divide with a remainder','remainder',lambda d:{'b':I(3,3*d),'c':I(2,20*d),'r':I(0,2),'a':E('b*c+r')},'{a} ÷ {b} 的商和餘數是多少？','Find the quotient and remainder of {a} ÷ {b}.','c','先分出完整的一份，剩下的數一定小於除數。','驗算：除數 × 商 + 餘數 = 被除數。',tool='array',typ='remainder',extra={'answer':{'expr':'c','remainder':'r'}})
add('3N4','先乘後加','Order of operations','mixed',lambda d:{'a':I(2,3*d),'b':I(2,3*d),'c':I(1,10*d)},'{c} + {a} × {b} = ？','Calculate {c} + {a} × {b}.','c+a*b','沒有括號時，先乘除，後加減。','先算 {a} × {b}，再加 {c}。',tool='array')
add('3N5','同分母分數相加','Add like fractions','sameFraction',lambda d:{'b':P([5,7,9,11]),'a':I(1,2),'c':I(1,2)},'{a}/{b} + {c}/{b} = ？','Calculate {a}/{b} + {c}/{b}.','(a+c)/b','每份一樣大，合併所選的份數，分母不變。','把 {a} 份和 {c} 份合在一起，每份仍是 1/{b}。',tool='fraction',typ='fraction')
add('4N1','兩位數相乘','Multiply two two-digit numbers','multiply',lambda d:{'a':I(11,20*d),'b':I(11,15*d)},'{a} × {b} = ？','Calculate {a} × {b}.','a*b','利用分配性質，把一個乘數拆成十位和個位。','先算 {a} 乘 {b} 的十位值，再加 {a} 乘其個位。',tool='array')
add('4N2','除以兩位數','Divide by two digits','division',lambda d:{'b':I(11,15*d),'c':I(2,6*d),'a':E('b*c')},'{a} ÷ {b} = ？','Calculate {a} ÷ {b}.','a/b','用倍數估計商，再用乘法檢查是否正好分完。','列出 {b}、2 × {b}、3 × {b}，直到找到 {a}。',tool='numberline')
add('4N3','找指定的倍數','Find a multiple','multiple',lambda d:{'a':I(2,4*d),'b':I(2,5*d)},'{a} 的第 {b} 個正倍數是多少？','What is the {b}-th positive multiple of {a}?','a*b','正倍數是原數乘1、2、3等正整數所得的數。','第 {b} 個正倍數就是 {a} × {b}。')
add('4N4','共同響起的時間','Least common multiples','lcmConsecutive',lambda d:{'k':I(1,3*d),'x':I(2,3+d),'a':E('k*x'),'b':E('k*(x+1)')},'甲鐘每 {a} 分鐘響，乙鐘每 {b} 分鐘響。現在同時響，最少再過多少分鐘同時響？','Bell A rings every {a} minutes and bell B every {b} minutes. They ring together now. How many minutes until they next ring together?','k*x*(x+1)','分別列出兩數的正倍數，最小的共同數就是最小公倍數。','逐列 {a} 和 {b} 的倍數，找第一個共同時間。',tool='table')
add('4N5','括號先算','Calculate inside brackets first','brackets',lambda d:{'a':I(12,30*d),'b':I(2,9),'c':I(2,7)},'({a} + {b}) × {c} = ？','Calculate ({a} + {b}) × {c}.','(a+b)*c','括號表示先把裏面的數量合成一組。','先把 {a} 加 {b}，再把整組乘 {c}。',tool='array')
add('4N6','帶分數轉假分數','Convert mixed numbers','mixedFraction',lambda d:{'a':I(1,3*d),'b':P([3,5,7,9]),'c':I(1,2)},'把帶分數 {a} 又 {c}/{b} 寫成假分數。','Write {a} and {c}/{b} as an improper fraction.','a+c/b','每個整數有分母所表示的份數，再加零散的份數。','分子是 {a} × {b} + {c}，分母仍是 {b}。',tool='fraction',typ='fraction')
add('4N7','十分位與百分位','Tenths and hundredths','decimalParts',lambda d:{'a':I(1,3*d),'b':I(0,9)},'{a} 個十分之一和 {b} 個百分之一，合起來是多少？請用小數。','Write {a} tenths plus {b} hundredths as a decimal.','a/10+b/100','一個十分之一等於十個百分之一；小數點後第一位是十分位。','把 {a} 個十分之一改寫成 {a} × 10 個百分之一，再加 {b} 個。',tool='fraction')
add('4N8','小數加法對齊','Align decimal places','decimalAdd',lambda d:{'ia':I(11,30*d),'ib':I(1,30*d),'a':D('ia/10'),'b':D('ib/10')},'{a} + {b} = ？','Calculate {a} + {b}.','a+b','小數點對齊，十分位對十分位，個位對個位。','也可把兩數都改成十分之一的個數，相加後換回。',tool='place')
add('5N1','四捨五入至千位','Round to the nearest thousand','roundThousand',lambda d:{'a':I(1000,200000*d),'r':E('floor((a+500)/1000)*1000')},'把 {a} 四捨五入至千位。','Round {a} to the nearest thousand.','r','看百位：0至4捨去，5至9令千位進一；更小的數位改為0。','先找前後兩個整千數，再判斷哪個較近。',tool='place')
add('5N2','異分母分數相加','Add unlike fractions','unlikeAdd',lambda d:{'a':I(1,2),'b':P([3,4,5]),'c':I(1,2),'e':P([6,8,10])},'{a}/{b} + {c}/{e} = ？','Calculate {a}/{b} + {c}/{e}.','a/b+c/e','先通分，使每一份同樣大，才可以相加。','可先用 {b} × {e} 作共同分母，兩個分子也要乘相應倍數。',tool='fraction',typ='fraction')
add('5N3','分數乘法','Multiply fractions','fractionMultiply',lambda d:{'a':I(1,d+1),'b':P([5,7,9]),'c':I(1,d+1),'e':P([5,7,9])},'{a}/{b} × {c}/{e} = ？','Calculate {a}/{b} × {c}/{e}.','a*c/(b*e)','一部分的另一部分可用乘法表示；分子相乘、分母相乘。','先算 {a} × {c} 及 {b} × {e}，需要時約分。',tool='fraction',typ='fraction')
add('5N4','小數乘整數','Multiply a decimal','decimalMultiply',lambda d:{'ia':I(11,30*d),'a':D('ia/10'),'b':I(2,3*d)},'{a} × {b} = ？','Calculate {a} × {b}.','a*b','先按整數乘法計，再按每份的單位換回十分之一。','{a} 是 {ia} 個十分之一。{ia} 乘 {b} 後再除以10。',tool='array')
add('5N5','分數除法','Divide fractions','fractionDivide',lambda d:{'a':I(1,d+1),'b':P([5,7,9]),'c':I(1,d+1),'e':P([5,7,9])},'{a}/{b} ÷ {c}/{e} = ？','Calculate {a}/{b} ÷ {c}/{e}.','a*e/(b*c)','除以一個非零分數，等於乘它的倒數。','保留第一個分數，乘 {e}/{c}；分子分母同乘後約分。',tool='fraction',typ='fraction')
add('6N1','小數除法','Divide decimal numbers','decimalDivide',lambda d:{'ib':I(2,3*d),'q':I(2,4*d),'b':D('ib/10'),'a':D('ib*q/10')},'{a} ÷ {b} = ？','Calculate {a} ÷ {b}.','a/b','被除數與除數同乘10，商不變；把除數化成整數。','兩數同乘10後做整數除法，再乘回除數驗算。',tool='place')
add('6N2','分數化小數','Fractions as decimals','fractionDecimal',lambda d:{'a':I(1,3*d),'b':P([10,20,25])},'把 {a}/{b} 化成小數。','Write {a}/{b} as a decimal.','a/b','分數表示分子除以分母，也可擴成分母100的分數。','把分母化成100時，分子也乘相同倍數。',tool='fraction')
add('6N3','百分數的意義','Read percentages','percentToDecimal',lambda d:{'a':I(1,30*d)},'{a}% 化成小數是多少？','Write {a}% as a decimal.','a/100','百分數表示每100份中有多少份；100%等於整個。','把 {a} 除以100，不是除以10。',tool='fraction')
add('6N4','折扣後的價錢','Calculate a discounted price','discount',lambda d:{'a':I(2,10*d),'price':E('a*10'),'p':P([10,20,25,30,50])},'原價 {price} 元，減價 {p}%，售價多少元？','An item costs {price} dollars before a {p}% discount. What is the sale price in dollars?','price*(100-p)/100','減價百分率不是售價百分率；售價是原價的100%減去減幅。','先算減去多少元，然後由 {price} 元扣除。',tool='money')
# Measurement. Low-primary examples intentionally avoid decimal unit conversions.
add('1M1','用同樣大小的單位量度','Measure with equal units','lengthUnits',lambda d:{'a':I(2,3*d),'b':I(1,d)},'短帶長 {a} 個積木單位，長帶比它長 {b} 個同樣單位。長帶多長？','A short ribbon is {a} equal blocks long. Another ribbon is {b} blocks longer. How many blocks long is it?','a+b','單位要同樣長，首尾相接，不留空隙、不重疊。','在 {a} 個相同單位後面，再接 {b} 個。',tool='ruler',visual='length')
add('1M2','數一數硬幣總值','Count coin values','coinSum',lambda d:{'a':I(1,3),'b':I(1,d)},'{a} 個1元硬幣和 {b} 個2元硬幣，共多少元？','What is the total value of {a} one-dollar coins and {b} two-dollar coins?','a+2*b','硬幣的枚數不等於總值；先按面值分組。','1元共 {a} 元，2元共 2 × {b} 元，再相加。',tool='money')
add('1M3','由尺的刻度讀長度','Read a ruler in centimetres','rulerLength',lambda d:{'start':I(0,d),'len':I(2,4*d),'end':E('start+len')},'紙條在尺上由 {start} 厘米至 {end} 厘米，長多少厘米？','A strip extends from {start} cm to {end} cm on a ruler. How long is it?','end-start','長度是終點與起點相差多少，不能只看終點數字。','由 {start} 數至 {end}，或用終點減起點。',tool='ruler',visual='ruler')
add('1M4','鐘面上的整點','Read whole hours','clockHour',lambda d:{'hour':I(1,4*d),'minute':P([0])},'鐘面的分針指向12。現在是幾點？只填小時。','The minute hand points to 12. What hour does the clock show?','hour','長針是分針，短針是時針。整點時分針指向12。','看短針指向哪個數字。',tool='clock',visual='clock')
add('2M1','米與厘米化聚','Convert metres to centimetres','metresCm',lambda d:{'a':I(1,3*d),'b':I(1,30*d)},'{a} 米 {b} 厘米等於多少厘米？','How many centimetres are in {a} metres and {b} centimetres?','a*100+b','1米等於100厘米，把單位統一後再加。','{a} 米先乘100，再加 {b} 厘米。',tool='ruler')
add('2M2','鐘面的分鐘','Read minutes on a clock','clockMinute',lambda d:{'hour':I(1,12),'idx':I(0,11),'minute':E('idx*5')},'鐘面顯示 {hour} 點多少分？只填分鐘。','The clock shows hour {hour}. How many minutes past the hour is it?','minute','分針每走一個大格是5分鐘，走一圈是60分鐘。','由12開始，以5、10、15順數至分針指向的刻度。',tool='clock',visual='clock')
add('2M3','付錢後找贖','Find change','change',lambda d:{'paid':P([20,50,100]),'cost':I(1,10*d)},'付款 {paid} 元，貨品售 {cost} 元，應找回多少元？','You pay {paid} dollars for an item costing {cost} dollars. How much change should you receive?','paid-cost','找贖等於付款減貨價，付款不能少於貨價。','用 {paid} 減 {cost}；貨價加找贖應等於付款。',tool='money',constraints=['paid>cost'])
add('3M1','厘米和毫米','Convert centimetres and millimetres','cmMm',lambda d:{'a':I(1,6*d),'b':I(1,9)},'{a} 厘米 {b} 毫米是多少毫米？','How many millimetres are in {a} centimetres and {b} millimetres?','a*10+b','1厘米有10毫米；先把厘米換成毫米。','{a} × 10 + {b}。',tool='ruler')
add('3M2','時間間隔','Elapsed time','elapsed',lambda d:{'start':I(1,15*d),'duration':I(2,4*d),'end':E('start+duration')},'同一小時內，活動由第 {start} 分鐘至第 {end} 分鐘，經過多少分鐘？','Within the same hour, an activity starts at minute {start} and ends at minute {end}. How many minutes pass?','end-start','經過時間由開始到結束計算；起點不是第一個已過的分鐘。','終點 {end} 減起點 {start}。',tool='clock',constraints=['end<60'])
add('3M3','升與毫升','Convert litres and millilitres','litresMl',lambda d:{'a':I(1,3*d),'b':I(10,250*d)},'{a} 升 {b} 毫升，共多少毫升？','How many millilitres are in {a} litres and {b} millilitres?','a*1000+b','1升等於1000毫升；容量單位統一後才相加。','{a} 升是 {a} × 1000 毫升，再加 {b}。',tool='ruler')
add('3M4','下午時間與24小時制','Use the 24-hour clock','hour24',lambda d:{'a':I(1,3*d)},'下午 {a} 時，用24小時報時制是幾時？','Write {a} p.m. using the 24-hour clock. Enter the hour only.','a+12','下午1至11時加12；中午12時仍是12，午夜是0時。','本題下午 {a} 時，計算 {a} + 12。',tool='clock')
add('3M5','公斤與克','Convert kilograms and grams','kgG',lambda d:{'a':I(1,3*d),'b':I(20,250*d)},'{a} 公斤 {b} 克，共多少克？','How many grams are in {a} kilograms and {b} grams?','a*1000+b','1公斤等於1000克，不能把公斤直接與克相加。','把 {a} 公斤換成克，再加 {b} 克。',tool='ruler')
add('4M1','長方形周界','Rectangle perimeter','perimeter',lambda d:{'a':I(3,6*d),'b':I(2,4*d)},'長方形長 {a} 厘米，闊 {b} 厘米。周界多少厘米？','A rectangle is {a} cm long and {b} cm wide. Find its perimeter in cm.','2*(a+b)','周界是沿外邊走一圈的長度，四條邊都要計算。','兩條長和兩條闊：2 × ({a} + {b})。',tool='ruler',visual='rectangle')
add('4M2','方格與面積','Area of a rectangle','areaRectangle',lambda d:{'a':I(3,5*d),'b':I(2,3*d)},'長方形長 {a} 厘米，闊 {b} 厘米。面積多少平方厘米？','A rectangle is {a} cm long and {b} cm wide. Find its area in square cm.','a*b','面積是能鋪滿圖形的單位正方形數，不是外邊的長度。','每行 {a} 格，共 {b} 行，所以 {a} × {b}。',tool='array',visual='rectangle')
add('5M1','三角形面積','Area of a triangle','areaTriangle',lambda d:{'a':I(2,5*d),'b':I(2,4*d),'base':E('2*a'),'height':E('b')},'三角形底 {base} 厘米，對應高 {height} 厘米。面積多少平方厘米？','A triangle has base {base} cm and perpendicular height {height} cm. Find its area in square cm.','base*height/2','兩個全等三角形可拼成一個同底同高的平行四邊形。','底 × 對應高 ÷ 2；高必須垂直於這條底。',tool='array',visual='triangle')
add('5M2','長方體體積','Volume of a cuboid','volume',lambda d:{'a':I(2,3*d),'b':I(2,2+d),'c':I(1,2+d)},'長方體長 {a} 厘米、闊 {b} 厘米、高 {c} 厘米。體積多少立方厘米？','A cuboid measures {a} cm by {b} cm by {c} cm. Find its volume in cubic cm.','a*b*c','先數一層有多少粒單位立方體，再乘層數。','每層 {a} × {b}，共 {c} 層。',tool='solid',visual='solid')
add('6M1','平角與相鄰角','Angles on a straight line','straightAngle',lambda d:{'k':I(2,4*d),'angle':E('k*10')},'一直線上的兩個相鄰角，其中一角是 {angle}°，另一角多少度？','Two adjacent angles form a straight line. One is {angle} degrees. Find the other.','180-angle','平角是180°；兩個相鄰角合起來剛好是平角。','180° 減去已知的 {angle}°。',tool='angle',visual='angle')
add('6M2','立方厘米與毫升','Volume and capacity','cm3Ml',lambda d:{'a':I(2,4*d),'b':I(2,5),'c':I(2,4)},'長方體容器內長 {a} 厘米、內闊 {b} 厘米、內高 {c} 厘米。注滿共多少毫升？','A container has internal dimensions {a} cm by {b} cm by {c} cm. How many millilitres does it hold when full?','a*b*c','1立方厘米等於1毫升。用容器的內部尺寸計容量。','先算內部體積 {a} × {b} × {c}，再換成毫升。',tool='solid',visual='solid')
add('6M3','圓周與直徑','Circumference','circumference',lambda d:{'a':I(2,5*d)},'圓的直徑是 {a} 厘米。取 π = 3.14，圓周多少厘米？','A circle has diameter {a} cm. Use pi = 3.14 to find the circumference in cm.','314*a/100','圓周等於π乘直徑。半徑要先乘2才是直徑。','本題已給直徑，直接用 3.14 × {a}。',tool='ruler',visual='circleDiameter')
add('6M4','路程、時間與速率','Speed, distance and time','speed',lambda d:{'speed':I(10,30*d),'time':I(2,5),'distance':E('speed*time')},'用 {time} 小時行了 {distance} 公里，平均速率是多少公里／小時？','A journey covers {distance} km in {time} hours. Find the average speed in km/h.','distance/time','速率表示每一單位時間所走的路程。','路程 {distance} ÷ 時間 {time}。',tool='numberline')
add('6M5','圓的面積','Area of a circle','circleArea',lambda d:{'a':I(2,3*d)},'圓的半徑是 {a} 厘米。取 π = 3.14，面積多少平方厘米？','A circle has radius {a} cm. Use pi = 3.14 to find its area in square cm.','314*a*a/100','圓面積等於π乘半徑再乘半徑，不能用直徑代替半徑。','3.14 × {a} × {a}。',tool='array',visual='circleRadius')
# Conceptual geometry / statistics: numeric codes are hidden behind bilingual labels.
def concept(unit,name,en,kind,rows,labels,zh,eng,explain,tool='ruler',visual='shape'):
    # All rows present in every tier; rotation or evidence detail varies, not arbitrary answer-code arithmetic.
    def params(d):return {'idx':I(0,len(rows)-1),'shape':L('idx',[r[0] for r in rows]),'detail':L('idx',[{'zh':r[1],'en':r[2]} for r in rows]),'ans':L('idx',[r[3] for r in rows]),'rotation':P([0,15*d,30*d])}
    lab={str(i+1):{'zh':a,'en':b} for i,(a,b) in enumerate(labels)}
    add(unit,name,en,kind,params,zh,eng,'ans',explain,explain,tool=tool,visual=visual,typ='choice',labels=lab)
concept('1S1','辨認立體外形','Recognise solid shapes','solidClass', [('cube','六個平面都是正方形','All six flat faces are squares',1),('sphere','沒有平面，像球','No flat faces; shaped like a ball',2),('cylinder','兩個圓形平面，旁邊是曲面','Two flat circular faces and a curved surface',3),('cone','一個圓形平面，上方尖頂','One flat circular face and a pointed top',4)], [('方塊形','Cube'),('球形','Sphere'),('圓柱形','Cylinder'),('圓錐形','Cone')], '物件的特徵：{detail}。它是哪種外形？','An object has these features: {detail}. What shape is it?','觀察平面、曲面及整體外形，不用物件用途猜答案。',tool='solid',visual='solidType')
concept('1S2','按邊數認圖形','Classify flat shapes','polygonClass', [('triangle','3條直邊','3 straight sides',1),('square','4條直邊','4 straight sides',2),('pentagon','5條直邊','5 straight sides',3),('hexagon','6條直邊','6 straight sides',4)], [('三角形','Triangle'),('四邊形','Quadrilateral'),('五邊形','Pentagon'),('六邊形','Hexagon')], '一個封閉圖形有 {detail}，是甚麼圖形？','A closed shape has {detail}. What is it?','圖形可按直邊數分類；轉動或改變大小不會改變邊數。')
concept('1S3','看清左右前後','Relative positions','positionClass', [('left','小球在方盒左邊','The ball is to the left of the box',1),('right','小球在方盒右邊','The ball is to the right of the box',2),('above','小球在方盒上方','The ball is above the box',3),('below','小球在方盒下方','The ball is below the box',4)], [('左邊','Left'),('右邊','Right'),('上方','Above'),('下方','Below')], '以看圖者方向判斷，小球在方盒哪個位置？','From the viewer\'s position, where is the ball relative to the box?','先確定以看圖者的方向作參考，再說出兩件物件的相對位置。',visual='position')
concept('2S1','立體的平面形狀','Faces of solids','solidFace', [('cube','正方體的每一個面','Each face of a cube',1),('cylinder','圓柱的上下兩個平面','The two flat ends of a cylinder',2),('triangularPrism','三角柱兩個全等的底面','The two congruent bases of a triangular prism',3),('cuboid','長、闊、高各不相同的長方體的每一個面','Each face of a cuboid whose length, width and height are all different',4)], [('正方形','Square'),('圓形','Circle'),('三角形','Triangle'),('長方形','Rectangle')], '{detail}是甚麼形狀？','What shape is {detail}?','只計平面的形狀；曲面不叫圓形面。',tool='solid',visual='solidType')
concept('2S2','分辨銳角、直角和鈍角','Classify angles','angleClass', [('acute','比直角小','Smaller than a right angle',1),('rightangle','與直角一樣大','Equal to a right angle',2),('obtuse','比直角大，但未到平角','Larger than a right angle but smaller than a straight angle',3),('acute2','兩邊張開得比直角窄','A narrower opening than a right angle',1)], [('銳角','Acute angle'),('直角','Right angle'),('鈍角','Obtuse angle')], '圖中的角{detail}，屬於哪一種角？','The angle is {detail}. What type is it?','角的大小由兩邊張開程度決定，與邊畫得長或短無關。',tool='angle',visual='angleClass')
concept('2S3','東南西北的相反方向','Opposite compass directions','oppositeDirection', [('north','北','north',1),('south','南','south',2),('east','東','east',3),('west','西','west',4)], [('南','South'),('北','North'),('西','West'),('東','East')], '面向{detail}，轉身180°後面向哪一方？','You face {detail}. After a half turn, which direction do you face?','北與南相反，東與西相反。圖的上方標北時，右方是東。',visual='compass')
concept('2S4','正方形和長方形','Squares and rectangles','rectangleClass', [('square','四個角都是直角，四條邊相等','Four right angles and four equal sides',1),('rectangle','四個角都是直角，但鄰邊不相等','Four right angles and unequal adjacent sides',2),('square','每邊3厘米，四個角都是直角','Each side is 3 cm and all angles are right angles',1),('rectangle','長5厘米、闊2厘米，四個角都是直角','Length 5 cm, width 2 cm, all angles are right angles',2)], [('正方形','Square'),('長方形（非正方形）','Rectangle, not square')], '選最具體的名稱：{detail}。','Choose the most specific name: {detail}.','正方形的四條邊相等；正方形也屬於長方形，本題選較具體的名稱。')
concept('3S1','平行與四邊形','Parallel sides in quadrilaterals','parallelClass', [('parallelogram','兩組對邊分別平行，沒有直角','Two pairs of parallel opposite sides and no right angles',1),('trapezium','只有一組對邊平行','Exactly one pair of parallel opposite sides',2),('square','四個直角，四邊相等','Four right angles and four equal sides',3),('rectangle','四個直角，鄰邊不相等','Four right angles and unequal adjacent sides',4)], [('平行四邊形（非長方形）','Parallelogram, not rectangle'),('梯形','Trapezium'),('正方形','Square'),('長方形（非正方形）','Rectangle, not square')], '選最具體的名稱：{detail}。','Choose the most specific name: {detail}.','平行線延長後不相交；分類時須同時查看角和邊。',visual='shape')
concept('3S2','依邊長分類三角形','Classify triangles by sides','triangleClass', [('equilateral','三條邊都相等','All three sides are equal',1),('isosceles','只有兩條邊相等','Exactly two sides are equal',2),('scalene','三條邊都不相等','All three sides have different lengths',3),('equilateral','三條邊都是4厘米','All sides are 4 cm',1)], [('等邊三角形','Equilateral triangle'),('等腰三角形（非等邊）','Isosceles, not equilateral'),('不等邊三角形','Scalene triangle')], '選最具體的名稱：{detail}。','Choose the most specific name: {detail}.','先比較三條邊，不要只看三角形朝向；等邊三角形也是等腰三角形。',visual='shape')
concept('4S1','菱形與四邊形關係','Rhombuses and quadrilaterals','rhombusClass', [('rhombus','四邊相等，沒有直角','Four equal sides and no right angles',1),('square','四邊相等，四個直角','Four equal sides and four right angles',2),('rectangle','四個直角，只有對邊相等','Four right angles; only opposite sides are equal',3),('trapezium','只有一組對邊平行','Exactly one pair of parallel opposite sides',4)], [('菱形（非正方形）','Rhombus, not square'),('正方形','Square'),('長方形（非正方形）','Rectangle, not square'),('梯形','Trapezium')], '選最具體的名稱：{detail}。','Choose the most specific name: {detail}.','正方形同時是菱形、長方形及平行四邊形；本題按全部特徵選最具體名稱。')
add('4S2','把長方形分割','Split and recombine shapes','splitRectangle',lambda d:{'a':I(2,3*d),'b':I(2,3*d),'c':I(2,3*d)},'長方形闊 {b} 厘米，長分成 {a} 厘米和 {c} 厘米兩段。總面積多少平方厘米？','A rectangle has width {b} cm. Its length is split into {a} cm and {c} cm. What is the total area in square cm?','(a+c)*b','分割後沒有重疊或空隙，總面積等於各部分面積相加。','先算 {a} × {b}，再算 {c} × {b}，最後相加。',tool='array',visual='splitRectangle')
concept('4S3','八個方向','Eight compass directions','eightDirections', [('ne','北和東之間','between north and east',1),('se','南和東之間','between south and east',2),('sw','南和西之間','between south and west',3),('nw','北和西之間','between north and west',4)], [('東北','Northeast'),('東南','Southeast'),('西南','Southwest'),('西北','Northwest')], '位於{detail}的方向叫甚麼？','What direction lies {detail}?','先找四個正方向，再找相鄰兩個正方向之間的方向。',visual='compass')
add('5S1','半徑與直徑','Radius and diameter','diameter',lambda d:{'a':I(2,4*d)},'圓的半徑是 {a} 厘米，直徑是多少厘米？','A circle has radius {a} cm. What is its diameter in cm?','2*a','直徑通過圓心，等於兩條半徑。','半徑 {a} × 2。',tool='ruler',visual='circleRadius')
add('5S2','數稜與頂點','Edges of prisms','prismEdges',lambda d:{'n':I(3,3+d)},'一個底面為 {n} 邊形的直柱體，有多少條稜？','A right prism has {n}-sided polygonal bases. How many edges does it have?','3*n','上下底各有一圈稜，另有連接兩底的側稜；不能只數看得見的。','上底 {n} 條、下底 {n} 條、側邊 {n} 條，共3 × {n}。',tool='solid')
concept('6S1','對稱軸','Lines of symmetry','symmetry', [('square','正方形','a square',1),('rectangle','長闊不相等的長方形','a non-square rectangle',2),('equilateral','等邊三角形','an equilateral triangle',3),('isosceles','非等邊的等腰三角形','an isosceles triangle that is not equilateral',4)], [('4條','4'),('2條','2'),('3條','3'),('1條','1')], '{detail}有多少條對稱軸？','How many lines of symmetry does {detail} have?','沿對稱軸對摺，兩邊完全重合；不是所有對角線都是對稱軸。',visual='shape')
# Data handling: explicit scales, counts and graphical evidence.
add('2D1','象形圖的每個圖案','Read pictograms','pictogram',lambda d:{'a':I(2,3*d),'scale':P([1])},'圖中每個圓點代表 {scale} 人，甲組共有多少人？','Each dot represents {scale} person. How many people are in group A?','a*scale','先讀圖例，再數圖案，不能把圖案大小當人數。','數一數甲組的圖案，每個代表 {scale} 人。',tool='chart',visual='pictogram')
add('3D1','棒形圖相差多少','Compare bars','barDifference',lambda d:{'b':I(1,5*d),'delta':I(1,3*d),'a':E('b+delta'),'scale':P([1])},'棒形圖中，甲組比乙組多多少人？','In the bar chart, how many more people are in group A than in group B?','a-b','先按縱軸刻度讀兩組的值，再相減。','甲組 {a} 減乙組 {b}。',tool='chart',visual='bars')
add('4D1','棒形圖的刻度','Read scaled bars','scaledBars',lambda d:{'k':I(2,5*d),'scale':P([2,5,10]),'a':E('k*scale'),'b':E('(k-1)*scale')},'每一大格代表 {scale} 本書。甲組有多少本書？','Each major interval represents {scale} books. How many books are in group A?','a','先看每格的數值，再看棒頂位置；棒高的格數不是數量本身。','甲組高 {k} 大格，每格 {scale}，所以相乘。',tool='chart',visual='bars')
add('5D1','複合棒形圖','Read grouped bars','groupBars',lambda d:{'a':I(5,15*d),'b':I(5,15*d),'c':I(5,15*d),'e':I(5,15*d)},'圖中第一天借出圖書總數是多少本？','How many books were borrowed in total on day 1 in the grouped bar chart?','a+b','每組有不同類別的棒，先讀圖例並選對日期。','第一天中文 {a} 本和英文 {b} 本相加；不要加第二天的棒。',tool='chart',visual='groupBars')
add('6D1','平均數不是最大值','Calculate a mean','mean',lambda d:{'a':I(2,12*d),'b':I(2,12*d),'c':I(2,12*d)},'三天借書數分別是 {a}、{b}、{c} 本，平均每天多少本？','The numbers of books borrowed on three days are {a}, {b} and {c}. Find the mean per day.','(a+b+c)/3','平均數等於總和除以項目數，可能不是任何一項原數據。','先加三天的數，再除以3。',tool='chart')
add('6D2','折線圖的變化','Read changes in line graphs','lineChange',lambda d:{'a':I(5,10*d),'rise':I(2,4*d),'b':E('a+rise'),'c':I(5,10*d)},'圖中由第一天到第二天，數量增加多少？','How much does the value increase from day 1 to day 2 in the line graph?','b-a','折線圖呈現先後次序及變化；增加量是終值減起值。','第二天 {b} 減第一天 {a}，不是把兩天相加。',tool='chart',visual='line')
add('6D3','圓形圖的百分比','Read a pie chart','pieAmount',lambda d:{'a':I(2,10*d),'total':E('a*20'),'p':P([10,20,25,40,50])},'圓形圖總共 {total} 人，甲組佔 {p}%。甲組多少人？','A pie chart represents {total} people. Group A is {p}%. How many people are in A?','total*p/100','圓形圖整個圓表示總數100%，不是每個扇形都一樣多人。','總人數 {total} × {p}/100。',tool='chart',visual='pie')
concept('6D4','圖表表達是否恰當','Spot misleading charts','chartMisuse', [('brokenAxis','由90開始的縱軸，把100與110的差異畫得特別大','A vertical axis starting at 90 exaggerates the difference between 100 and 110',1),('areaIcon','數量變成原來的2倍，圖案長和闊亦各變成原來的2倍','Both icon width and height are doubled when quantity only doubles',2),('missingUnit','縱軸只有數字，沒有說明是人數還是金額','The vertical axis has numbers but no unit or variable label',3),('fair','縱軸由0開始、刻度等距，並標明單位','A zero-based axis with equally spaced ticks and a clear unit',4)], [('截斷縱軸誇大差異','Truncated axis exaggerates differences'),('圖案面積誇大數量','Icon area exaggerates quantity'),('欠缺單位或變量','Missing unit or variable'),('上述表達合理','The described presentation is reasonable')], '選最直接的判斷：{detail}。','Choose the most direct assessment: {detail}.','檢查縱軸起點、刻度、圖例、單位及圖案面積；單憑畫面高低可能誤判。',tool='chart',visual='')
# Algebra, exact inverse operations.
add('5A1','把字母代入數值','Substitute into an expression','substitution',lambda d:{'a':I(2,5*d),'b':I(2,3*d),'c':I(1,5*d)},'當 x = {a}，{b}x + {c} 等於多少？','If x = {a}, find {b}x + {c}.','a*b+c','相鄰的數和字母表示相乘；把同一個字母用同一個數代入。','先算 {b} × {a}，再加 {c}。',tool='array')
add('5A2','一步方程','Solve one-step equations','oneEquation',lambda d:{'x':I(2,8*d),'a':I(2,6*d),'b':E('x+a')},'x + {a} = {b}，x 等於多少？','Solve x + {a} = {b}.','b-a','等式兩邊做相同運算，仍然相等。','兩邊同減 {a}，然後代回原式驗算。',tool='numberline')
add('6A1','兩步方程','Solve two-step equations','twoEquation',lambda d:{'x':I(2,6*d),'a':I(2,3*d),'b':I(1,10*d),'c':E('a*x+b')},'{a}x + {b} = {c}，x 等於多少？','Solve {a}x + {b} = {c}.','(c-b)/a','先消去加減部分，再消去乘除部分；每次兩邊做同一操作。','兩邊同減 {b}，再同除以 {a}。',tool='numberline')
# Three further olympiad levels, five distinct domains/strategies per level.
cards=[('inverse','倒推','從結果出發，用相反運算一步一步返回起點。','加3後乘2得到14：先14÷2，再減3。'),('parity','奇偶分析','留意奇數、偶數在加減或配對後的性質。','兩個奇數相加為偶數，可用小例子觀察。'),('assume','先作假設','先假設全部相同，再利用差額找出另一類的數量。','把全部車當成兩輪車，再按每輛多出的輪數調整。'),('pigeonhole','抽屜原理','把物件按類別分組，先考慮最分散的情況。','三種顏色，最壞先各拿一個，第4個必與某色相同。'),('systematic','有序計數','固定一部分，逐個改變另一部分，避免漏數和重複。','衣服每一件逐一配每一條褲，總數是兩數相乘。'),('invariant','找不變的量','步驟改變外觀時，找一直不變的量作檢查。','搬移物件不增加或減少時，總數不變。'),('pair','首尾配對','把兩端配成相同總和，減少重複加法。','1加10、2加9都等於11。')]
new['cards']=[{'id':k,'name':n,'description':d,'example':e} for k,n,d,e in cards]
for lev in [2,3,4]:
    common=lambda d,lev=lev: {'a':I(2,3*d+lev),'b':I(1,4*d+lev),'x':I(2,5*d+lev),'end':E('(x+a)*b')}
    add(f'O-R3-L{lev}-inverse','倒推：找原來的數',f'Work backwards level {lev}','inverse',common,'一個數先加 {a}，再乘 {b}，得 {end}。原數是多少？','A number is increased by {a}, then multiplied by {b}, giving {end}. What was the original number?','end/b-a','最後做乘法，倒推時先除；再把加法倒轉成減法。','先算 {end} ÷ {b}，再減 {a}。',level=lev,strategy='inverse')
    add(f'O-R3-L{lev}-count','有序計數：配搭',f'Systematic counting level {lev}','combinations',lambda d,lev=lev:{'a':I(2,d+lev),'b':I(2,d+lev),'c':I(1,lev-1)},'有 {a} 種上衣、{b} 種褲和 {c} 種帽。各選一款，共多少種配搭？','Choose one shirt, one pair of trousers and one hat from {a}, {b} and {c} choices respectively. How many outfits are possible?','a*b*c','先固定上衣，逐一配褲和帽，再換下一款上衣。','每種上衣有 {b} × {c} 種配搭，最後乘 {a}。',tool='table',level=lev,strategy='systematic')
    add(f'O-R3-L{lev}-geometry','方格中的長方形',f'Count rectangles level {lev}','gridRectangles',lambda d,lev=lev:{'a':I(1,min(5,d+lev-1)),'b':I(1,min(5,d+lev-1))},'圖中有 {a} 行、{b} 列單位方格，沿格線共可畫多少個長方形？包括正方形。','A grid has {a} rows and {b} columns of unit squares. How many rectangles can be drawn along grid lines, including squares?','a*(a+1)*b*(b+1)/4','一個長方形由兩條水平線和兩條垂直線確定；也可按長和闊逐類數。','水平線有 {a}+1 條，任選兩條；垂直線有 {b}+1 條，也任選兩條。',tool='array',visual='grid',level=lev,strategy='systematic')
    add(f'O-R3-L{lev}-logic','至少保證同色',f'Guarantee matching colours level {lev}','pigeonhole',lambda d,lev=lev:{'a':I(2,d+lev),'k':I(2,lev+1)},'袋中有 {a} 種顏色的球，每色數量充足。不看顏色拿球，最少拿多少個才能保證有 {k} 個同色？','A bag has {a} colours of balls, with plenty of each colour. How many draws without looking guarantee at least {k} balls of one colour?','a*(k-1)+1','考慮最不容易湊齊的情況：每種顏色先各拿少一個。','先算 {a} × ({k} − 1)，再多拿1個。',tool='tenframe',level=lev,strategy='pigeonhole')
    add(f'O-R3-L{lev}-applied','車輪問題：先假設',f'Assumption problems level {lev}','wheels',lambda d,lev=lev:{'cars':I(1,d+lev),'bikes':I(2,2*d+lev),'total':E('cars+bikes'),'wheels':E('cars*4+bikes*2')},'有兩輪單車和四輪車共 {total} 輛，共 {wheels} 個輪。四輪車有多少輛？','There are {total} vehicles: two-wheel bicycles and four-wheel cars. They have {wheels} wheels in total. How many cars are there?','(wheels-2*total)/2','先假設全部是兩輪車，每換一輛四輪車便多2個輪。','先用 {wheels} 減 2 × {total}，再除以2。',tool='table',level=lev,strategy='assume')
# Verify coverage and structural counts now; actual independent answers checked by a separate program.
assert len(new['coverage'])==79,(len(new['coverage']), sorted(set(un)-{x['unit'] for x in new['coverage']}))
assert len({s['id'] for s in new['skills']})==len(new['skills'])
new['revision']='R3-baseline-1';new['source']='EDB2017 pmc2017_tc.pdf, unit index; generated exercises are original, not official questions.'
(R/'r3_src/curriculum_extension.json').write_text(json.dumps(new,ensure_ascii=False,indent=2))
js='/* Original R3 baseline exercises. Not complete official-outcome or teacher certification. */\n(function(){const ext='+json.dumps(new,ensure_ascii=False,separators=(',',':'))+';const d=globalThis.WQMathData;d.skills.push(...ext.skills);d.templates.push(...ext.templates);d.cards.push(...ext.cards);for(const row of ext.coverage){const u=d.units.find(u=>u.id===row.unit);u.skills.push(row.added_skill);u.status="baseline-partial";}d.r3Coverage=ext.coverage;d.r3Revision=ext.revision;globalThis.WQR3Curriculum=ext;})();'
(R/'r3_src/curriculum_extension.js').write_text(js)
print('new',len(new['skills']),'skills',len(new['templates']),'templates; mapped units',len(new['coverage']))
