from pathlib import Path
import json,html,base64,hashlib,subprocess,platform,re,tempfile,shutil
R=Path(__file__).resolve().parents[1];E=R/'r32_evidence'
def e(s):return html.escape(str(s))
suites=[('街機引擎及存檔規則','arcade_core_results.json'),('家庭資料合約','family_contracts.json'),('新增日誌與動作規則','new_core_results.json'),('家庭備份還原DOM','family_browser.json'),('英數課堂及版面抽測','integration_results.json'),('五款街機瀏覽器回歸','arcade_browser_results.json'),('新增保護／裝置頁／動作頁','new_browser_results.json'),('阿峰實際遊戲操作','cloud_live.json'),('伺服器處理器合約','server_contracts.json'),('真正本機HTTP與檔案','server_native_http.json')]
flat=[];summ=[]
for name,file in suites:
 x=json.loads((E/file).read_text());rows=x if isinstance(x,list) else x.get('tests',x.get('rows'))
 n=0
 for i,r in enumerate(rows):
  p=(r.get('status','').lower()=='pass') if 'status' in r else r.get('pass') is True
  n+=p;flat.append({'suite':name,'number':i+1,'name':r.get('name',r.get('id','case')),'status':'pass' if p else 'fail','evidence':file,'detail':r.get('error',r.get('detail',''))})
 summ.append({'suite':name,'passed':n,'total':len(rows),'file':file})
assert all(x['passed']==x['total'] for x in summ),summ
# Syntax-check the shipped files, including the standalone preview's inline JS.
checks=[]
with tempfile.TemporaryDirectory(prefix='wqr32-syntax-') as tmp:
 for file in ['app/index.html','app/afeng-animation.html']:
  for i,m in enumerate(re.finditer(r'<script\b[^>]*>(.*?)</script>',(R/file).read_text(),re.S|re.I)):
   if not m[1].strip():continue
   t=Path(tmp)/f'{Path(file).stem}-{i}.js';t.write_text(m[1]);p=subprocess.run(['node','--check',str(t)],capture_output=True,text=True);checks.append({'file':file,'inline':i,'pass':p.returncode==0,'error':p.stderr[:1500]})
 for file in ['app/afeng-rig.js','app/device-check.js','app/sw.js','server/local_server.mjs']:
  p=subprocess.run(['node','--check',str(R/file)],capture_output=True,text=True);checks.append({'file':file,'pass':p.returncode==0,'error':p.stderr[:1500]})
assert all(x['pass'] for x in checks)
if not (E/'initial_syntax.json').exists():shutil.copy2(E/'syntax.json',E/'initial_syntax.json')
(E/'syntax.json').write_text(json.dumps(checks,indent=2))
result={'version':'R3.2.0','classification':'acceptance candidate; native browser persistence not certified','appSHA256':hashlib.sha256((R/'app/index.html').read_bytes()).hexdigest(),'suites':summ,'cases':len(flat),'passed':sum(x['passed'] for x in summ),'syntax':len(checks),'nativeBrowser':'BLOCKED_BY_ADMINISTRATOR; no native app-persistence passes','templateCoverage':'12/366 current templates re-rendered, selected evenly; existing complete six-step ordinary/Olympiad flows also executed; no new full independent answer audit','environment':{'python':platform.python_version(),'node':subprocess.check_output(['node','--version'],text=True).strip(),'browser':subprocess.check_output(['/usr/bin/chromium','--version'],text=True).strip(),'appUI':'Chromium actual DOM/canvas/input/download with explicit storage/WebLocks/WebCrypto and applicable family-media/journal I/O adapters','nativeDevicePage':'No adapters; verified correct BLOCKED/attestation controls, NOT successful native persistence','nativeHTTP':'15 real loopback HTTP tests, separate from browser'},'excluded':['historical R3/R3.1 test counts','incomplete first full-template run','initial development failures','package hash/file counts','native blocked steps']}
(E/'RELEASE_RESULTS.json').write_text(json.dumps(result,ensure_ascii=False,indent=2))
css='''*{box-sizing:border-box}.grid>*{min-width:0}body{overflow-wrap:anywhere;margin:0;background:#f5f2e8;color:#2d4336;font:17px/1.8 system-ui,"Microsoft JhengHei",sans-serif}main{max-width:1080px;margin:auto;padding:42px 24px 80px}h1{font-size:36px;line-height:1.3}h2{margin-top:38px;font-size:26px}h3{font-size:20px}.lead{font-size:21px;max-width:850px}.note{background:#f6e6bc;border-left:5px solid #9d7842;padding:20px;border-radius:0 14px 14px 0}.card{background:#fffdf7;padding:22px;border:1px solid #d7dfcd;border-radius:18px;margin:18px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.stats strong{font-size:34px;display:block}table{width:100%;border-collapse:collapse;font-size:15px}td,th{padding:12px 10px;text-align:left;vertical-align:top;border-bottom:1px solid #dce2d2}th{background:#e9efdf}.scroll{overflow:auto}img{display:block;width:100%;border-radius:16px;border:1px solid #d7dfcd}.mobile{max-width:320px;margin:auto}.small{font-size:14px;color:#65725d}summary{cursor:pointer;font-weight:700}input,select,button{font:inherit;padding:10px 13px;border:1px solid #9ead92;border-radius:10px;background:#fffdf7;color:inherit}a{color:#315f45}code{overflow-wrap:anywhere}pre{white-space:pre-wrap;word-break:break-word;font-size:13px}.controls{display:flex;gap:12px;flex-wrap:wrap}.footer{margin-top:38px;border-top:1px solid #d4dacb;padding-top:20px}@media(max-width:680px){main{padding:26px 17px 50px}.grid{grid-template-columns:1fr}h1{font-size:29px}.stats strong{font-size:26px}.card{padding:17px}.stats{gap:9px}.stats .card{padding:12px}}'''
def image(file):return 'data:image/png;base64,'+base64.b64encode((E/file).read_bytes()).decode()
tr=''.join(f'<tr><td>{e(x["suite"])}</td><td>{x["passed"]}／{x["total"]}</td><td><code>{e(x["file"])}</code></td></tr>' for x in summ)
body=f'''<!doctype html><html lang="zh-HK"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>WordQuest R3.2｜保存驗收及阿峰動作報告</title><style>{css}</style></head><body><main><p class="small">WORDQUEST R3.2.0 · ACCEPTANCE CANDIDATE</p><h1>先保護資料，<br>再讓阿峰真正動起來。</h1><p class="lead">在R3.1完整程式上增量修正家庭資料流程，加入原生裝置驗收頁，以及「雲島探險」的阿峰分肢動作。沒有把原生導覽封鎖說成測試通過。</p><div class="note"><strong>仍未完成：原生瀏覽器保存及重開驗收。</strong><br>兩次實際本機HTTP導覽均遭執行環境以 ERR_BLOCKED_BY_ADMINISTRATOR 阻擋。這個ZIP是可試用的驗收候選版，不是零漏洞或商用認證。</div><div class="stats"><div class="card"><strong>{len(flat)}</strong>本輪最終案例通過</div><div class="card"><strong>{len(checks)}</strong>JavaScript語法檢查</div><div class="card"><strong>8</strong>阿峰動作狀態</div></div>
<h2>已完成的五組修正</h2><div class="scroll"><table><tr><th>範圍</th><th>實際改動</th></tr><tr><td>一致家庭備份</td><td>匯出期間凍結操作與其他寫入；處理中的教材媒體先等待。最後再核對身份、授權、編輯權及資料快照，有變動就拒絕產生不一致檔案。</td></tr><tr><td>匯出大小</td><td>與原有匯入上限一致，限制140,000,000 UTF-8 bytes。邊界和拒絕路徑已測；未做140MB真機記憶體壓測，亦不是串流匯出。</td></tr><tr><td>中斷交易</td><td>復原日誌驗證目前家庭、允許的儲存位置、媒體歸屬及主資料格式；不讓損壞日誌回寫其他家庭或覆蓋有效主資料。失敗保留標記並停止其他寫入。</td></tr><tr><td>IndexedDB阻擋</td><td>被其他分頁佔用時提供失敗，不再無限等待；晚到的開啟結果會關閉額外連線。</td></tr><tr><td>裝置狀態</td><td>家長頁新增只讀裝置狀態和無姓名JSON；另有原生API、重載、雙分頁和人工重開驗收頁。專用記號與學員資料分開。</td></tr></table></div>
<h2>阿峰：不是整張海報平移</h2><p>手臂、前臂、腿部、頭部、耳朵及背包分開繪製，按實際時鐘、速度、落地、生命和完成狀態，切換待機、跑步、起跳、下落、落地緩衝、短衝、受碰撞及完成。暫停即停止；視覺資料不加入遊戲存檔，不改物理、碰撞或金幣。</p><p>實際鍵盤測試發現快速反向後，餘下慣性會讓角色轉回原方向。已改為優先跟隨操作意向、放手後保留朝向，並保留首次失敗記錄。<strong>這是新動作接入過程中發現的問題，不冒充原R3.1既有缺陷。</strong></p><div class="grid"><figure><img src="{image('afeng-lab-desktop.png')}" alt="實際動作檢視頁，獨立關節阿峰與原肖像並排"><figcaption class="small">實際Chromium檢視頁：可暫停、逐格、轉向及切換8個狀態。</figcaption></figure><figure class="mobile"><img src="{image('afeng-cloud-live-mobile.png')}" alt="320像素雲島探險實際遊戲中的阿峰"><figcaption class="small">實际320px遊戲畫面；不是Android/iPhone真機。</figcaption></figure></div><p class="note">目前阿峰是按原設定製作的<strong>簡化向量遊戲角色</strong>，不是海報原畫等級的高清逐格素材。其餘五位的完整跑跳／發球動作仍未全部製作。</p>
<h2>本輪最終重跑結果</h2><p>以下共{len(flat)}個測試案例，不是{len(flat)}個獨立功能；不與上一輪或初次中斷結果相加。全題庫沒有重新独立驗算：本輪只在366個模板中均勻抽12個重新作答，另測普通數學及奧數完整六階段流程。</p><div class="scroll"><table><tr><th>分組</th><th>通過／總數</th><th>原始證據檔案（r32_evidence）</th></tr>{tr}</table></div><p>「新增保護／裝置頁／動作頁」包括6項確認受限環境正確顯示未能執行、不允許錯誤重開認證的介面測試。這6項<strong>不是</strong>6個原生保存成功結果。Node迴路HTTP通過也不等於瀏覽器保存通過。</p>
<h2>執行環境與未完成驗收</h2><div class="scroll"><table><tr><th>項目</th><th>本次狀態</th></tr><tr><td>主程式畫面、點擊、鍵盤、下載、Canvas、部分WebAudio</td><td>真正Chromium執行；主程式storage／Web Locks／WebCrypto及相關家庭媒體／日誌I/O使用明示替身。</td></tr><tr><td>本機API驗收頁</td><td>沒有替身；本環境得到未能執行。已確認不會誤報成功。</td></tr><tr><td>原生應用關閉重開、真多分頁寫入、乾淨瀏覽器完整還原</td><td><strong>未能完成。</strong>原生runner在正常HTTP導覽即被政策阻擋，後續步驟未執行。</td></tr><tr><td>本機Node路由及實檔</td><td>15個真正HTTP迴路請求通過。既有37個處理器測試使用假上游聲音服務，沒有付費API請求。</td></tr><tr><td>Windows／Safari／iPhone／Android、真人聲音、真實教材OCR、教師／學生試用</td><td>未完成。螢幕尺寸模擬不是手機真機；自動作答不是學習成效研究。</td></tr></table></div><p class="small">Python {e(result['environment']['python'])} · Node {e(result['environment']['node'])} · {e(result['environment']['browser'])}</p>
<h2>開發過程保留的失敗與中斷</h2><p>初次動作核心測試對負零與正零使用過嚴的strictEqual，已修正測試判定及刪除重複檢查，不當作程式修正數。最初完整模板DOM重跑被工具時限中斷，只留下61筆已執行結果；之後以明示12模板抽測重跑75項，不把未跑的模板當通過。阿峰快速反向1項實測失敗已修正並重跑7項操作。原始檔案保存在initial_*，最終結果與首次記錄分開。</p>
<h2>自己的裝置如何驗收</h2><p>先在旧版匯出家庭完整備份。解壓後開START_HERE.html查看入口；Windows用START_WINDOWS.cmd開本機網址，保留命令視窗。家長頁 → 家庭備份 → 裝置與保存檢查 → 本機驗收頁。先建立記號，再驗證重載和第二分頁，完全關閉瀏覽器後回到同址核對；人工關閉確認與自動讀回證據會分開記錄。</p><p>不要公開自己的家庭備份。裝置頁只輸出技術狀態及專用測試記號；完整應用還原、舊學員搬移及自訂媒體仍需依套件內原生驗收表核對。</p>
<h2>逐項案例</h2><div class="controls"><input id="q" aria-label="搜尋案例" placeholder="搜尋案例名稱"><select id="suite" aria-label="選擇分組"><option value="">全部分組</option>{''.join('<option>'+e(s['suite'])+'</option>' for s in summ)}</select></div><p id="count"></p><div class="scroll"><table><thead><tr><th>分組</th><th>案例</th><th>結果</th></tr></thead><tbody id="cases"></tbody></table></div><div class="controls"><button id="prev">上一頁</button><button id="next">下一頁</button></div><div class="footer"><p>本次不改學員、題目、街機識別碼及金幣規則。原R3.1全部檔案保留在原位置或originals/R3_1。校驗碼只證明檔案完整，不是功能、安全或商用認證。</p><p class="small">實際測試均使用明示合成帳戶；没有存取你日常瀏覽器的學員紀錄。完整結果：r32_evidence/RELEASE_RESULTS.json；原生阻擋：native_acceptance.json、native-initial.json。</p></div></main><script>const rows={json.dumps(flat,ensure_ascii=False).replace('</','<\\/')};let page=0;const $=s=>document.querySelector(s);function show(){{let a=rows.filter(r=>(!$('#suite').value||r.suite===$('#suite').value)&&r.name.toLowerCase().includes($('#q').value.toLowerCase()));page=Math.max(0,Math.min(page,Math.max(0,Math.ceil(a.length/35)-1)));$('#cases').replaceChildren();a.slice(page*35,page*35+35).forEach(r=>{{let tr=document.createElement('tr');[r.suite,r.name,r.status==='pass'?'通過':'未通過'].forEach(v=>{{let td=document.createElement('td');td.textContent=v;tr.append(td)}});$('#cases').append(tr)}});$('#count').textContent=a.length+' 個案例 · 第 '+(page+1)+' 頁';$('#prev').disabled=page===0;$('#next').disabled=(page+1)*35>=a.length;}}$('#q').oninput=$('#suite').onchange=()=>{{page=0;show()}};$('#prev').onclick=()=>{{page--;show()}};$('#next').onclick=()=>{{page++;show()}};show();</script></body></html>'''
body=body.replace('實际','實際').replace('独立','獨立').replace('旧版','舊版').replace('没有','沒有')
(R/'docs/R3_2_驗收報告.html').write_text(body)
# Standalone copies may be made from docs/R3_2_驗收報告.html after this build.
print('Final total',len(flat),'syntax',len(checks),'report bytes',len(body.encode()))
