from pathlib import Path
import json,html,hashlib,re,subprocess
R=Path(__file__).resolve().parents[1];E=R/'r31_evidence';D=R/'docs'
suites=[('characters_core.json','角色分工、表情及輸入邊界'),('characters_browser.json','角色瀏覽器及備份流程'),('child_and_exam.json','孩子隔離及獨立作答介面'),('family_contracts.json','家庭資料驗證規則'),('family_browser.json','家庭備份、搬移及清除流程'),('integration_results.json','英文／數學整合回歸'),('arcade_core_results.json','街機引擎及局面相容'),('arcade_browser_results.json','街機實際操作及畫面')]
summary=[];allrows=[]
for name,title in suites:
 a=json.loads((E/name).read_text());a=a['tests'] if isinstance(a,dict) else a
 def ok(r):return r.get('pass') is True or r.get('status','').lower()=='pass'
 n=sum(ok(x) for x in a);summary.append({'file':name,'name':title,'total':len(a),'passed':n,'failed':len(a)-n})
 for i,r in enumerate(a):allrows.append({'suite':title,'id':r.get('id',name+':'+str(i+1)),'name':r.get('name',''),'pass':ok(r)})
assert all(x['failed']==0 for x in summary),summary
app=(R/'app/index.html').read_text();old=(R/'originals/R3/index.html').read_text();apphash=hashlib.sha256(app.encode()).hexdigest()
oldScripts=re.findall(r'<script\b[^>]*>(.*?)</script>',old,re.S|re.I);newScripts=re.findall(r'<script\b[^>]*>(.*?)</script>',app,re.S|re.I)
proof={'appSha256':apphash,'newScriptCount':len(newScripts),'unchangedMath':{},'unchangedArcade':{},'newSourcePNGs':[]}
for i,n in [(33,'math_data'),(34,'r3_curriculum_extension'),(35,'math_visuals'),(36,'math_core'),(37,'math_storage')]:proof['unchangedMath'][n]={'sha256':hashlib.sha256(oldScripts[i].encode()).hexdigest(),'exactSourcePresent':oldScripts[i] in newScripts}
for i in list(range(0,2))+list(range(12,24)):proof['unchangedArcade'][str(i)]={'sha256':hashlib.sha256(oldScripts[i].encode()).hexdigest(),'exactSourcePresent':oldScripts[i] in newScripts}
assets=json.loads((R/'app/assets/forest/manifest.json').read_text())
for c in assets['characters']:
 p=R/'app/assets/forest'/c['id']/'concept-original.png';h=hashlib.sha256(p.read_bytes()).hexdigest();assert h==c['original_sha256'];proof['newSourcePNGs'].append({'name':c['name'],'sha256':h,'size':p.stat().st_size})
assert all(v['exactSourcePresent'] for group in ['unchangedMath','unchangedArcade'] for v in proof[group].values())
syntax=[]
for i,s in enumerate(newScripts):
 p=E/'__syntax.js';p.write_text(s);q=subprocess.run(['node','--check',str(p)],capture_output=True,text=True);syntax.append({'id':'script:'+str(i),'pass':q.returncode==0,'error':q.stderr});assert not q.returncode,q.stderr
p.unlink()
q=subprocess.run(['node','--check',str(R/'app/sw.js')],capture_output=True,text=True);syntax.append({'id':'service-worker','pass':q.returncode==0,'error':q.stderr});assert not q.returncode
(E/'syntax.json').write_text(json.dumps(syntax,indent=2));(E/'source_preservation.json').write_text(json.dumps(proof,ensure_ascii=False,indent=2))
results={'version':'R3.1.0','appSha256':apphash,'suites':summary,'total':sum(x['total'] for x in summary),'passed':sum(x['passed'] for x in summary),'syntax':len(syntax),'observedScope':'real Chromium DOM; explicit native-I/O adapters; no human or physical-device validation'}
(E/'SUMMARY.json').write_text(json.dumps(results,ensure_ascii=False,indent=2))
(E/'all_cases.json').write_text(json.dumps(allrows,ensure_ascii=False,indent=2))
style='''*{box-sizing:border-box}body{margin:0;background:#f6f4eb;color:#253f34;font:17px/1.8 system-ui,"Microsoft JhengHei",sans-serif}main{max-width:1100px;margin:auto;padding:42px 24px 70px}h1{font-size:clamp(30px,5vw,46px);line-height:1.3;margin:12px 0 25px}h2{font-size:26px;margin:38px 0 16px}h3{margin:0 0 10px}.lead{font-size:20px;max-width:850px}.eyebrow{font-size:12px;letter-spacing:2px}.card{background:#fffdf6;border:1px solid #dedfcf;border-radius:20px;padding:25px;margin:20px 0}.note{background:#f7e9cc;border-left:4px solid #9d7237;padding:20px;border-radius:10px;margin:20px 0}.links{display:flex;gap:12px;flex-wrap:wrap}.button{display:inline-block;background:#2a5a45;color:white;border:0;border-radius:13px;padding:13px 22px;font:inherit;text-decoration:none;cursor:pointer}.secondary{background:#fffdf6;color:#2a5a45;border:1px solid #b9c9ad}a{color:#2a5a45}img{max-width:100%;height:auto;border-radius:15px}figure{margin:20px 0}figcaption,.small{font-size:13px;color:#5d6a57}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.cast{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:12px;margin:25px 0}.cast>div{text-align:center}.cast img{width:110px;height:130px;object-fit:contain}.cast strong{display:block;font-size:16px}.cast span{font-size:12px}.scroll{overflow-x:auto}table{border-collapse:collapse;width:100%;font-size:15px}td,th{padding:13px 12px;border-bottom:1px solid #dce1d4;text-align:left;vertical-align:top}th{background:#edf1e4}code{overflow-wrap:anywhere}pre{white-space:pre-wrap;font-size:13px;padding:15px;background:#edf1e4;border-radius:12px}input{font:inherit;padding:11px 14px;border-radius:10px;border:1px solid #acbba0;max-width:100%}.case{border-bottom:1px solid #dce1d4;padding:12px 0}.case small{display:block;color:#59674f}@media(max-width:640px){main{padding:25px 17px 45px}.grid{grid-template-columns:1fr}.cast{grid-template-columns:repeat(2,minmax(0,1fr))}.card{padding:18px}.button{width:100%;text-align:center}td,th{padding:10px 8px}h2{font-size:23px}}'''
def page(title,body):return '<!doctype html><html lang="zh-HK"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+html.escape(title)+'</title><style>'+style+'</style><main>'+body+'</main></html>'
roles=[('lie-lie','烈烈老師','解題老師','四則運算、應用題、學習步驟'),('you-you','柚柚老師','圖形老師','圖形、分數、量度與觀察'),('tang-li','糖栗老師','創意與教具老師','教具工房、動手探索'),('bo-bo','波波','數字小幫手','首頁任務、數感、基本加減'),('ci-ci','刺刺','步驟小幫手','提示、重試、休息及回饋'),('a-feng','阿峰','奧數同學','奧數、策略卡及街機準備')]
cast=lambda prefix: '<div class="cast">'+''.join(f'<div><img src="{prefix}app/assets/forest/{i}/front.webp" alt="{n}"><strong>{n}</strong><span>{job}</span></div>' for i,n,job,work in roles)+'</div>'
start='<div class="eyebrow">WORDQUEST R3.1 / FOREST ACADEMY</div><h1>六位新學伴，<br>一起回到真正的課堂。</h1><p class="lead">英文、普通數學、奧數與26款街機保留在同一個程式。本版把六位新角色的肖像、表情和分工接入原有學習流程。</p><div class="links"><a class="button" href="app/index.html">開啟完整程式</a><a class="button secondary" href="app/index.html#companions">直接查看六位角色</a></div>'+cast('')+'<div class="note"><strong>先備份，再升級。</strong>在舊版家長頁匯出「家庭完整備份」。更換檔案位置、網址、裝置或瀏覽器後，舊紀錄不一定自動出現；需要在新程式還原自己的備份。</div><div class="grid"><section class="card"><h2>按課堂自動安排</h2><p>波波帶你開始、老师講解、刺刺陪伴重試，阿峰一起挑戰奧數。也可固定一位學伴，或隱藏、精簡角色。</p></section><section class="card"><h2>保留原有學習規則</h2><p>角色不改答案、判分、提示或金幣。切換數學學伴只更新角色區，不重繪正在作答的題目。</p></section></div><div class="links"><a href="docs/R3_1_角色接入報告.html">本轮接入及測試報告</a><a href="docs/角色素材一覽_R3_1.html">原海報與表情素材</a><a href="README_R3_1.md">使用及資料說明</a></div><section class="card"><h2>這一版不代表甚麼？</h2><p>使用本次新繪的六張海報，不是取回V33或數學0.1.3的原件。未有獨立側面、背面或逐格跑跳動畫；街機玩家仍用R3原有的動作繪製。真機、原生關閉重開、多分頁及真人試用仍待驗收。</p><p class="small">一般開啟不需要Python。開發者重建與重跑測試才需要相應工具。舊R1、R2、R3報告及原始資料保留在包內，請以本輪報告判斷本版狀態。</p></section>'
start=start.replace('老师','老師').replace('本轮','本輪');(R/'START_HERE.html').write_text(page('WordQuest R3.1 · 開始使用',start))
table=''.join('<tr><td>'+x['name']+'</td><td>'+str(x['passed'])+' / '+str(x['total'])+'</td><td><a href="../r31_evidence/'+x['file']+'">逐項JSON</a></td></tr>' for x in summary)
report='<div class="eyebrow">WORDQUEST R3.1 / CHARACTER INTEGRATION</div><h1>角色不再只在海報裏。</h1><p class="lead">六個肖像、30個表情裁切，已接入英文與數學介面、教具及街機陪伴。六張原PNG完整保留；另有六個內嵌海報預覽，共42個程式圖像資源。</p><div class="links"><a class="button" href="../app/index.html">開啟完整程式</a><a class="button secondary" href="../app/index.html#companions">查看實際角色介紹</a></div>'+cast('../')+'<h2>分工與顯示</h2><div class="scroll"><table><tr><th>角色</th><th>主要分工</th></tr>'+''.join(f'<tr><td>{n}</td><td>{work}</td></tr>' for i,n,j,work in roles)+'</table></div><p>答錯或使用提示時由刺刺陪伴；進入教具探索由糖栗老師帶路。固定學伴只更換陪伴角色，不改題目回饋。高小及作答時自動精簡；模擬卷與獨立測試收起角色和設定入口。</p><h2>本輪實際畫面</h2><figure><img src="../r31_evidence/gallery_1280.png" alt="完整程式內六角色介紹與表情切換"><figcaption>實際Chromium畫面；不是獨立設計稿。</figcaption></figure><figure><img src="../r31_evidence/final_math_feedback.png" alt="數學作答後角色與表情回饋"><figcaption>原有題目、回饋與角色區共存；角色不另行判分。</figcaption></figure><h2>資料與操作</h2><p>角色設定沿用帳戶、孩子及正式／測試區的原有儲存位置。新增可選guide欄位，舊記錄未有此欄位時自動安排。家庭完整備份匯出、還原及孩子切換已加入驗證；原有題庫、判分核心及街機引擎的來源碼雜湊保持一致。</p><p>切換角色、隱藏或精簡只重繪學伴區，不重繪題目。實測保留未提交答案與焦點、不改數學状态或金幣；保存失敗時顯示只在本次有效，不冒充已保存。</p><h2>實際測試結果</h2><div class="scroll"><table><tr><th>範圍</th><th>通過／總數</th><th>證據</th></tr>'+table+f'<tr><th>合計</th><th>{results["passed"]} / {results["total"]}</th><td>不是相同數目的功能</td></tr></table></div><p>另有{len(syntax)}個JavaScript語法檢查通過（{len(newScripts)}段內嵌程式＋服務工作程序）。本輪沒有把原R3的3,660次獨立答案驗算當作重新執行；本次題目操作檢查屬於回歸驗證。檢查數目不代表品質分數、學習成效或零漏洞。</p><div class="note"><strong>驗收界線：</strong>實際Chromium點擊、鍵盤、選單和檔案下載有執行，但原生file導覽被環境以ERR_BLOCKED_BY_ADMINISTRATOR阻擋。測試使用明示儲存、跨分頁鎖、密碼運算及家庭媒體I/O替身；不代表原生重開保存、Safari、手機真機或Windows啟動器已通過。</div><h2>第一次嘗試與修正紀錄</h2><p>曾同時啟動三個Chromium檢查流程，遇到頁面崩潰，原因未證實；改為逐套執行後完成全套。另有兩項測試器問題：隱藏測試錯把不可見的快取圖片節點當成失敗；獨立作答測試的定位器同時找到兩個入口。分別改以實際可見性及指定第一個入口檢查。這些沒有冒充成原程式漏洞或刪去初次紀錄。</p><h2>仍需另外完成</h2><p>角色素材還欠獨立侧面、背面、逐格走跑跳／發球動作；小表情是約80像素寬的海報裁切，適合頭像，不是假裝成高清全身動畫。新六角色已接入街機大堂、規則及暫停陪伴，但未取代街機內的全部玩家動畫。完整官方課程、教師審核、真人語音和OCR模型等R3其餘範圍未在本輪擴充。</p><p>概念海報的字句和數學示意不作教材或標準答案。角色的姓名、工作及教學內容以程式文字、題庫及正式教具為準。</p><h2>重現及查閱</h2><p><a href="../r31_evidence/SUMMARY.json">本輪摘要</a> · <a href="../r31_evidence/source_preservation.json">核心與原圖校驗</a> · <a href="../r31_evidence/environment.json">環境及限制</a> · <a href="角色素材一覽_R3_1.html">全部素材</a> · <a href="../README_R3_1.md">使用與開發說明</a></p><pre>python tools/build_character_assets.py\npython tools/build_characters_r31.py\npython r31_tests/run_all.py\npython r31_tests/child_and_exam.py</pre><p class="small">本輪測試程式使用合成測試帳戶和作答資料；未接觸使用者瀏覽器的真實學員紀錄。應用程式SHA-256：<code>'+apphash+'</code></p>'
report=report.replace('状态','狀態').replace('侧面','側面');(D/'R3_1_角色接入報告.html').write_text(page('WordQuest R3.1 · 角色接入與驗證',report))
gallery='<div class="eyebrow">R3.1 / ASSET INVENTORY</div><h1>六位角色的原圖與表情</h1><p>所有原PNG完整保存。肖像使用橢圓取景，表情使用小尺寸原生裁切，不是新增角度或逐格動畫。</p><p><a href="../START_HERE.html">返回入口</a> · <a href="../app/assets/forest/manifest.json">裁切座標、尺寸及校驗碼</a></p>'
for c in assets['characters']:
 gallery+=f'<section class="card"><h2>{c["name"]}</h2><div class="links">'+''.join(f'<figure><img style="width:auto;max-width:90px;max-height:120px" src="../app/assets/forest/{c["id"]}/{pose}.webp" alt="{c["name"]} {pose}"><figcaption>{pose}</figcaption></figure>' for pose in ['front','face0','face1','face2','face3','face4'])+f'</div><details><summary>完整原PNG概念海報</summary><img loading="lazy" src="../app/assets/forest/{c["id"]}/concept-original.png" alt="{c["name"]}原概念海報"></details></section>'
(D/'角色素材一覽_R3_1.html').write_text(page('WordQuest R3.1 · 素材一覽',gallery))
print(json.dumps(results,ensure_ascii=False,indent=2))
