"""Build an evidence-backed HTML report; refuses to label failing suites as passed."""
from pathlib import Path
import json,hashlib,datetime,html,base64,collections
R=Path(__file__).resolve().parents[1];E=R/'r3_evidence';D=R/'docs'
suites=[('出題與獨立答案核對','independent_results.json','question-sample'),('家庭資料流程及故障注入','family_browser.json','browser-adapted'),('家庭資料驗證規則','family_contracts.json','pure-contracts'),('英文與數學整合回歸','integration_results.json','browser-adapted'),('新增教具、模擬卷及控制','new_features_browser.json','browser-adapted'),('課堂概念及另解題面','lesson_text_browser.json','seeded-browser-views'),('街機引擎及舊局面相容','arcade_core_results.json','engine'),('街機瀏覽器及音訊','arcade_browser_results.json','browser-adapted'),('可選服務請求處理器','server_contracts.json','handler-mocked-upstream')]
summary=[];allcases=[]
for label,file,scope in suites:
 raw=json.loads((E/file).read_text());rows=raw['tests'] if isinstance(raw,dict) else raw
 good=lambda x:x.get('pass') is True or str(x.get('status','')).lower()=='pass'
 passed=sum(good(x) for x in rows);assert passed==len(rows),(label,len(rows)-passed)
 summary.append({'label':label,'file':file,'scope':scope,'total':len(rows),'pass':passed,'fail':len(rows)-passed})
 for i,x in enumerate(rows):allcases.append({'group':label,'id':str(x.get('id') or f'{scope}-{i+1}'),'name':x.get('name') or '獨立驗算：'+str(x.get('kind','')),'status':'pass' if good(x) else 'fail'})
assert not json.loads((E/'generation_failures.json').read_text())
assert len(json.loads((E/'generated_cases.json').read_text()))==3660
h=hashlib.sha256((R/'app/index.html').read_bytes()).hexdigest();runs=json.loads((E/'delivery_runs.json').read_text());assert len(runs)==10 and all(x['app_sha256']==h and x['returncode']==0 for x in runs)
syntax=json.loads((E/'syntax.json').read_text());assert all(x['pass'] for x in syntax['tests']) and syntax['app_sha256']==h
coverage=json.loads((E/'curriculum_combined.json').read_text());preserve=json.loads((E/'R2_PRESERVATION.json').read_text());gaps=json.loads((D/'GAP_STATUS_R3.json').read_text())
now=datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=8))).isoformat(timespec='seconds')
result={'version':'R3.0.0','created_at_hk':now,'app_sha256':h,'question_sample_count':3660,'other_case_count':sum(s['total'] for s in summary[1:]),'suites':summary,'syntax_embedded':39,'syntax_worker_and_server':2,'native_browser_verified':False,'real_student_data_used':False,'live_ocr_verified':False,'live_paid_voice_verified':False,'original_r2_files_preserved':769,'limits':['Chromium page.set_content with explicit storage/WebLocks/crypto adapters','Family IDB media/journal I/O substituted; no native persistence/restart acceptance','Node HTTP request handler with fake upstream; no real speech audio','Localhost/file navigation blocked by environment policy','No original V33/Maths0.1.3/new-six-character raw files recovered','79 basic unit selections are not a complete official syllabus']}
(E/'DELIVERY_SUMMARY.json').write_text(json.dumps(result,ensure_ascii=False,indent=2));(E/'case_index.json').write_text(json.dumps(allcases,ensure_ascii=False,indent=2))
css=(E/'report_style.css').read_text();escape=lambda v:html.escape(str(v))
body=f'''<small>WORDQUEST · R3.0.0 · {escape(now)}</small><h1>先修正資料風險，<br>再擴充課堂及街機操作。</h1><p>本輪以英文V32＋數學0.1.2＋街機R2為基礎開發，原R2的769個檔案逐一保留。這不是原版V33或Maths0.1.3復原包。</p><div class="notice"><strong>這份報告不把「有入口」當成「課程全部完成」，也不把測試替身當成真機。</strong>本輪已完成下列修正與基礎擴充；完整官方課程、新版批准角色原圖、真正離線OCR／付費聲線及原生持久保存仍有未完成或未驗收部分。</div><div class="grid"><div class="card"><div class="stat">3,660</div><p>出題樣本，並用獨立Python運算核對答案；同一批樣本不重複計數。</p></div><div class="card"><div class="stat">{result['other_case_count']:,}</div><p>另外的規則、故障注入、引擎或瀏覽器案例全部通過。不等於相同數目的不同功能。</p></div></div>
<h2>一、R2五項優先問題</h2><div class="scroll"><table><thead><tr><th>原問題</th><th>本輪處理</th><th>驗證界線</th></tr></thead><tbody>
<tr><td>清除帳戶漏刪數學</td><td>目前家庭的數學主檔、還原副本、角色設定、跨科紀錄及自訂媒體一併清理，不碰其他家庭。</td><td>實際按鈕／資料流通過；持久儲存與IDB是明示替身。</td></tr>
<tr><td>沒有完整家庭備份</td><td>全部孩子、英文、普通數學、奧數、街機、設定、使用時間及媒體；校驗碼、還原預覽、明示確認、兩階段日誌與失敗恢復。</td><td>真實下載JSON及匯入操作；圖片測試為合成二進制夾具，不宣稱真實媒體解碼或原生斷電恢復。</td></tr>
<tr><td>舊數學身份不同不能搬入</td><td>由家長核對舊學員到目標孩子，合併歷史作答及進度，去重，不搬舊未完成課堂、不重派獎勵。</td><td>已知v1數學備份、重複搬入、去重及目標金幣流程通過。</td></tr>
<tr><td>答句提交後變空白</td><td>從已提交數值及單位還原完整答句，保留原判分。</td><td>原找贖題實際填答、提交及重繪檢查通過。</td></tr>
<tr><td>手機沒有慢移控制</td><td>星環巡航新增慢移鍵，按住生效，取消指標即解除；鍵盤Shift仍保留。</td><td>390px真實Chromium指標操作通過；不是觸屏手機真機驗收。</td></tr></tbody></table></div>
<h2>二、課程及操作增加到哪裡？</h2><div class="scroll"><table><thead><tr><th>項目</th><th>R2</th><th>R3</th><th>不能誤解成</th></tr></thead><tbody>
<tr><td>普通數學</td><td>23技能</td><td>102技能；小一至小六、五範疇、79單元均有原創基礎選段。</td><td>不是每個官方學習重點、先修流程和課時均已完成。</td></tr><tr><td>奧數</td><td>5啟蒙技能</td><td>4層×5技能條目、12策略卡、各層10題原創模擬卷。</td><td>不同層仍有同一方法的數值／步數變式；非完整競賽培訓或官方試卷。</td></tr><tr><td>題目模板</td><td>84</td><td>366（含原84）；另保留84個歷史模板供舊紀錄還原。</td><td>模板數不等於互不重複的教學概念，也不等於所有可能參數已窮舉。</td></tr><tr><td>教具</td><td>10入口</td><td>15入口；新增鐘面、量角器、立體單位積木、量度尺、統計圖。</td><td>自由教具不一定是當前題目本身；不適用的情況明示作探索用途。</td></tr><tr><td>跨科安排</td><td>資料分開</td><td>各科建議時間、全站上限、最近七天週報，合併入口、分開學科紀錄。</td><td>不補估舊版未记录的使用時間，不是伺服器同步家長控制。</td></tr><tr><td>街機</td><td>26款</td><td>仍26款；加入手機慢移與4款角色街機的獨立肢體動作。</td><td>不是多增加26款；不是已取回0.1.3六角色整套原圖及動畫。</td></tr></tbody></table></div>
<h2>三、本輪交付測試</h2><p>所有下列交付回歸測試讀取同一個R3主檔：<code>{h}</code>。沒有拿上次555項或之前1000項的結果充當本輪結果。</p><div class="scroll"><table><thead><tr><th>檢查組</th><th>通過／總數</th><th>原始結果檔案</th></tr></thead><tbody>'''
body+=''.join(f'<tr><td>{escape(s["label"])}</td><td>{s["pass"]:,}／{s["total"]:,}</td><td><code>r3_evidence/{escape(s["file"])}</code></td></tr>' for s in summary)
body+='''</tbody></table></div><p>另有39段內嵌JavaScript，以及Service Worker與Node伺服器2個檔案的語法檢查通過。語法、ZIP CRC及SHA256只證明相應語法或位元組完整性，不當作功能通過數。</p><div class="notice"><strong>執行環境：</strong>真實Chromium DOM點擊／鍵盤／下載／畫面及原生音訊介面；頁面透過page.set_content載入。localStorage、Web Locks、WebCrypto有明示替身，家庭備份的IDB媒體和日誌I/O亦有替身。localhost及file導覽被環境政策阻擋，沒有繞過。真正關閉再開、多分頁、Windows、Safari、手機仍未驗收。伺服器測試呼叫真實請求處理器及檔案系統，但語音上游和音訊為假資料，不是已成功合成真人聲線。</div><p>366個模板的題面逐一顯示、填答及判分；143項概念／另解頁檢查是有效課堂狀態的播種顯示，不是122課逐一從頭到尾真人上完。3,660個出題樣本以獨立Fraction／公式／枚舉核對，不僅用原判分器核對自己。</p>
<h2>四、實際畫面</h2><div class="grid">'''
for name,cap in [('family_panel.png','家長資料及跨科設定，合成測試帳戶。'),('money_sentence_fixed.png','已提交找贖題：答句仍保留實際答案。'),('new_solid_320.png','320px教具：5×5×5共125粒單位立方體，實際範圍鍵盤操作。'),('slow_key_mobile.png','星環巡航：390px慢移按鈕及遊戲操作畫面。')]:
 p=E/name
 if p.exists():body+='<figure><img loading="lazy" src="data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()+'" alt="'+escape(cap)+'"><figcaption>'+escape(cap)+'</figcaption></figure>'
body+='</div><h2>五、所有缺漏的處理狀態</h2><p>以下狀態優先於任何「完整版」檔名。完整版是來源、程式、素材與報告一起交付，不是所有產品藍圖均完成的承諾。</p>'
for code,label,status,desc in gaps:body+=f'<details><summary>{escape(code)} · {escape(label)} — {escape(status)}</summary><p>{escape(desc.replace("绘製","繪製"))}</p></details>'
body+='''<h2>六、逐項案例索引</h2><p>可按組別或名稱搜尋，每頁50項。完整數值、錯誤資料及重現方法在ZIP的r3_evidence與r3_tests。</p><p><input id="search" placeholder="搜尋編號、模板、功能" style="font:inherit;padding:11px;max-width:100%;width:360px"><select id="group" style="font:inherit;padding:11px;max-width:100%"><option value="">全部組別</option></select></p><p id="count"></p><div class="scroll"><table><thead><tr><th>組別</th><th>編號</th><th>案例</th><th>結果</th></tr></thead><tbody id="cases"></tbody></table></div><p><button id="prev" style="padding:12px;font:inherit">上一頁</button> <button id="next" style="padding:12px;font:inherit">下一頁</button></p>
<h2>七、開發中失敗紀錄沒有刪去</h2><p>首次独立驗算曾有圖形分類對應表的測試期望錯誤；修正驗算映射後再跑。手機慢移測試一開始以沒有活動指標的合成pointerdown呼叫setPointerCapture，造成測試事件錯誤；改用真實Chromium指標按下再取消後通過，沒有把測試錯誤冒充原程式漏洞。</p><p>交付檢查另捕捉到新增第七個慢移鍵後，320px全螢幕控制列超寬；已改成兩行，並重新跑所有交付套件。這是R3開發中引入的回歸，原失敗結果亦保留。另在最終題面檢查補上了「另解說明套入例題實際參數」及「分類題概念頁顯示文字答案而非內部數字碼」，再檢查所有122個概念頁及20個奧數另解頁。首輪結果與最終結果分別保留，失敗不會被刪成從未發生。</p>
<h2>八、備份、啟動及檔案完整性</h2><p>解壓後開START_HERE.html；一般用家不需要Python。Windows靜態啟動器仍需真機驗收，固定聲線另需可選Node20+與家長自行配置的服務金鑰。不要把金鑰寫入前端或分享；程式沒有代為啟用任何付費服務。</p><p>先在舊程式分別匯出英文、孩子數學及自訂媒體；R3可建立新的家庭完整JSON。JSON未加密；不能公開。程式ZIP不含你的真實瀏覽器學員資料。</p>'''
body+=f'<p>原R2的769個原檔：{sum(x["kind"]=="unchanged" for x in preserve["files"])}個保留原路徑，{sum(x["kind"]!="unchanged" for x in preserve["files"])}個被修改的原件另存originals/R2。對照表為r3_evidence/R2_PRESERVATION.json。最終檔案清單為PACKAGE_MANIFEST.json與SHA256SUMS.txt；清單不包含自己的雜湊，以免循環。</p>'
body+='''<p class="muted">原有歷史報告仍保留，但其版本／數字不能當作R3結果。R3不是已完成官方課程、零漏洞、商用安全或學習成效認證。</p>'''
data=json.dumps(allcases,ensure_ascii=False,separators=(',',':')).replace('</','<\\/')
script='''<script>const DATA=__DATA__;let page=0;const $=id=>document.getElementById(id);for(const g of [...new Set(DATA.map(x=>x.group))]){const o=document.createElement('option');o.value=g;o.textContent=g;$('group').append(o);}function render(){const q=$('search').value.toLowerCase(),group=$('group').value,rows=DATA.filter(x=>(!group||x.group===group)&&JSON.stringify(x).toLowerCase().includes(q));page=Math.min(page,Math.max(0,Math.ceil(rows.length/50)-1));$('cases').replaceChildren();for(const row of rows.slice(page*50,page*50+50)){const tr=document.createElement('tr');for(const v of [row.group,row.id,row.name,row.status==='pass'?'通過':'未通過']){const td=document.createElement('td');td.textContent=v;tr.append(td);}$('cases').append(tr);}$('count').textContent=rows.length+'項；第'+(page+1)+'頁';$('prev').disabled=page===0;$('next').disabled=(page+1)*50>=rows.length;}$('search').addEventListener('input',()=>{page=0;render()});$('group').addEventListener('change',()=>{page=0;render()});$('prev').onclick=()=>{page--;render()};$('next').onclick=()=>{page++;render()};render();</script>'''.replace('__DATA__',data)
report='<!doctype html><html lang="zh-HK"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>WordQuest R3｜升級與驗證報告</title><style>'+css+'</style></head><body><main>'+body.replace('未记录','未記錄').replace('首次独立','首次獨立')+'</main>'+script+'</body></html>'
(D/'R3_升級及驗證報告.html').write_text(report);(R.parent/'WordQuest_R3_Upgrade_Report_20260929.html').write_text(report)
print(json.dumps({'other_cases':result['other_case_count'],'questions':3660,'report_bytes':len(report.encode()),'all_suite_cases_pass':True},indent=2))
